### ISSUE TITLE
[1.12.2] Crash upon entering world

### ISSUE THREAD

**Issue by xilni** [McJty/LostCities#101]
**MC version:** 1.12.2
**Pack:** FTB Revelation 1.6.0
**jar version:** lostcities-1.12-2.0.2

When I updated my server from FTB Revelation 1.4.0 to 1.6.0 I got [this client crash log](https://pastebin.com/wKCSqd1v) within 1 second of entering world.

I wanted to see if it was the custom profile that we were using (without any problem until the upgrade from lostcities-1.12-1.0.2) so I attempted to restart the server using one of the default profiles (changing the appropriate fields in the server.properties generator settings) but then got [this server crash log](https://pastebin.com/C6jyZeBU) despite the me removing any mentions of this profile in the configs in the server directory (verified per a thorough grep search). Perhaps there issome non clear text setting in the world/ folder that's persisting?

EDIT: typo

**Comment by McJty** [comment]
The profile is remembered in the world save. So you cannot really do that

**Comment by xilni** [comment]
Figured as much, any reason why I'm getting the first crash log then after the upgrade?


Grabbed these from the server in case they were helpful
[general.cfg](https://pastebin.com/HzzZf1w4)
[profile_ultrararetallcities.cfg](https://pastebin.com/4jRkdU1B)
[server.properties](https://pastebin.com/sda4qQd8)

**Comment by McJty** [comment]
yes that's a bug on my side. I will fix this. You can avoid this bug temporarily by avoiding the fog settings

**Comment by xilni** [comment]
Ok, I don't believe I made any changes to the fog settings (at least intentionally), so would the fix involve setting the four fog settings in the profile (RGB + Density) to 0.0?

```
client_ultrararetallcities {
    # This is used client-side (but only if the client has this mod) for the fog color [range: -1.0 ~ 1.0, default: -1.0]
    S:fogBlue=-1.0

    # This is used client-side (but only if the client has this mod) for the fog density [range: -1.0 ~ 1.0, default: -1.0]
    S:fogDensity=-1.0

    # This is used client-side (but only if the client has this mod) for the fog color [range: -1.0 ~ 1.0, default: -1.0]
    S:fogGreen=-1.0

    # This is used client-side (but only if the client has this mod) for the fog color [range: -1.0 ~ 1.0, default: -1.0]
    S:fogRed=-1.0

    # This is used client-side (but only if the client has this mod) to set the height of the horizon [range: -1.0 ~ 256.0, default: -1.0]
    S:horizon=-1.0
}
```

**Comment by McJty** [comment]
Hmm no. That will not help. Are the configs for Lost Cities the same on server vs client? That could also cause the problem

**Comment by xilni** [comment]
Manually syncing the general.cfg and the profile did the job and no more crashes.

Strange I thought the syncing of config files happened upon login?

**Comment by McJty** [comment]
Not entirely. The client requests which profile is used from the server. But the profile settings are local. The crash happens because there is a small delay in requesting this data so the client doesn't know which profile to use right now. I will fix that but you will have to sync some data over because configs are not send to clients automatically

**Comment by xilni** [comment]
Thank you very much for the help. This issue caught me off guard because we didn't experience it in lost cities 1.0.2 when we were on FTB Revelation 1.4.0. 

I'll distribute the general.cfg and the profile cfg to our players until it's fixed.

**Comment by McJty** [comment]
I can't 100% fix it but I'll give a better error in the logs in the next version. The clients really need the correct configs from the server
