### ISSUE TITLE
Unable to spawn outside Biospheres

### ISSUE THREAD

**Issue by Tedyhere** [McJty/LostCities#103]
Version 
1.12-2.0.4

Wanting to spawn outside Biospheres in a wasteland.. Here are my two configs.
profile_bio_wasteland.json
https://pastebin.com/6g681BsV

profile_biosphere.json
https://pastebin.com/ffEhLcY0

**Comment by McJty** [comment]
Use:
S:spawnSphere=<out>

instead of:
S:spawnSphere=out

Let me know if that doesn't work still

**Comment by Tedyhere** [comment]
Ok changed it in both configs and still spawning inside spheres

**Comment by McJty** [comment]
Um. I just see github formatting ate the thing I wanted to say. Let me tell you in discord

**Comment by McJty** [comment]
Fixed in 2.0.5
