### ISSUE TITLE
More intragrations please

### ISSUE THREAD

**Issue by Landstryder** [McJty/LostCities#104]
Is there a way to have have Lost Cities generate in other dimensions other than the one created by this mod? I'm using Advanced Rocketry and the Dalek mod in my modpack and both add MANY dimensions. I would really appreciate a way to whitelist other dimensions for spawning lost cities in, and also if you could specify what style of generation for each of those dimensions.

Right now I have the Lost City dimension mapped to a planet with Advanced Rocketry so you have to get there using rockets (disabled the bed transport by setting the block to something unattainable). Ideally I want to have some dome cities spawn on "Mars" and the underwater domes spawn on "Titan", and maybe add some rare ruined cities to the planets added by the Dalek mod (since they are pretty boring in the current release).

**Comment by McJty** [comment]
I have plans for additional Lost City dimensions that you can specify in the config. Does that solve your problem?

**Comment by Landstryder** [comment]
Yea that would be awesome and plenty enough. If you can add the option to generate in dimensions that are added by other mods as well that would just be beyond awesome :)

Thanks very much!

**Comment by IcedReaper** [comment]
Hey,

I'd like to ask how the status of this options is.

Thanks in advance.
IcedReaper.

**Comment by McJty** [comment]
Generating in dimensions that are not Lost Cities is not possible I'm afraid. However, the option to have multiple Lost City dimensions has been implemented some time ago. Just forgot to note it here

**Comment by IcedReaper** [comment]
That's sad, but thanks for the Info and all your mods. :)
I'll try to create a second dimension (only a few cities here and there) via Lost cities that will replace the overworld and try to set this new dimension as the spawning dimension.
That way I'll have a "dead"dimension but ok.
