### ISSUE TITLE
World Generation - Lost Cities (BOP) - Empty Chunks

### ISSUE THREAD

**Issue by geleugim** [McJty/LostCities#11]
When I create a new world using Lost Cities (BOP) I find whole chunks with no blocks just bedrock.

https://1drv.ms/u/s!AqEmijhm9Cu7qrNOU5_9fd8bg6ANiA
https://1drv.ms/u/s!AqEmijhm9Cu7qrNPpw-3cc7Cm3Xipg

**Comment by McJty** [comment]
What version?

**Comment by geleugim** [comment]
I am using All the Mods 3 mod pack for 1.12
lostcities-1.12-0.0.7beta.jar

**Comment by McJty** [comment]
This bug has been fixed already
