### ISSUE TITLE
The biome "river" is shifted away from the river basin

### ISSUE THREAD

**Issue by BlayzerQ** [McJty/LostCities#110]
Mod version: lostcities-1.12-2.0.4
The biome "river" is shifted away from the river basin when using lostcities_bop worldtype (see screenshoots)

![ytb2ubuzaxm](https://user-images.githubusercontent.com/10747701/37229411-f0cdf940-23f4-11e8-9fa0-b88fc5ff92fb.jpg)
![xzqyn9oyofi](https://user-images.githubusercontent.com/10747701/37229415-f3249668-23f4-11e8-8cf2-041889440c6a.jpg)

**Comment by McJty** [comment]
That's not something my mod is doing

**Comment by FReEzZzi** [comment]
But this happens only on your lostcities_bop level-type 💡

**Comment by McJty** [comment]
Still not something I have control over. I don't handle biomes

**Comment by drakray** [comment]
(sorry to post this here as a starting point, trying to find why this is, without opening a new issue)
I got this too, easily visible in the middle desert of my rendered map
![serverworldmagic](https://user-images.githubusercontent.com/4303126/39136022-518c27dc-46e8-11e8-8a6f-69a36b66bd48.png)
Could it be a BiomesOPlenty issue? in which case I could open an issue there referencing this one
I got a couple of mods adding biomes, namely BoP, AbyssalCraft, Evilcraft, RandomThings and NetherEx
Unless it's a Customized Preset World thing?, I use https://pastebin.com/vqy5e0cp , which have BiomeSize = 3

**Comment by BlayzerQ** [comment]
The problem is relevant. I think the problem is with the BiomeProvider and ChunkGenerator of mod Lost Cities.

**Comment by BlayzerQ** [comment]
Maybe this fix shfting rivers?
https://github.com/Glitchfiend/BiomesOPlenty/blob/a9e42935d0d3ae4cd9c915854045826307633b3d/src/main/java/biomesoplenty/common/world/ChunkGeneratorOverworldBOP.java#L352
