### ISSUE TITLE
Biomes stick together

### ISSUE THREAD

**Issue by BlayzerQ** [McJty/LostCities#111]
Mod version: lostcities-1.12-2.0.4
Biomes stick together (there are never less than three biomes generated near) when using lostcities_bop worldtype (If to use default worldtype or BIOMESOP, they are generated separately). 
![g1awuohwybs](https://user-images.githubusercontent.com/10747701/37229553-5ca691a4-23f5-11e8-9a91-d6ac9bd24cb8.jpg)
![urobbthkogk](https://user-images.githubusercontent.com/10747701/37229635-b0c86a6e-23f5-11e8-8183-f7616a4676ea.jpg)

**Comment by McJty** [comment]
You're all reporting this but lost cities just uses the biomes as they are generated. So not much I can do about this. In addition I don't understand what is actually wrong

**Comment by FReEzZzi** [comment]
Desert world, and biomes should be single islands in the desert. But when using the parameter level-type = lostcities_bop they are glued together

**Comment by McJty** [comment]
I don't understand what you mean by 'single islands'?

**Comment by BlayzerQ** [comment]
Like islands in the sea, but in the desert. This concept of modpack - one island, one biome.

**Comment by McJty** [comment]
I still don't really understand what you mean by these islands but I think the problem you describe may have to do with me filtering the biomes because most biomes are restricted.  So in other words this is intentional
