### ISSUE TITLE
[SUGGESTION] Allow adjusting road width

### ISSUE THREAD

**Issue by wooky** [McJty/LostCities#12]
I want to replace the generated roads with my own road, but I don't like the fact that the width of the generated road doesn't match my own. It would be nice if I could adjust the width of the generated road through the config.

**Comment by Flabort** [comment]
I agree. When a fountain generates in the road, it's often just as large as the road, creating a break in the road. I'd like to be able to use the config to make roads just a bit wider.

**Comment by McJty** [comment]
The width of the roads is already configurable in the json asset system. Unfortunatelly this is poorly documented. But basically you could add a custom asset replacing the common citystyle. The width of the road is a parameter of the citystyle. It is not very easy to modify this atm. You basically have to replace the citystyle assets with your own

**Comment by Flabort** [comment]
Cool. I hope more documentation for the asset system comes soon then.

**Comment by McJty** [comment]
Working on this right now

**Comment by McJty** [comment]
Done (more or less)

**Comment by wooky** [comment]
I want to set the width to 7 blocks, but I was only able to set it to either 6 or 8 blocks. Is it not possible to set it to an odd number of blocks?

**Comment by McJty** [comment]
No that can't work because chunks are even and with 7 it would be pretty hard to fit roads on all sides
