### ISSUE TITLE
Option To Generate City Spheres other World Presets

### ISSUE THREAD

**Issue by Boolyman** [McJty/LostCities#128]
Title pretty much says it all.  If I am not misunderstanding the mod capabilities, your city spheres can only be generated if the Lost Cities world generation option is selected.  Is there a way to toggle a config option to generate them in any world type we select?  Certain mods, like Void Island Control only support the world selection of the vanilla options.

**Comment by McJty** [comment]
That's unfortunatelly not possible. Lost Cities can only work through a world type. Sorry
