### ISSUE TITLE
Adding Nether/End as Lost Cities City

### ISSUE THREAD

**Issue by Mattabase** [McJty/LostCities#129]
Crash https://goo.gl/euexcU

Config https://goo.gl/CLaohr

hoping to give them their own lost cites profiles.

**Comment by josephcsible** [comment]
`<-1>:<space>` should just be `-1:space`.

**Comment by Mattabase** [comment]
That is exactly why I linked the config.

I was assuming it was user error. Thanks.

**Comment by josephcsible** [comment]
Did that fix it? If so, please close the issue.

**Comment by Mattabase** [comment]
Taking a look now to make sure.

**Comment by Mattabase** [comment]
It has a different crash now, I assume I can use these for Vanilla Dimensions?

Crash https://goo.gl/nF7A6m
Config https://goo.gl/i8g1hA

**Comment by McJty** [comment]
No, it is not possible to replace the vanilla dimensions with these (except for the overworld)

**Comment by Mattabase** [comment]
Thank you for clearing that up. =)

**Comment by Normal69** [comment]
Just reopened this for a little talk - I don't want to make a totally new issue if one exists already.

You see my players hate the nether, so I am working on a pack, where there is none.
I aim in the modpack for this (did it before in one called "Expertion" via another mod) and one of my MC friends notified me about Lost Cities + Lost Souls.

But as you've mentioned above using -1:wasteland derailed the pack, as "the provider was already registered".

I am aiming for a pack which could be either used in SP or MP, and it is possibble that I can use allow-nether=false in the server.properties (it would be a hardcore upgrade for my "Howdy do we do?" pack).
But that won't make it possibble to play in single, and for me to test it in single beforehand.

So it would be wonderful if you could totally take over of existing dimension generation (I mean not to make cities in the Nether or in the End but generate the whole dimension in your way) as I would like to surprise my players after they reluctantly step thru a nether gate with a collection of desolate buildings under a clear sky to hunt for loot and clear haunted buildings.

Of course the nether resources already are provided in the overworld generation via another mod.
I have already sought a mod which prevents Nether provider registration to no avail.

Please can you give me some information on this, or (which I cannot hope) make your mod more agressive to unregister that useless Nether (or even End) generator, if your general.cfg says so?

Thank you.
