### ISSUE TITLE
[1.1x-0.0.9] Cascading Worldgen Issue

### ISSUE THREAD

**Issue by Alaberti** [McJty/LostCities#13]
https://pastebin.com/mjjBQViZ

Seeing that in my client console. I'm using the preset that makes the entire world a city when I get this error, then the game locks up and becomes unresponsive.

**Comment by McJty** [comment]
I'll check it out

**Comment by McJty** [comment]
Should be fixed next release

**Comment by Alaberti** [comment]
It still comes up, but far less than before, and doesn't seem to scale out of control anymore. Running through different presets seems to confirm it's waaaaay better.
