### ISSUE TITLE
The Lost Cities loaded a new chunk [-10, -5] in dimension 111 (lostcities) while populating chunk [-9, -6], causing cascading worldgen lag

### ISSUE THREAD

**Issue by Chronic-Reflexes** [McJty/LostCities#133]
my mods: buildcraftlib@7.99.12,openmods@0.11.5,rftools@7.33,buildcraftenergy@7.99.12,jei@4.9.1.188,buildcrafttransport@7.99.12,cofhcore@4.4.1,nei@2.4.1,mekanism@1.12.2-9.4.8.343,thermalfoundation@2.4.1,techguns_core@1.12.2-1.0,mcp@9.42,ctm@MC1.12-0.2.3.12,xnet@1.6.9,appliedenergistics2@rv5-stable-11,inventorytweaks@1.63+release.109.220f184,foamfixcore@7.7.4,secretroomsmod@5.6.3,waila@1.8.24,mekanismgenerators@9.4.4,mcjtylib_ng@2.6.7,mcmultipart@2.5.1,forge@14.23.4.2703,buildcraftrobotics@7.99.12,openblocks@1.7.6,weaponlevels@2.3.3,minecraft@1.12.2,charset@0.5.0.246,notenoughcodecs@0.6,redstoneflux@2.0.1,buildcraftsilicon@7.99.12,openmodscore@0.11.5,concheckrmd@1.4-multi,srm-hooks@1.12.2-1.0.0,lostsouls@1.1.4,buildcraftbuilders@7.99.12,buildcraftfactory@7.99.12,securitycraft@v1.8.4.1,autoreglib@1.3-17,lostcities@2.0.7,FML@8.0.99.99,thermalexpansion@5.4.2,mekanismtools@9.4.4,chisel@MC1.12.2-0.2.0.31,minetogether@unspecified,minetogetherserver@unspecified,foamfix@0.9.9.1-1.12.2,codechickenlib@3.1.8.341,morphtool@1.2-16,buildcraftcore@7.99.12,forestry@5.8.0.280,mobends@0.24,techguns@2.0.1.1

Im running latest sponge api, with nucleus, world edit, and luckperms

**Comment by Chronic-Reflexes** [comment]
gotta love when the dev of a world gen mod wont reply when its causing cascading lag to a server, rendering it unplayable while generating chunks

**Comment by McJty** [comment]
Vanilla bug (vanilla has a few instances where it also does this, for example emerald generation)

**Comment by McJty** [comment]
And btw, if there is a problem with lag it is not caused by this

**Comment by Chronic-Reflexes** [comment]
but its doing it for every single chunk generated, and no lag vs when the lost cities isnt installed, im not trying to knock the mod, its amazing, and i wanted to use it on my server, its just that the lag is bringing it to its knees

**Comment by McJty** [comment]
Well lost city world generation is a bit more heavy then usual worldgen. My guess is that it is simply caused by normal chunk generation and the lag should go away once that has done

**Comment by josephcsible** [comment]
If you want this to be investigated, reproduce the problem with only Lost Cities installed, and post the configuration and seed that leads to a message.
