### ISSUE TITLE
Problem login into server while logged out from Twilight Forest Dim due to Lost Cities

### ISSUE THREAD

**Issue by chezpaul** [McJty/LostCities#136]
Hey, it seems like Twilight Forest or Lost Cities is not allowing me to re login to my server.
Using Lost Cities 2.0.8 with MCtJyLib 2.6.7 on a Forge 2707 1.12 server

[Twilight Forest GitHub Link](https://github.com/TeamTwilight/twilightforest/issues/545#issuecomment-395168245)

**Comment by McJty** [comment]
Fixed in Lost Cities 2.0.9

**Comment by chezpaul** [comment]
You must be the coolest modder out there.  ;-)
Thanks.
Any timeframe idea for release?  ;-)

Oh it's already out...  hehe
