### ISSUE TITLE
1.11.2 Dimension Portal Structure NPE in survival single player

### ISSUE THREAD

**Issue by Knito58** [McJty/LostCities#14]
https://www.dropbox.com/s/a3bnpdl73raaofc/fml-client-latest.log?dl=1
https://www.dropbox.com/s/za1e72x4d1kfulj/latest.log?dl=1

**Comment by McJty** [comment]
Thanks. I will check this out and see what's wrong

**Comment by Knito58** [comment]
Thank you.
Konitor

**Comment by McJty** [comment]
Ah could you add your lostcity/general.cfg too?
I'd like to see if something went wrong there

**Comment by McJty** [comment]
Never mind
I know what's wrong

**Comment by McJty** [comment]
Will be fixed next release (in a few hours from now)

**Comment by Knito58** [comment]
Sorry was afk. Do you work day and night?
https://www.dropbox.com/s/fpa8vwj7u58cmya/general.cfg?dl=1
Just to be complete....
