### ISSUE TITLE
[1.12.2] Cities won't generate inside spheres

### ISSUE THREAD

**Issue by DWX12** [McJty/LostCities#140]
Working on world gen for a modpack I'm making, but I can't seem to get it to look or work the way I want it. I'm trying to get typical cities to generate inside of spheres, but so far all I get are empty spheres with railways connecting to each other along with there being a ton of spheres and close together. I'm not sure what exactly I'm doing wrong or not doing correctly.

On my last attempt, I did get cities to spawn, but only outside of the spheres. I'm keeping the landscape the same inside the spheres as outside so I don't need to use two profiles. I'm also aiming for there being flooding, but not so much that it's a water world in addition to having the world start at a very high elevation, around 110. My goal is to have it look like a futuristic post apocalyptic world with ruined buildings, plenty of craters all over the world (inside and outside the cities), and broken domes. I also want the cities to be pretty rare, which I can accomplish without the spheres. Worst case, I'll just do without the domes.

One other question, is there a way for me to smooth out the explosion craters so that they don't look so "noisy" or "pixelated"?

I sent you a copy of my config, which I also pasted in hastebin. Which ever is more convenient.

https://hastebin.com/nesiqevegu.coffeescript

[profile_space_quest.zip](https://github.com/McJtyMods/LostCities/files/2092633/profile_space_quest.zip)

**Comment by McJty** [comment]
Hmm not sure that you can work with only one profile to be honest. I think you *must* use two profiles for this type of world.

**Comment by DWX12** [comment]
Don't really understand why since my understanding is that you only use a second profile if you want outside landscape to be different than the inside. In that case, it should still generate cities regardless. Unless the profile picks landscapes over city generation, which it seems to be doing except for spheres.

Another question, if I'm using spheres and want to reduce the amount of cities and spheres that show up, do I use the sphere chance or the city chance? Are they tied together or separate? Are spheres tied to landscape generation?

One other comment I want to make about spheres is that the cities that generate in the various other profiles seem to be very small, nowhere near as large cities without spheres. If I were to make the spheres larger then would bigger cities spawn inside?

Thank you so much McJty for all of your wonderful mods and your contribution to the community, it means alot.

**Comment by DWX12** [comment]
So it seems that spheres and cities are NOT mutually inclusive or rather that they are two separate things. Setting the city spawn rate too low will cause spheres to just not generate any inside, and likewise, setting sphere generation too low will just cause them to not generate, including cities.

I'm still continuing to learn the world generation possibilities with this mod, but for the moment, it seems that you can't really replicate regular cities and have a sphere generate over them. The city generation seems cramped and alot smaller inside spheres. Also, I can't seem to get bridges or highways to generate like monorails do. I know bridges are possible, but not sure if highways are with sphere types.

Thanks again
