### ISSUE TITLE
"Drowned World" Highways don't want to be drowned

### ISSUE THREAD

**Issue by Seth0067** [McJty/LostCities#15]
Hey there - you've probably seen this, but the highways are not generating underwater as the surrounding structures are, leading to "holes" in the oceans above the highway surface.  

[screens](http://imgur.com/a/tnxr7)

Did get a pretty quick crash as well.  [crash paste](https://pastebin.com/ZjUDxgXn)

Edited to add that this was LC (BoP) worldtype 1.11.2

**Comment by McJty** [comment]
I will check it out

**Comment by McJty** [comment]
Fixed next release
