### ISSUE TITLE
[feature request] Within biome settings of a profile, allow a base fluid choice

### ISSUE THREAD

**Issue by Rosethorns** [McJty/LostCities#158]
It would be useful if the world generator profile could have a base fluid choice
For example instead of the default water, river/ocean/deep_ocean and lake decorations could have their fluid option changed to something else.
For example lava. Wherein all bodies of water would be replaced with lava.

**Comment by McJty** [comment]
That's a good idea. I think I can do that

**Comment by McJty** [comment]
Done
