### ISSUE TITLE
[Question] How to make Lost Cities work in Nether?

### ISSUE THREAD

**Issue by donqixot** [McJty/LostCities#159]
I tried 2 options in config:
    S:adaptingWorldTypes <
        -1
     >

that doesn't work. i also tried

    S:additionalDimensions <
		-1:cavern
     >

This is causing error "Failed to register dimension for id -1, One is already registered".

Anything else I can try? And thanks for this mod, amazing!

**Comment by McJty** [comment]
I'm afraid this is not implemented right now. That's something I might do in the future but right now it is not possible

**Comment by donqixot** [comment]
One simple option would be to allow buildings above bedrock ceiling while their basement will provide break thru bedrock and tunnels running under bedrock. This may be easier to implement with existing code?

**Comment by McJty** [comment]
Worldgen isn't the issue. I actually already have nether like worldgen (the 'cavern' profile). And if you (with the latest version) select netherack as base block and lava as base liquid you can make a custom lost city dimension that almost looks like the nether. The only thing Lost Cities cannot do right now is actually take over the nether dimension

**Comment by donqixot** [comment]
Thanks! I will try new dimension. I close this issue for now, hopefully, when you have time you can look into taking over the Nether :) Thanks for all your amazing mods!
