### ISSUE TITLE
 .10 Beta Crash-to-desktop while pregenerating world

### ISSUE THREAD

**Issue by Seth0067** [McJty/LostCities#16]
Also on 1.11.2 with a BoP world under the "chisel" type - but with tall city buildings and some other cfg changes.

[crash paste](https://pastebin.com/NBYMAW8X)

I was using a chunk pregeneration command block to pregen a potential server world and the crash occured very early on.  If there's more info i can get you here (cfgs or world seed) let me know.  

FYI, I dont necessarily post these from a "hey there, mod developer, fix my bugs" perspective, but just to give you more info that might help you in your efforts to optimize the mod.  If it becomes more noise than signal, just let me know.

**Comment by McJty** [comment]
I will check it out. Thanks for reporting

**Comment by McJty** [comment]
Fixed in 0.0.11 which will be released shortly
