### ISSUE TITLE
[Request] Wasteland Reborn Compatibility

### ISSUE THREAD

**Issue by SaucissePuree** [McJty/LostCities#160]
Hi & Thanks for this great mod.
Can you add the same Worldgen compatibilty you made for BOP with Wasteland Reborn please ?
Because BOP + wasteland profile insists to spawn some biomes that i don't want,
and Wastland Reborn seems to be the mod that fits best with Lost Cities (for a Post-Apo Modpack).
Thank you (sorry my english sucks).

Wasteland Reborn  : [https://minecraft.curseforge.com/projects/wasteland-reborn](url)

**Comment by McJty** [comment]
Adding support for another worldtype actually has to be done by the other worldtype. It is extremely hard to do that from Lost Cities. I have an API for that. The only reason I could do it with BoP is that for BoP I'm actually only using the biomes and not the worldgne itself

**Comment by SaucissePuree** [comment]
OK, thank you for your answer
