### ISSUE TITLE
Lostcities crash with Sponge (again)

### ISSUE THREAD

**Issue by duhadventure** [McJty/LostCities#166]
Sponge Version:
Forge Version: 2768
LS Version: 2.0.12

The Worldgen bug has returned!
https://pastebin.com/PDYYhHBs

**Comment by josephcsible** [comment]
Try again with this build and post the new crash report: [lostcities-1.12-2.0.12+8efe8c3.zip](https://github.com/McJtyMods/LostCities/files/2551274/lostcities-1.12-2.0.12%2B8efe8c3.zip)

**Comment by duhadventure** [comment]
https://pastebin.com/1e8srgnp
Here you go

**Comment by josephcsible** [comment]
It looks like you have a blank line in allowedBiomeFactors in your Lost Cities profile config. Remove that and see if the crash goes away.

**Comment by duhadventure** [comment]
I think it works but the dimension wont load...

**Comment by josephcsible** [comment]
Why not? What happens now? Can you post the new logs?
