### ISSUE TITLE
Lost Cities and JustEnoughIDS - Major World Generation Issues

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [McJty/LostCities#176]
I ran a large few test and I was able to determine that when JEID is active Lost Cities generates at level 5-1 here is a picture with what to expect.
![2019-01-15_04 52 06](https://user-images.githubusercontent.com/10351221/51176076-a0416980-1881-11e9-8a40-78f2840649e9.png)
![2019-01-15 04_54_17-minecraft 1 12 2](https://user-images.githubusercontent.com/10351221/51176106-b6e7c080-1881-11e9-87c3-e836295ae1b5.jpg)
https://github.com/P3rf3ctXZer0/Zer0Necrosis-Project-Workbench/issues/3

**Comment by McJty** [comment]
Lost Cities does not support JEID. We do support NotEnoughIds though

**Comment by P3rf3ctXZer0** [comment]
Why?

**Comment by McJty** [comment]
Well NotEnoughIds was first and we added support to that. I have no idea why there should be another mod to extend ID's? It is a bit of a hassle to have to support all of these mods so I'd like to limit it to one

**Comment by P3rf3ctXZer0** [comment]
Here is an example https://github.com/fewizz/NotEnoughIDs/issues/83

**Comment by McJty** [comment]
An example of what?

**Comment by P3rf3ctXZer0** [comment]
Fewizz was not focusing on biome id limit he was focusing on block limit. JEID is focusing on all limits removed

**Comment by McJty** [comment]
Well I can reopen this but I don't have the time at the moment to write support for it. If there is someone who would be willing to do that without sacrificing performance and making it messy then that's fine

**Comment by P3rf3ctXZer0** [comment]
Trust me I support @Fewizz too and I understand that it is not easy to just add support but the fact that my entire 164 mod pack was built on JEID makes this difficult for me as well. Also one other major way JEID is 1.13.2 safe and once forge publicly releases 1.13.2 builds I will just be able to use my world since JEID is basically the 1.13 save systems ported.

**Comment by P3rf3ctXZer0** [comment]
@Runemoro could you help us please?

**Comment by McJty** [comment]
Ok, note however that transfering your worlds from 1.12 to 1.13 will most likely not work because all the mods will be very incompatible. I don't plan on maintaining compatibility with my mods between 1.12 and 1.13 because that's way to much work and I'm taking the chance to do some major restructurings. I guess many other bigger mods will do the same

**Comment by P3rf3ctXZer0** [comment]
Understood. You are probably not wrong. I will probably keep rolling 1.12.2 until forge modding is stable for 1.13+

**Comment by MokahTGS** [comment]
So is this currently still incompatible with JEIDs?

**Comment by McJty** [comment]
Yes but not for long. I have a fix almost ready for release

**Comment by ZombieHDGaming** [comment]
Thanks for adding support @McJty, didn't mean to make you have to do it yourself. To be honest, I'm not quite sure what caused the chunks to just up and do that, but I'm glad you were able to add support on your end (if it did in fact work). We'll still be sure to add support on JEID's end for the biome ID expansions and such so it's not so much of a hassle on your end for it, but that should definitely add some much needed support between the 2 mods.

Sorry about it being such as a hassle though 😅 if you ever need any help with support or anything what so ever between any of our mods, feel free to ping me here or in your Discord server under the same name, I'm almost always available to help (except when I'm sleeping lol).

**Comment by McJty** [comment]
This was fixed some time ago
