### ISSUE TITLE
[suggestion] Compatibility both with BoP and CBP. 

### ISSUE THREAD

**Issue by Bulldog83** [McJty/LostCities#178]
Hello! Can you make LostCities compatibility both with BoP and Climatic Biome Placement mod?

**Comment by McJty** [comment]
It's already compatible with BoP but don't know what that other mod does?

**Comment by Bulldog83** [comment]
https://minecraft.curseforge.com/projects/climatic-biome-placement

**Comment by Bulldog83** [comment]
I've tryed to add climatic_bp (CBP world type) to "adaptingWorldTypes" in the LC config, but it didn't take effect.

**Comment by BlackJar72** [comment]
Change the chunk provider to "lostcities" in the CBP config ... you will get lost cities.

**Comment by Bulldog83** [comment]
Great, thanks!
