### ISSUE TITLE
Error when creating Lost Cities dimension

### ISSUE THREAD

**Issue by CaptainSisko** [McJty/LostCities#179]
I am getting an error in console when the Lost Cities dimension is being created on startup and i also receive an error when attempting to travel to the dimension via the bed.

The server doesnt crash for either error.

Server Startup Error
https://hastebin.com/tiruvutibi.css

Error when trying to travel to the dimension via the bed
https://hastebin.com/eruhitegeg.rb

Without sponge installed the issue does not occur.

It looks like this is related to this issue https://github.com/McJtyMods/LostCities/issues/142 but there hasnt been any update on that ticket since July last year.

It also looks as though there was an attempted fix for this on a fork here https://github.com/lolnetnz/LostCities/commit/3985bf447e06dc598aa8a252c4a9462e3c44eeb6 but i havent built their version to see if it actually works.

**Comment by McJty** [comment]
Do you have sponge? If so please report to them as I don't know how to fix sponge related errors

**Comment by CaptainSisko** [comment]
Sorry i should have made it more clear that yes i am using sponge.

This issue has already been [reported to sponge](https://github.com/SpongePowered/SpongeCommon/issues/1944) as mentioned in issue https://github.com/McJtyMods/LostCities/issues/142 however according to Gabizou https://github.com/SpongePowered/SpongeCommon/issues/1944#issuecomment-397784127, this issue is not likely to be fixed on Sponge's end.

BloodMC from sponge posted a possible fix https://github.com/McJtyMods/LostCities/issues/142#issuecomment-406838832 but according to the comment block on the [fork that i linked](https://github.com/lolnetnz/LostCities/commit/3985bf447e06dc598aa8a252c4a9462e3c44eeb6), BloodMC's fix doesnt work, although they appear to have "fixed" the issue another way. Whether or not their fix works i dont know as i have not built it and tested it.

**Comment by LokeYourC3PH** [comment]
Having the same issue, and from what I have seen, Sponge isn't the one who needs to fix this, though they said that they won't really fix it either. Hope you can fix this McJty, I really love this mod so much and wanted to use it on my new server :(

**Comment by UmbraGaming** [comment]
I have created a pull request containing the changes needed to fix this issue

https://github.com/McJtyMods/LostCities/pull/183

I have built and tested this with sponge, it launches and the dimension is created correctly on launch and loads correctly when teleporting there via the bed.

Whether or not this is the way that McJty wants to fix the issue is up to him.

**Comment by UmbraGaming** [comment]
@LokeYourLord The pull request i made has been approved so the fix should be in the next release.

**Comment by McJty** [comment]
Releasing right now
