### ISSUE TITLE
Chunk generation crash

### ISSUE THREAD

**Issue by Seth0067** [McJty/LostCities#184]
Not sure what this is, but thought I should forward to you...

[Crashy crash](https://pastebin.com/krMp8U0u)

**Comment by McJty** [comment]
Hmm. This is something that happens when a part is missing. Is this with modified assets?

**Comment by McJty** [comment]
Basically it is trying to get a floor part of a building and the building returns a part that doesn't exist

**Comment by Seth0067** [comment]
Ah - I see.  I am playing with modified buildings, yes, thanks.  Let me take another look at what I am doing. I'll let you know if I have any questions.

**Comment by Seth0067** [comment]
found the problem. thank you so much for your patience.
