### ISSUE TITLE
Array Out of Bounds While Chunk Generating

### ISSUE THREAD

**Issue by Damien-Reave** [McJty/LostCities#185]
Happens between a few seconds to a full minute after loading up a new world walking around.

Not sure what's going on, updated to the latest version of GTCE, Lost Cities and a few other mods and now these crashes. Pack was working fine previously.

https://paste.dimdev.org/petiyekebo.mccrash

https://paste.dimdev.org/okibetozaz.mccrash

Edit: Reverting to the 2.0.13 build fixes the crashes. 2.0.14 and up all cause them.

**Comment by McJty** [comment]
I might have an idea

**Comment by McJty** [comment]
Fixed in 2.0.17. I hope

**Comment by Damien-Reave** [comment]
Thanks!
