### ISSUE TITLE
Rare cities profile: still too many cities

### ISSUE THREAD

**Issue by ClaudiusMinimus** [McJty/LostCities#186]
We changed the following in profile_rarecities.cfg, to make cities rarer, but we are not noticing a difference when we reboot our server. 

> `# The chance this chunk will be the center of a city [range: 0.0 ~ 1.0, default: 0.002]
>     S:cityChance=0.0005`

The following variables have been set in server.properties:

> `level-type=lostcities
> ...
> generator-options={"profile"\:"rarecities"}`

Please let me know if we are missing something.
Thank you for an amazing mod!

**Comment by McJty** [comment]
Besides rebooting, did you also let the world regenerate?

**Comment by ClaudiusMinimus** [comment]
We have rebooted many times. We have tested this with many new local worlds and it seems the behavior may have changed in the most recent update. Regarding our server: We have not regenerated the world, but have rtp to new locations previously not generated expecting to reflect the settings change. 

Also, are we, in fact, changing the correct setting to reduce the chance of a city spawning?

**Comment by McJty** [comment]
You should use 'generator-settings' instead of 'generator-options'

**Comment by ClaudiusMinimus** [comment]
Will try it. Will post results. Thanks for your timely responses!

**Comment by ClaudiusMinimus** [comment]
In server.properties I changed as suggested from:
`generator-options={"profile"\:"rarecities"}`
to:
`generator-settings={"profile"\:"rarecities"}`
and it worked perfectly!
Thanks for your help!
