### ISSUE TITLE
Forge's Biome Dictionary improvement?For the lost cities BOP world generation type

### ISSUE THREAD

**Issue by SirAron111** [McJty/LostCities#191]
For some reason some mobs don’t spawn how they are support to in certain biomes. The modmaker of the mobs mod told me it must be because of the biomes themselves not having the compatibility. Can this be implemented? with the Bop world gen?

https://github.com/BobMowzie/MowziesMobs/issues/136

**Comment by McJty** [comment]
Lost Cities doesn't do biomes. It is just worldgen so that can't be the cause.
