### ISSUE TITLE
Client Crash OptimizedDriver

### ISSUE THREAD

**Issue by Kehaan** [McJty/LostCities#194]
Had a crash in singleplayer, while flying around. Just thought i would report it.

Using MC 1.12.2:

[crash-2019-04-02_11.39.53-server.txt](https://github.com/McJtyMods/LostCities/files/3033288/crash-2019-04-02_11.39.53-server.txt)

**Comment by McJty** [comment]
More info please? What kind of profile were you using?

**Comment by Kehaan** [comment]
Hm i may have had derped something xD I will close this, if i get it again i will report it once more and give some more info, sorry that i distrubed you.
