### ISSUE TITLE
Game crashes after leaving Lost Cities Dimension

### ISSUE THREAD

**Issue by aleXzzz1** [McJty/LostCities#195]
Hi,

I'm playing SkyFactory 4 on the twitch launcher (1.12.2). In SkyFactory 4 you enter and leave dimensions with cakes from a mod called 'TelePastries'. Whenever I leave the Lost Cities dimension using an overworld cake, my game almost instantly crashes and i get this crash report 
![crash](https://user-images.githubusercontent.com/49884917/56532911-39011880-6546-11e9-939e-8f8d650cdfaf.PNG)

Here is the full crash report: 
[crash-2019-04-22_21.21.02-server.txt](https://github.com/McJtyMods/LostCities/files/3104951/crash-2019-04-22_21.21.02-server.txt)

**Comment by McJty** [comment]
It is crashing in CodeChickenLib. Not caused by Lost Cities
