### ISSUE TITLE
Something wrong with Fog

### ISSUE THREAD

**Issue by DevTimur** [McJty/LostCities#198]
In version 2.0.17 fog was just fine.
I used this settings to get slightly dusty look in my world
https://imgur.com/a/4UlRn8A

> client_default {
>     # This is used client-side (but only if the client has this mod) for the fog color [range: -1.0 ~ 1.0, default: -1.0]
>     S:fogBlue=0.59
> 
>     # This is used client-side (but only if the client has this mod) for the fog density [range: -1.0 ~ 1.0, default: -1.0]
>     S:fogDensity=0.015
> 
>     # This is used client-side (but only if the client has this mod) for the fog color [range: -1.0 ~ 1.0, default: -1.0]
>     S:fogGreen=0.79
> 
>     # This is used client-side (but only if the client has this mod) for the fog color [range: -1.0 ~ 1.0, default: -1.0]
>     S:fogRed=0.92
> 
>     # This is used client-side (but only if the client has this mod) to set the height of the horizon [range: -1.0 ~ 256.0, default: -1.0]
>     S:horizon=-1.0
> }

But in version 2.0.18 i don't get any Fog doesnt matter what settings i use.

**Comment by McJty** [comment]
I see what happened. I will fix this

**Comment by McJty** [comment]
Fixed next release
