### ISSUE TITLE
[HELP] I cant find cities

### ISSUE THREAD

**Issue by Crosus97** [McJty/LostCities#200]
i cant find the generated cities

i delete all the chunks but I've been creative for 30 minutes looking for a city and I can not find it, do I need something in the server.properties?

[modlist.txt](https://github.com/McJtyMods/LostCities/files/3146254/modlist.txt)
[server.properties.txt](https://github.com/McJtyMods/LostCities/files/3146256/server.properties.txt)

I put in level_type: lostcities(with "_bot" and without "_bot")

[latest.log](https://github.com/McJtyMods/LostCities/files/3146255/latest.log)

i activate the debugmode and this is the logs
i explore all this 
![695975e0f3e2e8947e1c066eda1c5bf0](https://user-images.githubusercontent.com/46854222/57203131-9452f200-6fad-11e9-80f1-a20cd8e8af06.png)

any help?

**Comment by McJty** [comment]
After changing level-type to lostcities you did remove the already generated world?
Also it is 'lostcities_bop' not 'bot'

**Comment by Crosus97** [comment]
Nope...
