### ISSUE TITLE
Enhancement: Option to set default world type to lost cities/lost cities (BOP)

### ISSUE THREAD

**Issue by SirAron111** [McJty/LostCities#202]
I run a modpack where I recommend using the lost cities bop type chisel as world generation.

But some people simply click create world without changing away from the default world type forgetting to set it and then complain they can’t find the promised treasurers and all other stuff that come in the cities etc.

Would it be possible to add an option to make the lost cities or the lost cities with a choosable profile type (Chisel (I changed how many cities spawn etc and what types in the config of the profile) as a default other mods already have such a function so it should be possible)

**Comment by McJty** [comment]
There are other mods that can already do that. I'm not sure how they are called but they are used in modpacks like Sky Factory and others where the default worldtype is changed

**Comment by SirAron111** [comment]
Yes I know but adding a mod for a small function that probably adds in a lot of extra unwanted functions as well to a modpack that already has over 200 mods is pretty bad. And I thought that the function to set the cities as default should be integrated in the mod as it full feature of this mod is to make the world generate like that most other mods give this function in the config like set void world as default, set sky lands as default, set the wall (bedrock wall) as default, set garden of glass as default etc. I was just wondering why you don’t have this function in the general config.
