### ISSUE TITLE
generator-options={"profile"\:"rarecities"}

### ISSUE THREAD

**Issue by repomanz** [McJty/LostCities#209]
Hi mod creator!

Trying to help my son get this up and running.  We're hosting his server on alpine linux and when using this server.property configuration:  generator-options={"profile"\:"rarecities"}  the mod / minecraft escapes the : with a backslash.

Do you have a work around?  Tried other suggestions in the issues here. No luck.

**Comment by McJty** [comment]
Try generator-settings instead

**Comment by repomanz** [comment]
excellent. that worked, even with the extra \ being inserted.
