### ISSUE TITLE
[suggestion] water towers?

### ISSUE THREAD

**Issue by Seth0067** [McJty/LostCities#21]
Again, die hard New Yorker here.
[inspiration](https://cdn.shopify.com/s/files/1/0211/4926/files/P-WaterTower_Zoom.jpg?8117)
[visual](http://imgur.com/a/2WzU9)
[recurrent complex rcst file](https://www.dropbox.com/s/s09fe3noc5d7ikn/watertower.rcst?dl=0)

**Comment by McJty** [comment]
Oh nice! I'll add something like that on some of the roofs. Will be easy. Thanks :-)

**Comment by McJty** [comment]
Done!
