### ISSUE TITLE
Crash on first world load with custom configs

### ISSUE THREAD

**Issue by Damien-Reave** [McJty/LostCities#215]
I made some custom settings for Lost Cities (just combining aspects of certain default types) and get a crash instantly upon loading into the world for the first time.

Crash: https://pastebin.com/Gr41tBuT

Settings: https://pastebin.com/Gz2NJUme

I'll be playing around with it more and will update hopefully.

**Comment by Damien-Reave** [comment]
I tried a few things, including removing the duplicated maximum number of cellars line and the json generator options. I still get a crash after a few minutes of flying around in creative, though at least its not on world load anymore.

https://pastebin.com/VxTP3rPi

**Comment by josephcsible** [comment]
Try this build and post the crash report you get with it: [lostcities-1.12-2.0.20+g3f9f7b8.zip](https://github.com/McJtyMods/LostCities/files/3353141/lostcities-1.12-2.0.20%2Bg3f9f7b8.zip)

**Comment by Damien-Reave** [comment]
I've found a config that works for me with no crashes.

**Comment by josephcsible** [comment]
That's not helpful to anyone else who's searching for this because they have the same problem. Can you post the results from that build with the broken config, or explain what you changed to make it stop crashing?

**Comment by Damien-Reave** [comment]
https://pastebin.com/gjyAxx6E

This is my new config, a simple mixing together of Tall, Rare and No Damage, which is what I was going for the first time. You can diff the two files if you'd like to know what changed, I just tried a second time with fresh copies of the configs.
