### ISSUE TITLE
Crash with CBP mod

### ISSUE THREAD

**Issue by Bulldog83** [McJty/LostCities#217]
Game crashes when I using Lost Cities chunk provider in Climatic Biome Placement mod.

I created an issue on it's GitHub too. All technical info here:
https://github.com/BlackJar72/ClimaticBiomePlacement/issues/29

**Comment by BlackJar72** [comment]
I may have fixed this on my end -- it just needs testing.  I just had to have it disable my fake biomes when using Lost Cities.

**Comment by Bulldog83** [comment]
Problem solved.
