### ISSUE TITLE
Fully take over Nether/End generation

### ISSUE THREAD

**Issue by Normal69** [McJty/LostCities#220]
Just opened this for a little talk.

You see my players hate the nether, so I am working on a pack, where there is none.
I aim in the modpack for this (did it before in one called "Expertion" via another mod) and one of my MC friends notified me about Lost Cities + Lost Souls.

But as you've mentioned before using -1:wasteland derailed the pack, as "the provider was already registered".

I am aiming for a pack which could be either used in SP or MP, and it is possibble that I can use allow-nether=false in the server.properties (it would be a hardcore upgrade for my "Howdy do we do?" pack).
But that won't make it possibble to play in single, and for me to test it in single beforehand.

So it would be wonderful if you could **totally take over** of existing dimension generation (_I mean not to make cities in the Nether or in the End but generate the whole dimension in your way_) as I would like to surprise my players after they reluctantly step thru a nether gate with a collection of desolate buildings under a clear sky to hunt for loot and clear haunted buildings.

Of course the nether resources already are provided in the overworld generation via another mod.
I have already sought a mod which prevents Nether provider registration to no avail.

Please can you give me some information on this, or (which I cannot hope) make your mod more agressive to unregister that useless Nether (or even End) generator, if your general.cfg says so?

I've tried this with lostcities-1.12-2.0.20.jar

Thank you.

**Comment by Normal69** [comment]
Solved!

Use this mod:
https://www.curseforge.com/minecraft/mc-mods/just-enough-dimensions

In justenoughdimensions.cfg:
`B:enableReplacingRegisteredDimensions=true`

Make a dimensions.json:
```
{
    "dimensions": [
        {
            "dim": -1,
            "override": true,
            "dimensiontype": {
                "id": -1,
                "name": "Elder Ruins",
                "suffix": "_dim-1",
                "keeploaded": false,
                "worldprovider": "WorldProviderSurfaceJED",
                "require_exact_match": true
            },
            "worldinfo_onetime": {
                "generatorName": "lostcities"
            },
            "jed": {
                "CanRespawnHere": true,
                "CanSleepHere": "allow"
            }
        }
    ]
}
```

It will use the lostcities profile you've set up default.
Voila! A brand new nether according to your specifications! :)

Thank you for the mod.

**Comment by DevTimur** [comment]
Thank you, really helped me!
