### ISSUE TITLE
[INCORRECT] Incompatibility with Rough Mobs mod

### ISSUE THREAD

**Issue by shimmer-n-shine** [McJty/LostCities#223]
Once creating a Lost Cities world type, no mobs spawn at all apart from ones spawned from structures(villages) and spawners.
Removing Rough Mobs solves the issue
Generating a new world will not solve the issue, it does not stop unless you reset your mods.

OneDrive link to profile used (import using twitch app)
https://1drv.ms/u/s!AutiVk5ehVSyiZoYLl8MGT4qW2rB6Q?e=7csY4v

**Comment by McJty** [comment]
I don't see how these two mods can have anything to do with each other. Lost Cities is just worldgen and doesn't do anything else. Also did you report to Rough Mobs author as well?

**Comment by josephcsible** [comment]
There's a lot of mods in that pack. See if you can reproduce the problem with just The Lost Cities and Rough Mobs 2, and no other mods.

**Comment by shimmer-n-shine** [comment]
Hi, seems like I narrowed it down to the wrong mod. It was an option from Air Support, nothing to do with Lost Cities. sorry!
