### ISSUE TITLE
crashes while loading

### ISSUE THREAD

**Issue by shrekbruh** [McJty/LostCities#224]
i have touched the config or anything, no other mods
The game crashed whilst ticking entity

Error: java.lang.NoClassDefFoundError: com/pg85/otg/forge/dimensions/WorldProviderOTG

its probably something simple, idk

**Comment by McJty** [comment]
Lost Cities is not compatible with OTG

**Comment by shrekbruh** [comment]
oh i forgot to remove that, thanks man!
