### ISSUE TITLE
Can't create world using the mod

### ISSUE THREAD

**Issue by lunageek520** [McJty/LostCities#228]
when I attempt to make a world using this mod, it crashes.

the main message on the launcher says this
The game crashed whilst ticking entity
Error: java.lang.NoClassDefFoundError: com/pg85/otg/forge/dimensions/WorldProviderOTG

if necessary, I can post the full crash report

**Comment by josephcsible** [comment]
Did you remove OpenTerrainGenerator without also removing OTG-Core.jar? If so, see if that fixes it. If not, then yes, please post the full crash report.

**Comment by lunageek520** [comment]
I actually realized that right before you responded, and it fixed the issue.

Thanks for the help though!
