### ISSUE TITLE
Water Tower generation issue

### ISSUE THREAD

**Issue by tyra314** [McJty/LostCities#24]
When the building with a water tower on top gets wore down, the top part of the tower remains flying in the air.

![2017-07-01_12 06 35](https://user-images.githubusercontent.com/16997177/27761116-4b43e6b0-5e56-11e7-9853-32e862562ce1.png)

1.10.2 with 0.0.13beta

**Comment by McJty** [comment]
I will fix this soon

**Comment by McJty** [comment]
Fixed next release
