### ISSUE TITLE
1.14.4 Forge-28.1.109 Server Crash 

### ISSUE THREAD

**Issue by Lunacrat** [McJty/LostCities#240]
Clientside works without issues. Booting the server crashes. Maybe something is missing? Possibly the profile configurations for the city generation? 

---- Minecraft Crash Report ----
// Don't do that.

Time: 12/28/19 6:25 AM
Description: Exception in server tick loop

net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
	LostCities (lostcities) has failed to load correctly
§7Attempted to load class net/minecraft/client/gui/screen/Screen for invalid dist DEDICATED_SERVER
]
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:201) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:183) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.server.ServerModLoader.begin(ServerModLoader.java:45) ~[?:?] {re:classloading}
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:598) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_221, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 12893143744 bytes (12295 MB) / 13226213376 bytes (12613 MB) up to 15271460864 bytes (14564 MB)
	CPUs: 8
	JVM Flags: 2 total; -Xms8G -Xmx16G
	ModLauncher: 4.1.0+62+5bfa59b
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.1.109.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.109.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.1-milestone.0.1+94458e7-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.1.109.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.109.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.14.4-28.1.109.jar fml TRANSFORMATIONSERVICE 
	FML: 28.1
	Forge: net.minecraftforge:28.1.109
	FML Language Providers: 
		javafml@28.1
		minecraft@1
		kotlinfml@1.3.0
		kotori_scala@2.13.1
	Mod List: 
		enchantedbookredesign-1.1.jar Enchanted Book Redesign {enchantedbookredesign@1.1 CREATE_REGISTRIES}
		warpmod-1.14.4-2.1.8.jar The Warp Mod {warp_mod@2.1.8 CREATE_REGISTRIES}
		prefab-1.4.0.7.jar Prefab {prefab@1.4.0.7 CREATE_REGISTRIES}
		embellishcraft-bop-1.14.4-1.0.0.jar EmbellishCraft BoP Addon {embellishcraft-bop@1.14.4-1.0.0 CREATE_REGISTRIES}
		Uppers-0.1.10.jar Uppers {uppers@0.1.10 CREATE_REGISTRIES}
		IronJetpacks-1.14.4-2.0.3.jar Iron Jetpacks {ironjetpacks@2.0.3 CREATE_REGISTRIES}
		BetterCaves-1.14.4-1.1.1.jar YUNG's Better Caves {bettercaves@1.14.4-1.1.1 CREATE_REGISTRIES}
		fastxppickup-1.1.jar Fast XP Pickup {fastxppickup@1.1 CREATE_REGISTRIES}
		XaerosWorldMap_1.5.2_Forge_1.14.4.jar Xaero's World Map {xaeroworldmap@1.5.2 CREATE_REGISTRIES}
		CookingForBlockheads_1.14.4-7.4.2.jar Cooking for Blockheads {cookingforblockheads@7.4.2 CREATE_REGISTRIES}
		Controlling-5.0.4.jar Controlling {controlling@5.0.4 CREATE_REGISTRIES}
		Placebo-1.14.4-2.3.5.jar Placebo {placebo@2.3.5 CREATE_REGISTRIES}
		Powah-1.14.4-0.1.6.jar Powah {powah@0.1.6 CREATE_REGISTRIES}
		Fence+Jumper-1.14.4-1.0.8.jar FenceJumper {fencejumper@version CREATE_REGISTRIES}
		NomadicTents-1.14.4-10.0.2-beta.jar Nomadic Tents {nomadictents@10.0.2-beta CREATE_REGISTRIES}
		WitherSkeletonTweaks-1.14.4-3.1.0.jar Wither Skeleton Tweaks {wstweaks@3.1.0 CREATE_REGISTRIES}
		MutantBeasts-1.14.4-0.7.0.jar Mutant Beasts {mutantbeasts@1.14.4-0.7.0 CREATE_REGISTRIES}
		u_team_core-1.14.4-2.8.0.140.jar U Team Core {uteamcore@2.8.0.140 CREATE_REGISTRIES}
		Customized-Dungeon-Loot-1.14.x-(v.2.0.0).jar Customized Dungeon Loot {cdl@2.0.0 CREATE_REGISTRIES}
		Apotheosis-1.14.4-2.4.4.jar Apotheosis {apotheosis@2.4.4 CREATE_REGISTRIES}
		ProgressiveBosses-2.1.3.jar Progressive Bosses {progressivebosses@2.1.3 CREATE_REGISTRIES}
		ironshulkerboxes-1.14.4-3.1.12.jar Iron Shulker Boxes {ironshulkerbox@1.14.4-3.1.12 CREATE_REGISTRIES}
		walkthroughberries-1.0a.jar Walk Through Berries {walkthroughberries@1.0a CREATE_REGISTRIES}
		SnowRealMagic-1.14.4-1.4.5.jar Snow! Real Magic! {snowrealmagic@1.4.5 CREATE_REGISTRIES}
		confdespawnt_1.14-1.0.jar Configurable Despawn Timer {confdespawnt@1.0 CREATE_REGISTRIES}
		mysticallib-1.14.4-1.8.0.jar Mystical Lib {mysticallib@1.14.4-1.8.0 CREATE_REGISTRIES}
		AirHop-v1.1.1-1.14.4.jar Air Hop {airhop@1.1.1 CREATE_REGISTRIES}
		corpse-1.14.4-1.0.3.jar Corpse {corpse@1.14.4-1.0.3 CREATE_REGISTRIES}
		anviltweaks-1.4a.jar Anvil Tweaks {anviltweaks@1.4a CREATE_REGISTRIES}
		useful_backpacks-1.14.4-1.7.4.47.jar Useful Backpacks {usefulbackpacks@1.7.4.47 CREATE_REGISTRIES}
		Overloaded+Compressed+Blocks-1.14.4-1.0.8.jar Overloaded Compressed Blocks {overloaded_cb@1.14.4-1.0.8 CREATE_REGISTRIES}
		embellishcraft-1.14.4-1.4.0.jar EmbellishCraft {embellishcraft@1.14.4-1.4.0 CREATE_REGISTRIES}
		BiomesOPlenty-1.14.4-9.0.0.262-universal.jar Biomes O' Plenty {biomesoplenty@1.14.4-9.0.0.259 CREATE_REGISTRIES}
		Lollipop-1.14.4-0.0.19.jar Lollipop {lollipop@0.0.19 CREATE_REGISTRIES}
		AzureRPGItems+1.14.4-1.0.4.jar Azure RPG Items {azurerpgitems@1.0.4 CREATE_REGISTRIES}
		extcaves-1.4.2.jar Extended Caves {extcaves@1.4.2 CREATE_REGISTRIES}
		fairylights-2.1.14-1.14.4.jar Fairy Lights {fairylights@2.1.14 CREATE_REGISTRIES}
		randomenchants-2.2.3.jar Random Enchants {randomenchants@2.2.3 CREATE_REGISTRIES}
		portality-1.14.4-2.0.4-b0b3467.jar Portality {portality@2.0.4 CREATE_REGISTRIES}
		curios-FORGE-1.14.4-1.0.6.jar Curios API {curios@FORGE-1.14.4-1.0.6 CREATE_REGISTRIES}
		AutoRegLib-1.4-35.jar AutoRegLib {arl@1.4-35 CREATE_REGISTRIES}
		extlights-1.6.jar Extended Lights {extlights@1.6 CREATE_REGISTRIES}
		OreExcavation-1.6.145.jar Ore Excavation {oreexcavation@1.6.145 CREATE_REGISTRIES}
		flexible_skills-1.14.4-1.1.8.jar Flexible Skills Mod {flexible_skills@1.1.8 CREATE_REGISTRIES}
		lostcities-1.14-2.0.22-alpha.jar LostCities {lostcities@1.14-2.0.22-alpha ERROR}
		malilib-forge-1.14.4-0.10.0-dev.19+alpha.2.jar MaLiLib {malilib@0.10.0-dev.19 CREATE_REGISTRIES}
		furniture-7.0.0-pre15-1.14.4.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre15 CREATE_REGISTRIES}
		cc-tweaked-1.14.4-1.86.0.jar CC: Tweaked {computercraft@1.86.0 CREATE_REGISTRIES}
		AI-Improvements-1.14.4-0.3.0.jar AI-Improvements {aiimprovements@0.2.2 CREATE_REGISTRIES}
		betterwithminecolonies-1.14.4-1.8.9.jar Better With Minecolonies {betterwithminecolonies@1.14.4-1.8.9 CREATE_REGISTRIES}
		PrettyBeaches_1.14.4-3.0.7.jar Pretty Beaches {prettybeaches@3.0.7 CREATE_REGISTRIES}
		Kiwi-1.14.4-2.4.5.jar Kiwi {kiwi@2.4.5 CREATE_REGISTRIES}
		Ma-Enchants-1.14.4-1.8.0.jar Ma Enchants {ma-enchants@1.14.4-1.8.0 CREATE_REGISTRIES}
		Cucumber-1.14.4-2.0.6.jar Cucumber Library {cucumber@2.0.6 CREATE_REGISTRIES}
		TrashSlot_1.14.4-10.4.8.jar TrashSlot {trashslot@10.4.8 CREATE_REGISTRIES}
		mining-helmet-1.14.4-1.0.1.jar Mining Helmet {mining_helmet@1.0.1 CREATE_REGISTRIES}
		bountifulbaubles-1.14.4-0.0.2.jar Bountiful Baubles {bountifulbaubles@NONE CREATE_REGISTRIES}
		Mine+and+Slash-1.14.4-2.9.3.jar Mine and Slash {mmorpg@2.8.0 CREATE_REGISTRIES}
		jei-1.14.4-6.0.0.26.jar Just Enough Items {jei@6.0.0.26 CREATE_REGISTRIES}
		Druidcraft-1.14-0.2.32.jar Druidcraft {druidcraft@0.2.32 CREATE_REGISTRIES}
		AttributeFix-1.14.4-3.0.3.jar AttributeFix {attributefix@3.0.3 CREATE_REGISTRIES}
		caelus-FORGE-1.14.4-1.0.1.1.jar Caelus API {caelus@FORGE-1.14.4-1.0.1.1 CREATE_REGISTRIES}
		Upgrade-Aquatic-1.14.4-v1.4.4.jar Upgrade Aquatic {upgrade_aquatic@1.4.4 CREATE_REGISTRIES}
		colytra-FORGE-1.14.4-2.0.0.1.jar Colytra {colytra@FORGE-1.14.4-2.0.0.1 CREATE_REGISTRIES}
		extraboats-1.1.2-1.14.4.jar Extra Boats {extraboats@1.1.2 CREATE_REGISTRIES}
		Mine+and+Slash+Auto+Compatibility+1.14.4-1.4.8 (1).jar M&S Auto-Compat 1.14.4 {azurecompat@1.4.8 CREATE_REGISTRIES}
		OresAboveDiamonds-1.14.4+v1.3Beta.jar Ores Above Diamonds {oresabovediamonds@1.3b CREATE_REGISTRIES}
		SereneSeasons-1.14.4-2.0.0.9-universal.jar Serene Seasons {sereneseasons@1.14.4-2.0.0.9 CREATE_REGISTRIES}
		DungeonCrawl-1.14.4-1.6.0.jar Dungeon Crawl {dungeoncrawl@1.6.0 CREATE_REGISTRIES}
		cofh_core-1.14.4-0.2.0b.jar CoFH Core {cofh_core@0.2.0b CREATE_REGISTRIES}
		The-Endergetic-Expansion-1.14.4-v1.0.jar The Endergetic Expansion {endergetic@1.0 CREATE_REGISTRIES}
		snowundertrees-1.14.4-v1.0.jar Snow Under Trees {snowundertrees@v1.0 CREATE_REGISTRIES}
		mysticalworld-1.14.4-1.6.10.jar Mystical World {mysticalworld@1.14.4-1.6.10 CREATE_REGISTRIES}
		forge-1.14.4-28.1.109-universal.jar Forge {forge@28.1.109 CREATE_REGISTRIES}
		QuickLeafDecay-MC1.14.4-1.2.5.jar Quick Leaf Decay {quickleafdecay@1.2.5 CREATE_REGISTRIES}
		Explorercraft-1.14.4-3.2.4.jar Explorercraft {explorercraft@3.2.4 CREATE_REGISTRIES}
		ironchest-1.14.4-9.1.5.jar Iron Chests {ironchest@1.14.3-9.0.3 CREATE_REGISTRIES}
		SimpleDivingGear-3.0.3+mc+1.14.4.jar Simple Diving Gear {simpledivegear@3.0.3 mc 1.14.4 CREATE_REGISTRIES}
		CraftingTweaks_1.14.4-10.1.5.jar Crafting Tweaks {craftingtweaks@10.1.5 CREATE_REGISTRIES}
		forge-1.14.4-28.1.109-server.jar Minecraft {minecraft@1.14.4 CREATE_REGISTRIES}
		extraanvils-2.5a.jar Extra Anvils {extraanvils@2.5a CREATE_REGISTRIES}
		swingthroughgrass-1.14.4-1.3.2.jar SwingThroughGrass {swingthroughgrass@1.14.4-1.3.2 CREATE_REGISTRIES}
		pandoras_creatures-1.14.4-0.12.0.jar Pandoras Creatures {pandoras_creatures@1.14.4-0.12.0 CREATE_REGISTRIES}
		illuminations-0.1.0-1.14.4.jar Illuminations for Forge {illuminations@1.0.0.0 CREATE_REGISTRIES}
		titanium-1.14.4-2.2.5.jar Titanium {titanium@2.2.5 CREATE_REGISTRIES}
		behgameon-1.14.4-1.0.2.jar Behgameon {behgameon@1.0.2 CREATE_REGISTRIES}
		theplopper-1.14.4-v1.3.jar The Plopper {theplopper@v1.3 CREATE_REGISTRIES}
		forbidden_arcanus-1.14.4-1.5-beta-3.jar Forbidden & Arcanus {forbidden_arcanus@1.14.4-1.5-beta-3 CREATE_REGISTRIES}
		archers_paradox-1.14.4-0.1.0a.jar Archer's Paradox {archers_paradox@0.1.0b CREATE_REGISTRIES}
		GeneticAnimals_0_4_11.jar Genetic Animals {eanimod@0.4.11 CREATE_REGISTRIES}
		car-1.14.4-2.0.23.jar Ultimate Car Mod {car@1.14.4-2.0.23 CREATE_REGISTRIES}
		paintings-1.14.4-6.0.1.5.jar Paintings ++ {paintings@1.14.4-6.0.1.5 CREATE_REGISTRIES}
		extragolems-9.0.5.jar Extra Golems {golems@9.0.5 CREATE_REGISTRIES}
		SpartanShields-1.14.4-2.0.0-beta-1.jar Spartan Shields {spartanshields@1.14.4-2.0.0-beta-1 CREATE_REGISTRIES}
		Quark-r2.0-206.jar Quark {quark@r2.0-206 CREATE_REGISTRIES}
		rediscovered-1.14.4-1.1.1.jar Rediscovered {rediscovered@1.1.1 CREATE_REGISTRIES}
		FTBUtilitiesBackups-2.0.0.11.jar FTB Utilities: Backups {ftbbackups@2.0.0.11 CREATE_REGISTRIES}
		recycler-1.0.0.jar Recycler {recycler@1.0.0 CREATE_REGISTRIES}
		FastWorkbench-1.14.4-2.1.4.jar FastWorkbench {fastbench@2.1.4 CREATE_REGISTRIES}
		performant-1.14.4-1.4.jar Performant {performant@1.14.4-1.4 CREATE_REGISTRIES}
		backpacked-1.2.0-1.14.4.jar Backpacked {backpacked@1.2.0 CREATE_REGISTRIES}
		HardcoreRevival_1.14.4-3.0.11.jar Hardcore Revival {hardcorerevival@3.0.11 CREATE_REGISTRIES}
		tubesreloaded-1.14.4-1.1.0d.jar Tubes Reloaded {tubesreloaded@1.14.4-1.1.0d CREATE_REGISTRIES}
		structurize-0.10.201-ALPHA.jar Structurize {structurize@0.10.201-ALPHA CREATE_REGISTRIES}
		quickstack-2.0.2.jar DropOff {dropoff@2.0.2 CREATE_REGISTRIES}
		minecolonies-0.10.593-RELEASE-universal.jar Minecolonies {minecolonies@0.10.593-RELEASE CREATE_REGISTRIES}
		FastFurnace-1.14.4-2.2.4.jar FastFurnace {fastfurnace@2.2.4 CREATE_REGISTRIES}
		easyelytrato_1.14-1.1.jar Easy Elytra Takeoff {easyelytrato@1.1 CREATE_REGISTRIES}
		Aquaculture-1.14.4-2.0.3.jar Aquaculture 2 {aquaculture@1.14.4-2.0.3 CREATE_REGISTRIES}
		CloudBoots-1.14.4-2.0.0.jar Cloud Boots {cloudboots@2.0.0 CREATE_REGISTRIES}
		XL-Food-Mod-1.14.4-2.1.1.jar XL Food Mod {xlfoodmod@2.1.1 CREATE_REGISTRIES}
		CraftingCraft_1.14.4-7.1.7.jar CraftingCraft {craftingcraft@7.1.7 CREATE_REGISTRIES}
		farlanders-1.14.4-1.1.0.jar The Farlanders {farlanders@1.1.0 CREATE_REGISTRIES}
	Kiwi Modules: 
		
	Data Packs: 
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)

**Comment by sabinoplane** [comment]
Same error here, here's my crash report:
---- Minecraft Crash Report ----
// Everything's going to plan. No, really, that was supposed to happen.

Time: 29/12/19 1:58
Description: Exception in server tick loop

net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
	LostCities (lostcities) has failed to load correctly
§7Attempted to load class net/minecraft/client/gui/widget/Widget for invalid dist DEDICATED_SERVER
]
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:199) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:181) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.server.ServerModLoader.begin(ServerModLoader.java:45) ~[?:?] {re:classloading}
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:598) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_231] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_231, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3338738328 bytes (3184 MB) / 4279238656 bytes (4081 MB) up to 7635730432 bytes (7282 MB)
	CPUs: 4
	JVM Flags: 2 total; -Xms2G -Xmx8G
	ModLauncher: 4.1.0+62+5bfa59b
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.1.61.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.61.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.1.61.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.61.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.14.4-28.1.61.jar fml TRANSFORMATIONSERVICE 
	FML: 28.1
	Forge: net.minecraftforge:28.1.61
	FML Language Providers: 
		javafml@28.1
		minecraft@1
	Mod List: 
		astikorcarts-1.0.0.1.jar AstikorCarts {astikorcarts@NONE CREATE_REGISTRIES}
		AutoRegLib-1.4-35.jar AutoRegLib {arl@1.4-35 CREATE_REGISTRIES}
		backpacked-1.2.0-mc1.14.4.jar Backpacked {backpacked@1.2.0 CREATE_REGISTRIES}
		BiomesOPlenty-1.14.4-9.0.0.261-universal.jar Biomes O' Plenty {biomesoplenty@1.14.4-9.0.0.259 CREATE_REGISTRIES}
		CarryOn+MC1.14.4+v1.12.4.jar Carry On {carryon@1.12.4 CREATE_REGISTRIES}
		comforts-FORGE-1.14.4-2.0-beta4.jar Comforts {comforts@FORGE-1.14.4-2.0-beta4 CREATE_REGISTRIES}
		Craftable+Saddles+[1.14]-1.3.jar Craftable Saddles {craftable_saddles@1.3 CREATE_REGISTRIES}
		extcaves-1.4.2.jar Extended Caves {extcaves@1.4.2 CREATE_REGISTRIES}
		extraboats-1.1.2-1.14.4.jar Extra Boats {extraboats@1.1.2 CREATE_REGISTRIES}
		furniture-7.0.0-pre15-1.14.4.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre15 CREATE_REGISTRIES}
		lostcities-1.14-2.0.22-alpha.jar LostCities {lostcities@1.14-2.0.22-alpha ERROR}
		mining-helmet-1.14.4-1.0.1.jar Mining Helmet {mining_helmet@1.0.1 CREATE_REGISTRIES}
		NoIncreasingRepairCost-1.0.jar No Increasing Repair Cost {noincreasingrepaircost@NONE CREATE_REGISTRIES}
		obfuscate-0.3.3-1.14.4.jar Obfuscate {obfuscate@0.3.3 CREATE_REGISTRIES}
		paintings-1.14.4-6.0.1.5.jar Paintings ++ {paintings@1.14.4-6.0.1.5 CREATE_REGISTRIES}
		petyourwolf-1.2.1-mc1.14.4.jar Pet Your Wolf {petyourwolf@1.2.1 CREATE_REGISTRIES}
		placeableitems-4.0.0.jar Placeable Items {placeableitems@4.0 CREATE_REGISTRIES}
		ruins-1.14.4.4.jar Ruins {ruins@1.14.3.3 CREATE_REGISTRIES}
		SereneSeasons-1.14.4-2.0.0.14-universal.jar Serene Seasons {sereneseasons@1.14.4-2.0.0.14 CREATE_REGISTRIES}
		structurize-0.10.201-ALPHA.jar Structurize {structurize@0.10.201-ALPHA CREATE_REGISTRIES}
		Upgrade-Aquatic-1.14.4-v1.4.4.jar Upgrade Aquatic {upgrade_aquatic@1.4.4 CREATE_REGISTRIES}
		VanillaTweaks-1.14.4.1.5.11.jar VanillaTweaks {vanillatweaks@1.14.4.1.5.11 CREATE_REGISTRIES}
		XL-Food-Mod-1.14.4-2.1.1.jar XL Food Mod {xlfoodmod@2.1.1 CREATE_REGISTRIES}
		forge-1.14.4-28.1.61-universal.jar Forge {forge@28.1.61 CREATE_REGISTRIES}
		Aquaculture-1.14.4-2.0.3.jar Aquaculture 2 {aquaculture@1.14.4-2.0.3 CREATE_REGISTRIES}
		Quark-r2.0-206.jar Quark {quark@r2.0-206 CREATE_REGISTRIES}
		forge-1.14.4-28.1.61-server.jar Minecraft {minecraft@1.14.4 CREATE_REGISTRIES}
	Data Packs: 
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)

**Comment by McJty** [comment]
I just published an update. Can you let me know if it works?

**Comment by Lunacrat** [comment]
That seems to have resolved the crash. Much appreciated!
