### ISSUE TITLE
Crash when I apply stone slab on top of other stone slabs in building

### ISSUE THREAD

**Issue by FluffiKiki** [McJty/LostCities#241]
Crash does not happen (to what I know) on stone slabs on roads. Just inside buildings. In order to stack another stone slab onto an existing one, I have to destroy it then place it again. Here's the crash log (Note: Kleeslabs is on, but was applied after the first few crashes): 

---- Minecraft Crash Report ----

WARNING: coremods are present:
  ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.6.jar)
  AppleCore (AppleCore-mc1.12.2-2.2.2.jar)
  offlineskins (OfflineSkins-1.12.2-v6-core.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.16-universal.jar)
  ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
  ComfortsCoreLoadingPlugin (comforts-1.12.2-1.1.3.jar)
  LoadingPlugin (Quark-r1.5-144.jar)
  wings (wings-1.1.4-1.12.2.jar)
  CharmLoadingPlugin (Charm-1.12.2-1.3.6.jar)
  llibrary (llibrary-core-1.0.8-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 1/2/20 5:57 PM
Description: Unexpected error

java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=half, clazz=class net.minecraft.block.BlockSlab$EnumBlockHalf, values=[top, bottom]} as it does not exist in BlockStateContainer{block=minecraft:double_stone_slab, properties=[seamless, variant]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:201)
	at cjminecraft.doubleslabs.Events.onItemUse(Events.java:89)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_83_Events_onItemUse_RightClickBlock.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onRightClickBlock(ForgeHooks.java:1124)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:398)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1578)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2253)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2019)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1807)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1097)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:201)
	at cjminecraft.doubleslabs.Events.onItemUse(Events.java:89)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_83_Events_onItemUse_RightClickBlock.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onRightClickBlock(ForgeHooks.java:1124)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:398)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1578)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2253)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2019)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['FluffiKiki'/490, l='MpServer', x=-24.38, y=96.00, z=344.61]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 09 - lostcities_bop, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (92,64,241), Chunk: (at 12,4,1 in 5,15; contains blocks 80,0,240 to 95,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 846765 game time, 1398773 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 89 total; [EntitySheep['Sheep'/132, l='MpServer', x=-61.45, y=65.00, z=268.55], EntityItem['item.item.itemBatWing'/140, l='MpServer', x=-47.94, y=38.00, z=324.88], EntityChicken['Chicken'/141, l='MpServer', x=-45.86, y=80.00, z=377.75], EntityItem['item.item.egg'/7055, l='MpServer', x=39.82, y=80.00, z=384.25], EntityBat['Bat'/14611, l='MpServer', x=7.77, y=60.52, z=354.74], EntityBat['Bat'/14612, l='MpServer', x=14.53, y=60.27, z=361.75], EntitySquid['Squid'/152, l='MpServer', x=-27.17, y=62.19, z=307.86], EntitySquid['Squid'/153, l='MpServer', x=-17.40, y=62.20, z=309.04], EntityItem['item.item.itemBatWing'/154, l='MpServer', x=-17.85, y=54.00, z=310.99], EntitySquid['Squid'/155, l='MpServer', x=-22.67, y=62.20, z=308.17], EntitySquid['Squid'/156, l='MpServer', x=-28.94, y=60.21, z=306.15], EntityChicken['Chicken'/157, l='MpServer', x=-11.77, y=80.00, z=379.57], EntityBat['Bat'/14877, l='MpServer', x=-101.52, y=33.17, z=348.54], EntityItem['item.item.itemBatWing'/170, l='MpServer', x=-6.01, y=32.00, z=287.30], EntityItem['item.item.itemBatWing'/172, l='MpServer', x=-8.06, y=29.00, z=303.88], EntityItem['item.item.itemBatWing'/173, l='MpServer', x=-4.36, y=30.00, z=297.89], EntitySquid['Squid'/174, l='MpServer', x=-6.28, y=35.55, z=314.66], EntityPlayerSP['FluffiKiki'/490, l='MpServer', x=-24.38, y=96.00, z=344.61], EntityItem['item.item.itemBatWing'/177, l='MpServer', x=-5.25, y=40.00, z=329.93], EntityBat['Bat'/178, l='MpServer', x=-4.41, y=35.73, z=295.60], EntityLift['Elevator'/179, l='MpServer', x=-9.50, y=95.00, z=341.50], EntityChicken['Chicken'/180, l='MpServer', x=-9.88, y=127.00, z=343.79], EntityChicken['Chicken'/181, l='MpServer', x=-8.68, y=127.00, z=340.12], EntityChicken['Chicken'/182, l='MpServer', x=-9.77, y=127.00, z=341.73], EntityEasterChicken['Easter Chicken'/183, l='MpServer', x=-7.88, y=127.00, z=342.21], EntityEasterChicken['Easter Chicken'/184, l='MpServer', x=-14.49, y=127.00, z=350.12], EntityCow['Cow'/185, l='MpServer', x=-9.15, y=127.00, z=347.53], EntityItem['item.item.egg'/187, l='MpServer', x=-14.15, y=127.00, z=350.01], EntityItem['item.item.chocolate_egg:milk'/188, l='MpServer', x=-14.60, y=127.00, z=348.66], EntityItem['item.item.egg'/189, l='MpServer', x=-15.65, y=80.00, z=378.36], EntityBat['Bat'/22845, l='MpServer', x=-62.87, y=57.20, z=294.39], EntityBat['Bat'/22846, l='MpServer', x=-74.09, y=52.03, z=296.75], EntityBat['Bat'/22848, l='MpServer', x=-55.31, y=59.00, z=309.37], EntityBat['Bat'/22850, l='MpServer', x=-94.83, y=31.07, z=368.72], EntityGlassItemFrame['Glass Item Frame'/200, l='MpServer', x=7.03, y=134.50, z=294.50], EntityArmorStand['Armor Stand'/201, l='MpServer', x=5.50, y=132.00, z=298.50], EntityGlassItemFrame['Glass Item Frame'/202, l='MpServer', x=6.50, y=134.50, z=293.97], EntityItem['item.item.itemBatWing'/203, l='MpServer', x=11.61, y=60.00, z=306.62], EntityChicken['Chicken'/75, l='MpServer', x=-101.85, y=79.00, z=293.41], EntityPig['Pig'/205, l='MpServer', x=1.31, y=79.00, z=389.43], EntityDuck['Duck'/77, l='MpServer', x=-94.47, y=80.00, z=300.89], EntityChicken['Chicken'/206, l='MpServer', x=19.18, y=79.00, z=406.59], EntityDuck['Duck'/79, l='MpServer', x=-102.05, y=80.00, z=341.28], EntityPig['Pig'/208, l='MpServer', x=28.49, y=90.00, z=302.70], EntityChicken['Chicken'/209, l='MpServer', x=29.50, y=91.00, z=351.11], EntityChicken['Chicken'/210, l='MpServer', x=18.55, y=88.00, z=366.87], EntityChicken['Chicken'/211, l='MpServer', x=24.48, y=86.00, z=371.87], EntityItem['item.item.egg'/3667, l='MpServer', x=-8.84, y=127.00, z=341.13], EntityChicken['Chicken'/212, l='MpServer', x=24.12, y=86.00, z=375.42], EntityItem['item.item.egg'/213, l='MpServer', x=18.78, y=86.00, z=370.96], EntityChicken['Chicken'/214, l='MpServer', x=24.87, y=86.00, z=372.51], EntityChicken['Chicken'/215, l='MpServer', x=24.23, y=85.00, z=382.59], EntityItem['item.item.egg'/12503, l='MpServer', x=-45.14, y=80.00, z=377.62], EntityItem['item.item.egg'/216, l='MpServer', x=25.10, y=86.00, z=372.31], EntityChicken['Chicken'/217, l='MpServer', x=28.38, y=82.00, z=390.45], EntityItem['item.item.egg'/218, l='MpServer', x=23.60, y=80.00, z=394.61], EntitySquid['Squid'/23009, l='MpServer', x=-21.89, y=60.12, z=309.04], EntityPig['Pig'/226, l='MpServer', x=42.82, y=91.00, z=307.82], EntityDuck['Duck'/98, l='MpServer', x=-92.37, y=80.00, z=331.63], EntitySquid['Squid'/23010, l='MpServer', x=-24.22, y=60.64, z=309.04], EntitySquid['Squid'/23011, l='MpServer', x=-17.40, y=61.49, z=307.57], EntityChicken['Chicken'/228, l='MpServer', x=40.12, y=80.00, z=384.22], EntityPig['Pig'/101, l='MpServer', x=-91.79, y=79.00, z=356.50], EntityChicken['Chicken'/229, l='MpServer', x=26.87, y=79.00, z=404.50], EntityItem['item.item.egg'/230, l='MpServer', x=35.92, y=79.00, z=406.77], EntityItem['item.item.itemBatWing'/103, l='MpServer', x=-81.99, y=46.00, z=378.16], EntityChicken['Chicken'/231, l='MpServer', x=34.51, y=80.00, z=408.13], EntityChicken['Chicken'/105, l='MpServer', x=-80.67, y=79.00, z=385.80], EntityItem['item.item.itemBatWing'/110, l='MpServer', x=-69.25, y=41.00, z=302.49], EntityBat['Bat'/111, l='MpServer', x=-78.76, y=50.10, z=301.96], EntityItem['item.item.itemBatWing'/112, l='MpServer', x=-64.32, y=41.00, z=306.25], EntityCoconut['entity.coconut.name'/113, l='MpServer', x=-74.60, y=102.63, z=310.50], EntityChicken['Chicken'/241, l='MpServer', x=51.16, y=80.00, z=401.44], EntityCoconut['entity.coconut.name'/114, l='MpServer', x=-73.60, y=101.63, z=311.30], EntityCoconut['entity.coconut.name'/115, l='MpServer', x=-75.60, y=101.63, z=311.30], EntityCoconut['entity.coconut.name'/116, l='MpServer', x=-75.40, y=101.63, z=309.40], EntityCoconut['entity.coconut.name'/117, l='MpServer', x=-73.60, y=101.63, z=309.60], EntityBat['Bat'/14453, l='MpServer', x=-6.56, y=24.10, z=268.25], EntityItem['item.item.itemBatWing'/118, l='MpServer', x=-73.21, y=50.00, z=325.13], EntityPig['Pig'/119, l='MpServer', x=-72.25, y=89.00, z=336.49], EntityChicken['Chicken'/120, l='MpServer', x=-80.50, y=88.00, z=330.78], EntityItem['item.item.egg'/3192, l='MpServer', x=-81.62, y=79.00, z=363.70], EntityChicken['Chicken'/121, l='MpServer', x=-77.51, y=80.00, z=343.77], EntityDuck['Duck'/122, l='MpServer', x=-76.94, y=79.00, z=361.88], EntityChicken['Chicken'/123, l='MpServer', x=-81.09, y=79.00, z=363.08], EntityItem['item.item.duckcraft.duckeggitem'/124, l='MpServer', x=-76.64, y=79.00, z=361.91], EntityChicken['Chicken'/125, l='MpServer', x=-78.20, y=79.00, z=383.43], EntityItem['item.item.egg'/126, l='MpServer', x=-73.13, y=80.00, z=371.52], EntityChicken['Chicken'/127, l='MpServer', x=-71.87, y=79.00, z=416.53]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2740)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:426)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_231, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 604255704 bytes (576 MB) / 1876951040 bytes (1790 MB) up to 2386558976 bytes (2276 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx2560m
	IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 104
	FML: MCP 9.42 Powered by Forge 14.23.5.2772 79 mods loaded, 78 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                   | Version         | Source                                        | Signature                                |
	|:--------- |:-------------------- |:--------------- |:--------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft            | 1.12.2          | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | mcp                  | 9.42            | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | FML                  | 8.0.99.99       | forge-1.12.2-14.23.5.2772-universal.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                | 14.23.5.2772    | forge-1.12.2-14.23.5.2772-universal.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | obfuscate            | 0.2.6           | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | craftable_cds        | RELEASE         | [1.12.2]+Craftable+CDs+1.0.jar                | None                                     |
	| UCHIJAAAA | uncraftingtable      | 1.8-beta6       | [1.12]UncraftingTable-1.8-beta6.jar           | None                                     |
	| UCHIJAAAA | aether_legacy        | 1.4.4           | aether_legacy-1.12.2-v1.4.4.jar               | None                                     |
	| UCHIJAAAA | aeadditions          | 1.0             | aetheradditions-1.12.2-1.1.jar                | None                                     |
	| UCHIJAAAA | applecore            | 2.2.2           | AppleCore-mc1.12.2-2.2.2.jar                  | None                                     |
	| UCHIJAAAA | jei                  | 4.15.0.268      | jei_1.12.2-4.15.0.268.jar                     | None                                     |
	| UCHIJAAAA | quark                | r1.5-144        | Quark-r1.5-144.jar                            | None                                     |
	| UCHIJAAAA | autoreglib           | 1.3-24          | AutoRegLib-1.3-24.jar                         | None                                     |
	| UCHIJAAAA | baubles              | 1.5.2           | Baubles-1.12-1.5.2.jar                        | None                                     |
	| UCHIJAAAA | bibliocraft          | 2.4.3           | BiblioCraft[v2.4.3][MC1.12.0].jar             | None                                     |
	| UCHIJAAAA | biomesoplenty        | 7.0.1.2350      | BiomesOPlenty-1.12.2-7.0.1.2350-universal.jar | None                                     |
	| UCHIJAAAA | birdsfoods           | 3.1 - [1.12]    | birdsfoods-1.12 - 3.1.jar                     | None                                     |
	| UCHIJAAAA | camera               | 1.0.8           | camera-1.0.8.jar                              | None                                     |
	| UCHIJAAAA | redstoneflux         | 2.0.1           | RedstoneFlux-1.12-2.0.1.2-universal.jar       | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UCHIJAAAA | car                  | 1.2.11          | car-1.2.11.jar                                | None                                     |
	| UCHIJAAAA | carryon              | 1.12.2          | CarryOn+MC1.12.2+v1.12.2.jar                  | 55e88f24d04398481ae6f1ce76f65fd776f14227 |
	| UCHIJAAAA | cfm                  | 6.3.0           | CFM 6.3.0 - MC 1.12.2 - Sliding Doors Fix.jar | None                                     |
	| UCHIJAAAA | charm                | 1.12.2-1.3.6    | Charm-1.12.2-1.3.6.jar                        | None                                     |
	| UCHIJAAAA | christmasfestivity   | 1.2.2.1         | christmasfestivity-1.2.2.1.jar                | None                                     |
	| UCHIJAAAA | coffeespawner        | 1.0.2           | CoffeeSpawner-1.12-1.0.2.jar                  | None                                     |
	| UCHIJAAAA | toughasnails         | 3.1.0.115       | ToughAsNails-1.12.2-3.1.0.115-universal.jar   | None                                     |
	| UCHIJAAAA | comforts             | 1.1.3           | comforts-1.12.2-1.1.3.jar                     | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| UCHIJAAAA | cookingforblockheads | 6.4.71          | CookingForBlockheads_1.12.2-6.4.71.jar        | None                                     |
	| UCHIJAAAA | culinaryconstruct    | 1.3.3.1         | culinaryconstruct-1.3.3.1.jar                 | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
	| UCHIJAAAA | modcurrency          | 1.12-1.3.5      | Currency-1.12.0-1.3.5.jar                     | None                                     |
	| UCHIJAAAA | dazzle               | 2.0.0           | dazzle-2.0.0.jar                              | None                                     |
	| UCHIJAAAA | doubleslabs          | 0.1.0           | DoubleSlabs-1.12-0.1.0.jar                    | None                                     |
	| UCHIJAAAA | harvestcraft         | 1.12.2zb        | Pam's+HarvestCraft+1.12.2zf.jar               | None                                     |
	| UCHIJAAAA | duckcraft            | 3.0.8           | Duckcraft-1.12.2-3.0.8.jar                    | None                                     |
	| UCHIJAAAA | elevatorid           | 1.3.5           | ElevatorMod-1.12.2-1.3.5.jar                  | None                                     |
	| UCHIJAAAA | entityspring         | 2.0.0           | entityspring-2.0.0.jar                        | None                                     |
	| UCHIJAAAA | extraalchemy         | 0.3.8.3-release | extraalchemy-0.3.8.3-release.jar              | None                                     |
	| UCHIJAAAA | fairylights          | 2.1.9           | fairylights-2.1.9-1.12.2.jar                  | None                                     |
	| UCHIJAAAA | familiarfauna        | 1.0.10          | FamiliarFauna-1.12.2-1.0.10.jar               | None                                     |
	| UCHIJAAAA | ferdinandsflowers    | 1.10.1b         | Ferdinand's+Flowers-1.10.1b-1.12.jar          | None                                     |
	| UCHIJAAAA | foodexpansion        | 1.3             | FoodExpansion1.3.2-1.12.jar                   | None                                     |
	| UCHIJAAAA | forgivingvoid        | 1.0.17          | ForgivingVoid_1.12.2-1.0.17.jar               | None                                     |
	| UCHIJAAAA | hungerinpeace        | 1.0.0           | HungerInPeace-mc1.12-1.0.0.jar                | None                                     |
	| UCHIJAAAA | improvedbackpacks    | 1.12.2-1.4.0.0  | ImprovedBackpacks-1.12.2-1.4.0.0.jar          | None                                     |
	| UCHIJAAAA | kleeslabs            | 5.4.12          | KleeSlabs_1.12.2-5.4.12.jar                   | None                                     |
	| UCHIJAAAA | lostcities           | 2.0.18          | lostcities-1.12-2.0.18.jar                    | None                                     |
	| UCHIJAAAA | mcpaint              | 1.2.4           | mcpaint-1.2.4.jar                             | 7904c4e13947c8a616c5f39b26bdeba796500722 |
	| UCHIJAAAA | moredyeablearmors    | 1.12.2-1.1.0    | moredyeablearmors-1.12.2-1.1.0.jar            | None                                     |
	| UCHIJAAAA | noel                 | 1.0.2           | noel-1.12.2-1.0.3.jar                         | None                                     |
	| UCHIJAAAA | yurtmod              | 9.5.0           | NomadicTents-1.12.2-9.5.0.jar                 | None                                     |
	| UCHIJAAAA | recipehandler        | 0.13            | NoMoreRecipeConflict-0.13(1.12.2).jar         | None                                     |
	| UCHIJAAAA | offlineskins         | 1.12.2-v6       | OfflineSkins-1.12.2-v6.jar                    | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| UCHIJAAAA | persistentcake       | 2.0.0           | persistentcake-1.12-2.0.0.jar                 | None                                     |
	| UCHIJAAAA | pizzacraft           | 2.0.16.16       | PizzaCraft-1.12.2-2.0.16.16.jar               | None                                     |
	| UCHIJAAAA | potioncrackers       | 1.0             | PotionCrackers+v1.1.1.jar                     | None                                     |
	| UCHIJAAAA | rockcandy            | 1.12.2-2.03     | rockcandy-1.12-2.1.0.jar                      | None                                     |
	| UCHIJAAAA | saltmod              | 1.12_e          | SaltyMod_1.12.1_e.jar                         | None                                     |
	| UCHIJAAAA | sereneseasons        | 1.2.16          | SereneSeasons-1.12.2-1.2.16-universal.jar     | None                                     |
	| UCHIJAAAA | shetiphiancore       | 3.5.6           | shetiphiancore-1.12.0-3.5.6.jar               | None                                     |
	| UCHIJAAAA | simplecorn           | 2.3.2           | SimpleCorn1.12-2.3.2.jar                      | None                                     |
	| UCHIJAAAA | skyes_bakery         | 1.0.0           | Skye's+Bakery+2.0.1_hotfix+for+MC1.12.2.jar   | None                                     |
	| UCHIJAAAA | somelikeitdry        | 1.2.2           | somelikeitdry-1.2.2.jar                       | None                                     |
	| UCHIJAAAA | spikedfoods          | 1.0             | SpikedFoods-1.0.jar                           | None                                     |
	| UCHIJAAAA | terraqueous          | 1.4.12          | terraqueous-1.12.0-1.4.12.jar                 | None                                     |
	| UCHIJAAAA | thutcore             | 5.19.9          | thutcore-1.12.2-5.19.9.jar                    | None                                     |
	| UCHIJAAAA | thutcore_compat      | 1.0             | thutcore-1.12.2-5.19.9.jar                    | None                                     |
	| UCHIJAAAA | thuttech             | 6.1.5           | thuttech-1.12.2-6.1.5.jar                     | None                                     |
	| UCHIJAAAA | vehicle              | 0.41.0          | vehicle-mod-0.41.0-1.12.2.jar                 | None                                     |
	| UCHIJAAAA | llibrary             | 1.7.15          | llibrary-1.7.15-1.12.2.jar                    | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| UCHIJAAAA | wings                | 1.1.4           | wings-1.1.4-1.12.2.jar                        | None                                     |
	| UCHIJAAAA | bauble_wings         | 1.0.0           | wings-1.1.4-1.12.2.jar                        | None                                     |
	| UCHIJAAAA | worldedit            | 6.1.8           | worldedit-forge-mc1.12-6.1.8-dist.jar         | None                                     |
	| UCHIJAAAA | xaerominimap         | 1.17.8          | Xaeros_Minimap_1.17.8_Forge_1.12.jar          | None                                     |
	| UCHIJAAAA | xaeroworldmap        | 1.4.8           | XaerosWorldMap_1.4.8_Forge_1.12.jar           | None                                     |
	| UCHIJAAAA | xlfoodmod            | 1.12.2-1.9.1    | XL-Food-Mod-1.12.2-1.9.1.jar                  | None                                     |
	| UCHIJAAAA | candymod             | 1.1.1           | candyworld-1.1.1.jar                          | None                                     |
	| UCHIJAAAA | lemonlib             | 1.3.0           | lemonlib-1.12.2-1.3.0.jar                     | None                                     |
	| UCHIJAAAA | snowrealmagic        | 0.3.3           | SnowRealMagic-0.3.3.jar                       | None                                     |
	| UD        | mobends_wings        | 1.0.0           | wings-1.1.4-1.12.2.jar                        | None                                     |

	Loaded coremods (and transformers): 
ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.6.jar)
  shetiphian.asm.ClassTransformer
AppleCore (AppleCore-mc1.12.2-2.2.2.jar)
  squeek.applecore.asm.TransformerModuleHandler
offlineskins (OfflineSkins-1.12.2-v6-core.jar)
  lain.mods.skins.init.forge.asm.ASMTransformer
SSLoadingPlugin (SereneSeasons-1.12.2-1.2.16-universal.jar)
  sereneseasons.asm.transformer.EntityRendererTransformer
  sereneseasons.asm.transformer.WorldTransformer
ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
ComfortsCoreLoadingPlugin (comforts-1.12.2-1.1.3.jar)
  c4.comforts.asm.SleepTransformer
LoadingPlugin (Quark-r1.5-144.jar)
  vazkii.quark.base.asm.ClassTransformer
wings (wings-1.1.4-1.12.2.jar)
  me.paulf.wings.server.asm.WingsRuntimePatcher
  me.paulf.wings.server.asm.mobends.WingsMoBendsRuntimePatcher
CharmLoadingPlugin (Charm-1.12.2-1.3.6.jar)
  svenhjol.charm.base.CharmClassTransformer
llibrary (llibrary-core-1.0.8-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
	GL info: ' Vendor: 'Intel' Version: '4.5.0 - Build 24.20.100.6025' Renderer: 'Intel(R) HD Graphics 620'
	Launched Version: MultiMC5
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 620 GL version 4.5.0 - Build 24.20.100.6025, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz

**Comment by josephcsible** [comment]
That looks like it's caused by DoubleSlabs. If you disagree, then uninstall DoubleSlabs, get it to crash again, and post the new crash report.

**Comment by FluffiKiki** [comment]
Oh my goodness, you just pointed me to a mod I didn't even know I had on this instance. Learned my lesson! Thanks so much! I'll go ahead and close this.
