### ISSUE TITLE
[Suggestion] Expose vanilla Customized worldtype settings in Lost Cities worldgen

### ISSUE THREAD

**Issue by esotericist** [McJty/LostCities#25]
The vanilla Customized worldtype is exceptionally flexible, and allows for quite a lot of fairly impressive things to be done with it.

As an example, Quark's 'Realistic' worldtype is actually simply a wrapper for a preset made by [soniop](https://www.reddit.com/u/soniop) on reddit, and described [here](https://www.reddit.com/r/Minecraft/comments/4nfw3t/more_realistic_generation_preset_in_comment/d4eq417/?context=1).

Having the ability to at least use the preset json text either in the world creation screen in-game or in profile definitions in the lost cities config would enable quite a lot of interesting world generation patterns.

**Comment by McJty** [comment]
At least the ability to use preset texts will be available next release. Not sure if I can integrate the gui into mine easily. Will have to try that out

**Comment by esotericist** [comment]
That's good enough for me, honestly. Easy enough to use the gui in the vanilla menu to do designing if you have to.

**Comment by McJty** [comment]
Implemented next release
