### ISSUE TITLE
Variable Cavern dimension height

### ISSUE THREAD

**Issue by PCSpinner** [McJty/LostCities#252]
lostcities-1.12-2.0.22

Maybe I'm missing something, but is there a way to adjust the world height of the "cavern" landscapeType? If not, is that something that can be implemented?

**Comment by McJty** [comment]
No, that's unfortunatelly hardcoded to 128. Note that there is a reason it is set to that (and also a reason that the nether is limited to 128) and that's performance. Same reason why amplified terraingen isn't very fast

**Comment by PCSpinner** [comment]
I was afraid you were going to say that.
