### ISSUE TITLE
RegenChest

### ISSUE THREAD

**Issue by listofer** [McJty/LostCities#254]
I propose to introduce a mod to restore chests in buildings with a new loot in the chest even if the old chest is not oblutali
Version 1.12.2
Because players can clean all the chests and for new players there will be no resources in them
So it would not be bad if the loot regenerated in them again if the chest is not broken
If it is broken then make it appear again with a new loot
With the ability to disable the recovery of the chest to avoid the situation of the appearance of the chest in the air

**Comment by McJty** [comment]
Well the same is true for normal vanilla dungeon chests isn't it? So if a mod like that would be made it is not related to Lost Cities I think. But personally I think this is a feature that could be abused. i.e. what prevents the same player to loot the chest again?

**Comment by listofer** [comment]
This is necessary for new players on the server to have loot in chests in buildings

**Comment by listofer** [comment]
Abuse and he will not be able to clean all the chests in the world because the world is big

**Comment by McJty** [comment]
yes but this is not related to Lost Cities at all and I don't see a way to do this in a non cheating way

**Comment by listofer** [comment]
And he may get tired of this activity, because the base will also need to be built and developed.
Then he will not be able to carry a lot of things from the chests, because I will add weight to them using the player weight mod

**Comment by McJty** [comment]
This is best handled in another mod. So going to close this as it is not really relevant to Lost Cities
