### ISSUE TITLE
Server Properties rolling back to default 1.15.2 Forge 31.1.1

### ISSUE THREAD

**Issue by assasing123** [McJty/LostCities#255]
Each time i try to generate a world with the attached properties file, it rollsback the lines for level type and generator settings.
ottocities is a profile i created that exists in the proper folder.
i am using forge to load my server (all the other mods i have work)
BiomesoPlenty is installed.

[server.properties.txt](https://github.com/McJtyMods/LostCities/files/4174618/server.properties.txt)

**Comment by McJty** [comment]
Check the explanation on the CurseForge page for Lost Cities. The way to configure Lost Cities on 1.14 and 1.15 is not the same as on 1.12
