### ISSUE TITLE
Dimension Not Generating

### ISSUE THREAD

**Issue by varnithian97** [McJty/LostCities#261]
I currently run a RLcraft 1.12.2 V2.8.1 and since its creation this plugin has not worked, ive tried switching the profiles, as well altering the config and other dimension values. However no matter what I do there is no dimension creation. I cannot teleport to the DIMID nor can I create a portal through the plugin(bed+emeraldblock) any ideas? is there some setup im not aware of? I tried reading other issues and looking at wiki but no data brought anything to light.

**Comment by McJty** [comment]
It's bed + diamond blocks and skulls around it

**Comment by varnithian97** [comment]
In the config its preset for emerald, I did change back to diamond block to make sure it wasnt an issue with it. I also placed skulls to no avail. I can post screenshot

**Comment by varnithian97** [comment]
![lost cities](https://user-images.githubusercontent.com/59478226/74872820-ffe33180-532b-11ea-82e2-d8c29b6c1836.png)

**Comment by de1h** [comment]
I also have this error only i'm using 1.15.2 ver 3.0.0

**Comment by McJty** [comment]
This features isn't implemented yet in 1.14+
