### ISSUE TITLE
Doesn't work Server Sided w/ Large Biomes 1.15.2

### ISSUE THREAD

**Issue by RussianJesuz** [McJty/LostCities#266]
This may be already known but if its not heres the issue
I've been attempting to get the server to have large biomes with lostcities but it seems like its one or the other. 
since both require you to use "level-type=" to generate.

**Comment by McJty** [comment]
On 1.15.2 Lost Cities no longer requires level-type. Check the instructions on the curseforge page for Lost Cities on how to set up a server on 1.15.2. It is different from 1.12.
