### ISSUE TITLE
[1.12]/SF4 An exception occured while generating chunk

### ISSUE THREAD

**Issue by jaz000** [McJty/LostCities#267]
sorry to report an error generating a particular chunk

This is in Sky Factory 4 modpack / lostcities-1.12-2.0.17

The problem repeats if someone goes to the same location

[11:45:33] [Server thread/ERROR] [lostcities]: An exception occured while generating chunk: 39,9
java.lang.ArrayIndexOutOfBoundsException: -8
	at mcjty.lostcities.dimensions.world.driver.OptimizedDriver.block(OptimizedDriver.java:101) ~[OptimizedDriver.class:?]

I may try deleting/re-creating the chunk but for now it's out-of-bounds ...

https://pastebin.com/a2pUfXj0

**Comment by josephcsible** [comment]
You're on Lost Cities 2.0.17, which is over a year old. Please update to 2.0.22 and try again, and if it still crashes, then post the new crash report.
