### ISSUE TITLE
[suggestion]  slime islands/tcon integration

### ISSUE THREAD

**Issue by Seth0067** [McJty/LostCities#27]
Within Lost Cities, Tinkers Construct slime islands might be really cool if they were presented as rooftop arboriums etc. Can their generation can be lined up to building tops, etc.?  Is there a building/slime island synthesis possible (this might be a nice "tall building" that exists in non-tall building type worlds)?  

I would be interested in working on a build prototype.

**Comment by McJty** [comment]
That would be hard to do and mostly up to Tinkers Construct as it is that mod doing the generation. If the slime islands can be disabled then a companion mod could be made to generate variant slime islands that are compatible with Lost Cities

**Comment by Seth0067** [comment]
The slime islands can be turned off inthe config.  I'm going to approach this via Recurrent Complex, I think, and make my own Slime Towers.  I can share the structure with you in case you'd like to include as well?  Hope you are having a good weekend! :)
