### ISSUE TITLE
Lost Cities needs language provider Javafml:31 

### ISSUE THREAD

**Issue by ItsSquiffy** [McJty/LostCities#270]
States that there was an issue with the latest version of this with forge when I load it. States it needs language provider javafml:31 found 30. This is lostcities - 1.15-3.0.0 alpha. Was wondering if this is a newer issue due to latest versions of forge/lost cities or if I was downloading things incorrectly.

**Comment by McJty** [comment]
I don't understand this issue. What exactly is the problem? Any logs perhaps?

**Comment by ItsSquiffy** [comment]
nope figured it out

**Comment by Sheepotastic** [comment]
Yeah, because he didn't bother putting a solution for anyone else who might have this issue or closing it:
Use forge 1.15.2, not 1.15. The .jar says 1.15, but its actually 1.15.2, switching the forge will fix this issue
