### ISSUE TITLE
Configs - add clarification for "levels"

### ISSUE THREAD

**Issue by Seth0067** [McJty/LostCities#29]
Hi McJty - I'm not sure what "level" refers to in these cfg lines: "Below this chunk height cities will be level 3". A clarifying line in the cfg file might be helpful.

I'm thinking other users may not understand this either, but maybe its just me.  :)

**Comment by Flabort** [comment]
I think this might have to do with the terraces, and generating in taller biomes like extreme hills. So if a biome would generate terrain above one level but below the other level, it generates at the chunk height indicated by the higher level. But I'm not sure.

**Comment by McJty** [comment]
The city level concept is explained in the wiki:

https://wiki.mcjty.eu/mods/index.php/Lost_Cities

**Comment by Seth0067** [comment]
I hadnot seen the wiki so thanks for sharing!

Unfortunately, I don't see the concept of level in relation to the config options cited. Really having trouble parsing this - apologies. 

The reference I found to level was in building chunk generation: "First the chunk gets filled with stone up to the current city level (multiple of 6)"

The config options are 
Below this chunk height cities will be level 0=75
Below this chunk height cities will be level 1=83
Below this chunk height cities will be level 2=91
Below this chunk height cities will be level 3=99

1) are the cfg numbers above a y height or a chunk height (nx16)?
2) what does a level # determine? (aside from filling up a chunk w/stone to this level)
3) abstracted, what do changing the numbers above do?  I tried setting them to different values to see if it was something i could easily deduce but wasnt able to tell a difference (at least visually)

**Comment by McJty** [comment]
I will clarify this further in the wiki.
But basically the concept of 'level' or 'citylevel' is relative to ground level which is 71 by default. So city level 0 corresponds to height 71. City level 1 is 6 higher which means 77. City level -1 is 6 lower which is 65.

Buildings can be at city level 0 through 4.
The subway system is at city level -3

**Comment by Flabort** [comment]
So this does nothing?
Below this chunk height cities will be level 0=75

**Comment by McJty** [comment]
What? Level 0 is a valid city level. It is the lowest level at which buildings can generate

**Comment by Flabort** [comment]
No, you just said...?
In the config for a profile are "Below this chunk height cities will be level X" config options. What you just said "But basically the concept of 'level' or 'citylevel' is relative to ground level which is 71 by default. So city level 0 corresponds to height 71. City level 1 is 6 higher which means 77. City level -1 is 6 lower which is 65." conflicts with that idea.

**Comment by McJty** [comment]
I don't see the problem? Below chunk height 75 cities will be at level 0 which corresponds to ground level 71

**Comment by Flabort** [comment]
So what if you set the configs to something wacky like
Below this chunk height cities will be level 0=49
Below this chunk height cities will be level 1=61
Below this chunk height cities will be level 2=91
Below this chunk height cities will be level 3=124

**Comment by McJty** [comment]
Well that will work fine. When the biome height is less then 49 cities at those chunks will be generated at level 0 which is 71. When biome height is less then 61 cities will be generated at level 1 (77) and so on

**Comment by Flabort** [comment]
Ah, so that's what that means.

#Biomes which would generate chunks with a height below the listed levels will generate cities at the following levels: 71 for level 0, 77 for level 1, 83 for level 2, and 89 for level 3

**Comment by Seth0067** [comment]
OK, I understand how you are arriving at the level designation now. 

Are there any more values that correspond to the term "levels"?  For example, "more spawners are generated at city level 3"?  I'm just wondering why, as a packdev, I should be concerend with city levels and also why I would want to change the cited cfg options relating to levels.

**Comment by McJty** [comment]
Well say that you prefer cities to be less variable in height then you could modify that table to make sure cities never go beyond city level 2 (now they can go up to 4). Or if you like cities to be very high above the landscape you can raise the thresshold at which citylevels go higher.

**Comment by Seth0067** [comment]
ah.... *ding*.  that explanation makes this much more clear.  could i suggest you paste it in to your config for your users?
