### ISSUE TITLE
Dimension setup

### ISSUE THREAD

**Issue by FriendlyOneDev** [McJty/LostCities#297]
So, I don't really know what to do. I've created portal (2 emerald blocks(tried with diamond blocks too), bed, 6 skulls around), but it doesn't work. I tried many times, but nothing. Looked into config and saw dimension config. There was no profiles inside. I just need help with setting it up. I want cities to be in dimension and overworld to be empty. I don't mind waiting, since it's not that big of an issue:)

**Comment by McJty** [comment]
Version?

**Comment by FriendlyOneDev** [comment]
Yes, sorry, Minecraft version 1.15.2
Lost cities version 3.0.1 -alpha
Also, I'm not playing modpack

**Comment by McJty** [comment]
The Lost City dimension hasn't been implemented yet in 1.15.

**Comment by FriendlyOneDev** [comment]
Oh, I see, thanks!
