### ISSUE TITLE
how can i change Dimension type to space？

### ISSUE THREAD

**Issue by JCWONG2020** [McJty/LostCities#303]
how to change Dimension type to space？got Someone know how to change
？

**Comment by McJty** [comment]
Can you give more information? Like for what version? (it is different)

**Comment by JCWONG2020** [comment]
LostCities - 1.12-2.0.22  version

**Comment by JCWONG2020** [comment]
general  got say version=7    is this version？ or LostCities - 1.12-2.0.22

**Comment by McJty** [comment]
when creating the world you go to customize and select the space worldtype

**Comment by JCWONG2020** [comment]
if i use minecraft Normal world type use bed go in the lost cities Dimension is default world type how can i change to space type？ 。w。

**Comment by JCWONG2020** [comment]
i just want to change Dimension world type  QAQ

**Comment by McJty** [comment]
Ah you mean for the dimension. Check the lost cities config. You can change the type there.  I don't remember the name of the field but it is easy to find

**Comment by JCWONG2020** [comment]
# List of additional Lost City dimensions. Format '<id>:<profile>' [default: ]
    S:additionalDimensions <
     is this right？  but how change it？

**Comment by JCWONG2020** [comment]
# List of additional Lost City dimensions. Format '<id>:<profile>' [default: ]
S:[default: [space]
 change like this？

**Comment by McJty** [comment]
No no. It's 'dimensionProfile

**Comment by JCWONG2020** [comment]
oh~ i get it。i go find it  ，w， if i got any problem i come back later  thx bro .W.

**Comment by JCWONG2020** [comment]
# The 'profile' to use for generation of the Lost City dimension [default: default]
    S:dimensionProfile=space
change like this is  it works  thx bro love u very very much XD
