### ISSUE TITLE
Crash when generating new world

### ISSUE THREAD

**Issue by BknString** [McJty/LostCities#325]
When creating a new world, game will always crash. Tried using different world types, and cities presets. 
~~
After about an hour of trying to figure this issue out on my own, it ended up working using the rare preset. I was able to load into a world, but as soon as a city began generating as I explored, I received the same crash notification

The game crashed whilst exception ticking world
Error: java.lang.NoSuchFieldError: GLASS
Exit Code: -805306369

The game crashed whilst exception initializing level
Error: java.lang.NoSuchFieldError: GLASS
Exit Code: -1

exit code varies, but always shows the same error

Edit: added additional error message

**Comment by McJty** [comment]
Versions please?

**Comment by BknString** [comment]
MC - 1.14.4
Forge - 28.0.83
Mod - lostcities-1.14-2.0.28-alpha

**Comment by McJty** [comment]
1.14.4 is not really supported I'm afraid. In currently only support 1.15.2 (and 1.16.3 once I have ported it)

**Comment by BknString** [comment]
Ah okay, thank you anyways

I should also mention, should anyone else have this issue, setting the buildings preset to cavern with standard world type seems to work about 75% of the time
