### ISSUE TITLE
Crash during onclick handling of the Create New World button

### ISSUE THREAD

**Issue by ParzivalWolfram** [McJty/LostCities#327]
Versions:

Minecraft 1.16.3
Forge 34.1.0
Lost Cities 1.16-4.0.1-alpha

Minecraft crashes on clicking the "Create New World" button with the following information:
```
The game crashed whilst mouseclicked event handler
Error: java.lang.NoClassDefFoundError: net/minecraftforge/common/BiomeDictionary$Type
Exit Code: 255
```

[Full crash log here.](https://github.com/McJtyMods/LostCities/files/5519593/crash-2020-11-10_13.01.00-client.txt)

**Comment by McJty** [comment]
Update forge. You're using a version that is too old

**Comment by ParzivalWolfram** [comment]
34.1.0 is the current recommended version for 1.16.3. What is the minimum version supported by this mod?

**Comment by McJty** [comment]
Go with latest. Recommended is usually not 'recommended'

**Comment by ParzivalWolfram** [comment]
you wouldn't mind listing what version and up you want people using, would you? or baking it into the JAR, which would be preferable? https://github.com/McJtyMods/LostCities/issues/329#issuecomment-725816505
