### ISSUE TITLE
Backport 1.14-1.16 world type system

### ISSUE THREAD

**Issue by Ts804** [McJty/LostCities#330]
**[Enhancement/Backported Feature Request]**

The new system for generating cities in any world type would make an amazing addition to the 1.12 version of the mod, considering all of the other world types offered on forge 1.12. Of course it is completely understandable if you don't want to backport features, and would rather focus on the updating the latest versions.

**Comment by McJty** [comment]
It's extremely hard to do in 1.12. Thanks to how Mojang changed it in 1.15+ it's actually possible

**Comment by Ts804** [comment]
That's unfortunate but makes sense. Does the hacky API thing still work, where the API can be implemented into a mod to allow for a custom world type?

**Comment by McJty** [comment]
No, because on 1.15 that's no longer needed

**Comment by Ts804** [comment]
Yeah, I meant for the 1.12.2 version of the mod
