### ISSUE TITLE
Crash at creating a new game 1.16.3

### ISSUE THREAD

**Issue by AgustinBrasburg** [McJty/LostCities#331]
The game crashed whilst starting integrated server
Error: java.lang.NoSuchMethodError: net.minecraft.util.ResourceLocation.compareNamespaced(Lnet/minecraft/util/ResourceLocation;)I
Exit Code: -1

Forge: 1.16.3-forge-34.1.42

**Comment by McJty** [comment]
I need to see the entire log as well as the Lost City version

**Comment by AgustinBrasburg** [comment]
[crash-2020-11-22_08.15.14-client.txt](https://github.com/McJtyMods/LostCities/files/5579354/crash-2020-11-22_08.15.14-client.txt)
The version of lost cities is 1.16-4.0.1-alpha
It also crash with only lost cities installed so ignore the other mods
