### ISSUE TITLE
Not generating on 1.15.2 servers

### ISSUE THREAD

**Issue by ldxrly** [McJty/LostCities#333]
I don't know what to put for the structures to generate in the server properties

**Comment by McJty** [comment]
Did you check the documentation on the curseforge page?
https://www.curseforge.com/minecraft/mc-mods/the-lost-cities

**Comment by ldxrly** [comment]
> Did you check the documentation on the curseforge page?
> 
> https://www.curseforge.com/minecraft/mc-mods/the-lost-cities

Yes I did sorry I didn't understand what to do at first but I reread it and I think I get it I'll see if it works thank you Sm <3
