### ISSUE TITLE
Lost Cities: How do I configure this as a separate dimension?

### ISSUE THREAD

**Issue by mactso** [McJty/LostCities#334]
I assume this is either easy and I'm missing it or it's not working yet?

It generates fine in the overworld.  I want it to generate in dimension 111.

Help! please.

**Comment by McJty** [comment]
What version?

**Comment by mactso** [comment]
lostcities-1.16-4.0.3-alpha.jar

This is the config file

_#General settings
[profiles]
	#A list of dimensions with associated city generation profiles
	dimensionProfiles = []_

I've tried "lostcity" and "111" in the brackets.

A copy of a working config file would probably solve this for me.

Basically, I want to have a dimension of lost cities in our modpack (have been eagerly awaiting your 1.16 release.  :) ) but not have lost cities in the overworld.

The configuration button is working and I set up a default profile and Lost Cities's is generating cities in the overworld. 
There isn't a dimension in the dimensions folder and the bed won't transport me to a lost city dimension.

These also failed.
_#General settings
[profiles]
	#A list of dimensions with associated city generation profiles
	dimensionProfiles = [0:default,lost:default]_
_#General settings
[profiles]
	#A list of dimensions with associated city generation profiles
	dimensionProfiles = [overworld:default,lost:default]_
And this
#General settings
[profiles]
	#A list of dimensions with associated city generation profiles
	dimensionProfiles = ["overworld:rarecities","111:default"]

It would probably be nice if you had an "overworld/dimension" button / checkbox on the configuration screen.

**Comment by McJty** [comment]
The seperate dimension isn't implemented yet in the 1.16 version. That's on my todo

**Comment by mactso** [comment]
Ah!  Thanks!
At least I'm not going crazy.
The configuration interface you have now is very slick and intuitive.
I'll keep an eye on the mod for when it gets alternate dimensions again.
