### ISSUE TITLE
Highways aren't spawning

### ISSUE THREAD

**Issue by syntience** [McJty/LostCities#335]
1.12.2, lost cities ver. 2.0.22

world type is lost cities bop with the realistic preset. only thing i changed was setting cityChance to 0.002 in the realistic profile config

haven't seen a single highway after exploring extensively via flying around in creative mode. anything i can do to fix that?

**Comment by McJty** [comment]
By default lost cities only generates highways between two cities. By reducing the chance of cities the chance of highways will be very low. There is an option in the profile to make sure highways only need one city. That might help)

**Comment by syntience** [comment]
i see. i thought that might've been the case, but wasn't sure. i'll give that a try

**Comment by syntience** [comment]
yep. that worked. thanks!
