### ISSUE TITLE
Incorrect lighting in lost cities worldgen

### ISSUE THREAD

**Issue by esotericist** [McJty/LostCities#34]
Short version: Most buildings in lost cities worldgen (this is using the Chisel worldtype, but I would expect it shouldn't matter) are not having their lighting updated after the building is generated.

This results in interiors being fully (or near enough as to make no difference) lit inside, as if most of it was being hit by sunlight. This is especially blatant in the cellars, which should be pretty damn dark, but somehow aren't.

At first I thought somehow the chisel blocks were transmitting sunlight, or that the sunlight value per column wasn't being correctly adjusted, but I was able to confirm with a set of tests that this isn't the case.

Images for reference:

https://drive.google.com/file/d/0B9H6zC2vFoiveVBreGVnMkg1S1U/view
https://drive.google.com/file/d/0B9H6zC2vFoivQmYwWXM2dlJ0VFE/view

At this point, the entire roof of the building should be in shadow, with at most mild lighting at the edges. 

This is essentially an inversion of the unlit trees issue, where once you can force the incorrectly lit blocks to update...

https://drive.google.com/file/d/0B9H6zC2vFoivaFdVVlowdlE0TmM/view
https://drive.google.com/file/d/0B9H6zC2vFoivVVpmX2VrSEk0LUU/view

... the situation drastically improves.

**Comment by McJty** [comment]
That's extremely strange and I have not seen that myself. BTW, what version of MC?

I cannot do a lot about that though as I don't do anything with lighting. That's just minecraft itself

**Comment by esotericist** [comment]
OH! Sorry, 1.11.2, and this is on 0.0.16 (although it's been happening for a bit), and I've encountered it in a fairly minimal environment. Currently using forge 2388 (although that probably isn't pertinent).

I didn't know if there was a way for you to trigger a relight on a chunk once you'd finished generatingit, since this has a rather substantial impact on the actual threat level of the cities -- because their light value is set high, they're safer than they should be both day and night.

**Comment by McJty** [comment]
What is that platform on top of the building? Where does that come from?

And you mean the lighting is actually not only visual? Can you show light level overlay (F4) so I can see lighting numbers?

**Comment by esotericist** [comment]
The platform was something I placed to block sunlight in my testing, and to demonstrate sunlight wasn't able to hit the building.

The light level overlays available to me show what the lighting level SHOULD be -- generally 0s -- but spawners in cellars are frequently failing to spawn mobs until I do something to force the room to be darker. So this appears to be actual gameplay-impacting, not just visual.

**Comment by McJty** [comment]
I don't see how that I can be and also if you placed that platform after the chunk is generated then lighting is updated by vanilla itself and there is nothing I can do during worldgen. Do you have any other mod that might interphere with this?

**Comment by esotericist** [comment]
Lighting is only updated by vanilla selectively when you place blocks. You can see in the later images where I place then remove blocks, less of the phantom lighting remains present. I have yet to find any way of forcing an entire chunk to recalculate light as a player/operator. 

We've seen a lot of this in the past with other mod worldgens-- it used to be extremely prevalent with things like Extra Biomes XL and Biomes o'Plenty where we'd have severe problems with large parts of worldgen being pitch black despite light access -- a vanilla problem exacerbated by the mods. But something presumably changed in how those mods go about business because those errors are much rarer than they used to be.

**Comment by McJty** [comment]
I have never seen it myself though which is why I'm wondering

**Comment by esotericist** [comment]
https://drive.google.com/file/d/0B9H6zC2vFoivc3hVekV2dkNhb3M/view
https://drive.google.com/file/d/0B9H6zC2vFoivSGhTdktsY0JzVms/view

This is the cellar of a building. There are no light sources.  That's as minimal a mod collection as is possible to reproduce this problem, so I don't have a light level overlay. F3 does tell me this, though:

https://drive.google.com/file/d/0B9H6zC2vFoivNElWeG5wVzRCV2M/view

which is clearly wrong.

**Comment by esotericist** [comment]
As an interesting side note, I was NOT able to replicate this with a non-chisel world; it didn't occur to me to try it previously (because playing with the chisel blocks seems to me to be the 'obvious' thing to do), so this only seems to occur with that version of your worldgen.

I suppose it's possible that could be the chisel mod's problem, but since as far as I can tell their blocks correctly block sunlight when placed by hand, I'm not sure how.

**Comment by esotericist** [comment]
update: Maybe it is somehow chisel.
https://drive.google.com/file/d/0B9H6zC2vFoivNkRkSlBYRDVtTmc/view

Note the shadows are only underneath the sections of the bridge where there are vanilla blocks.

This is WEIRD.

**Comment by McJty** [comment]
Report it to them and see what they have to say about this

**Comment by esotericist** [comment]
Will do.

**Comment by esotericist** [comment]
Do you happen to know offhand if you use chisel blocks other than concrete in the chisel palette?

**Comment by McJty** [comment]
A few I think but can't check now

**Comment by esotericist** [comment]
Fair enough. Was mostly just curious, in case that might matter for figuring things out on the other end.

**Comment by esotericist** [comment]
tterag1098 has located and solved the problem on the chisel end. Sorry for pointing my finger at you, McJty!

**Comment by McJty** [comment]
No problem
