### ISSUE TITLE
Issue with the 1.15-3.0.2-Alpha file

### ISSUE THREAD

**Issue by failedartkid** [McJty/LostCities#341]
So, I've been trying to use the mod in a 1.15.2 Forge Mod Profile, and every time I try to run the game with the 3.0.2-Alpha file, it says the mod failed to load correctly. Attached is the log file generated, can anyone help me with this issue?
[Lost Cities Issue.txt](https://github.com/McJtyMods/LostCities/files/5883588/Lost.Cities.Issue.txt)

**Comment by McJty** [comment]
Your Forge is too old. Update to a more recent version of forge for 1.15.2
