### ISSUE TITLE
[1.16.5] Client crash on creating a new world - NullPointerException: mouseClicked event handler

### ISSUE THREAD

**Issue by ProsperCraft** [McJty/LostCities#348]
I am trying to create a custom lost cavern dim and on clicking custom it crashed.

https://gist.github.com/ProsperCraft/98eb57b65c342c7165409c9d580b8aa5

lostcities-1.16-4.0.6-alpha
forge-1.16.5-36.0.22

Modpack- [TownCraft TWO for 1.16.5](https://www.curseforge.com/minecraft/modpacks/towncraft)

**Comment by McJty** [comment]
Lost cavern is not implemented yet in 1.16. That's on my todo

**Comment by LilChocolateNeko** [comment]
I have a similar problem but it crashes as soon as I select the "Create a New World" button. The game immediately crashes afterwards and the output says "Process crashed with exit code -1"

**Comment by McJty** [comment]
@LilChocolateNeko can you give me the crashlog?

**Comment by LilChocolateNeko** [comment]
22:21:27.049
game
Forge: net.minecraftforge:34.1.1
22:21:27.049
game
FML Language Providers:
22:21:27.049
game
javafml@34.1
22:21:27.049
game
minecraft@1
22:21:27.049
game
Mod List:
22:21:27.049
game
forge-1.16.3-34.1.1-client.jar Minecraft {minecraft@1.16.3 DONE}
22:21:27.049
game
lostcities-1.16-4.0.6-alpha.jar LostCities {lostcities@1.16-4.0.6-alpha DONE}
22:21:27.049
game
forge-1.16.3-34.1.1-universal.jar Forge {forge@34.1.1 DONE}
22:21:27.050
game
Launched Version: 1.16.3-forge-34.1.1
22:21:27.050
game
Backend library: LWJGL version 3.2.2 build 10
22:21:27.050
game
Backend API: AMD Radeon HD 7560D GL version 4.3.12793 Compatibility Profile Context 13.351.1001.0, ATI Technologies Inc.
22:21:27.050
game
GL Caps: Using framebuffer using OpenGL 3.0
22:21:27.050
game
Using VBOs: Yes
22:21:27.050
game
Is Modded: Definitely; Client brand changed to 'forge'
22:21:27.050
game
Type: Client (map_client.txt)
22:21:27.050
game
Graphics mode: fancy
22:21:27.050
game
Resource Packs:
22:21:27.050
game
Current Language: English (US)
22:21:27.050
game
CPU: 4x AMD A8-5500 APU with Radeon(tm) HD Graphics
22:21:27.177
game
[m[32m[22:21:27] [Render thread/INFO] [STDOUT/]: [net.minecraft.util.registry.Bootstrap:func_179870_a:122]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Michael Suire\AppData\Roaming\.minecraft\crash-reports\crash-2021-02-18_22.21.27-client.txt
22:21:27.555
game
[mAL lib: (EE) alc_cleanup: 1 device not closed
22:21:27.889
monitor
Process Monitor
Process crashed with exit code -1

**Comment by LilChocolateNeko** [comment]
[crash-2021-02-18_22.21.27-client.txt](https://github.com/McJtyMods/LostCities/files/6007669/crash-2021-02-18_22.21.27-client.txt)

**Comment by McJty** [comment]
@LilChocolateNeko Update Minecraft and Forge (to 1.16.5)

**Comment by LilChocolateNeko** [comment]
Got it, thanks!

**Comment by ProsperCraft** [comment]
Not having this issue in 1.18.2
