### ISSUE TITLE
1.12.2 Crash my server.

### ISSUE THREAD

**Issue by SeagalKru** [McJty/LostCities#369]
(google translation from Russian)
Hey!
As soon as I, playing on my server, reach the biome in which the Lost City is generated, the server crashes.
The crash log is attached.

[crash-2021-04-09_20.20.18-server.txt](https://github.com/McJtyMods/LostCities/files/6287684/crash-2021-04-09_20.20.18-server.txt)
[crash-2021-04-09_21.00.19-server.txt](https://github.com/McJtyMods/LostCities/files/6287685/crash-2021-04-09_21.00.19-server.txt)
[crash-2021-04-09_21.04.02-server.txt](https://github.com/McJtyMods/LostCities/files/6287674/crash-2021-04-09_21.04.02-server.txt)

Thank you!

**Comment by McJty** [comment]
This crash is usually caused by wrong configuration of Lost Cities. What profile are you using and what did you modify?

**Comment by SeagalKru** [comment]
[general.cfg.txt](https://github.com/McJtyMods/LostCities/files/6290459/general.cfg.txt)
[profile_chisel.cfg.txt](https://github.com/McJtyMods/LostCities/files/6290460/profile_chisel.cfg.txt)
[profile_default.cfg.txt](https://github.com/McJtyMods/LostCities/files/6290461/profile_default.cfg.txt)

To be honest, I don’t remember what I changed. But few options.

**Comment by McJty** [comment]
Hard to see but most likely that will be the reason. If you (for example) change options so that building height can be too high or too low you can get crashes.

For example     I:buildingMaxFloors=30
is pretty dangerous

**Comment by SeagalKru** [comment]
Hmm ...
I love to experiment!
I'll put it on default.
Thank you!
