### ISSUE TITLE
Custom Profile doesn't work

### ISSUE THREAD

**Issue by BrisingrAerowing** [McJty/LostCities#37]
I have a custom profile that is a combination of the Safe and No Damage profiles, but spawners still appear and buildings are still damaged. I also disabled caves, but caves still spawn as well.

[Profile](https://gist.github.com/BrisingrAerowing/fc093e4b4be8f1a7a1d069bc22bbd59a)

This profile is used for the dimension, BTW.

**Comment by BrisingrAerowing** [comment]
I'm also seeing issues similar to #31, where I set the world style to Chisel, but that didn't do anything,

**Comment by McJty** [comment]
Can you show me your general.cfg?

**Comment by BrisingrAerowing** [comment]
Added to the original gist.

Also, I am using 0.0.19-beta.

**Comment by McJty** [comment]
Is this for the dimension or for the overworld?

**Comment by BrisingrAerowing** [comment]
This was for the dimension. So #39 fixes this.
