### ISSUE TITLE
The "allowedBiomeFactors" doesn't work at all

### ISSUE THREAD

**Issue by MarkSergeevich** [McJty/LostCities#376]
I started a blank 1.16.4 client with only The Lost Cities installed. I chose the "wasteland" preset but biomes were default. I tried to change the "allowedBiomeFactors" but it didn't help

**Comment by McJty** [comment]
More info please!

1. Version
2. to what values did you set allowedBiomeFactors?

**Comment by MarkSergeevich** [comment]
1.16-4.0.5-alpha I didn't change configs at first. I just installed the mod in curseforge app, then started new world with wasteland preset but biomes were default. Then I opened config/lostcities/profiles/wasteland.json and changed allowedBiomeFactors from [
      "desert=1",
      "desert_hills=1",
      "stone_beach=1",
      "dead_forest=1",
      "gravel_beach=1",
      "outback=1",
      "volcanic_island=1",
      "wasteland=.3"
    ]
to
[
      "desert=1"
    ]
and started new world again but nothing changed

**Comment by McJty** [comment]
You need to update to the latest version (and also to 1.16.5). The version you are using is buggy

**Comment by MarkSergeevich** [comment]
Ok, thank you
