### ISSUE TITLE
Lost Cities mod prevents Better Strongholds from working

### ISSUE THREAD

**Issue by TelepathicGrunt** [McJty/LostCities#382]
This is a very strange bug. 
Better Strongholds mod: https://www.curseforge.com/minecraft/mc-mods/yungs-better-strongholds
Latest.log: https://paste.ee/p/GeYve

If Better Strongholds and Lost Cities is both on, the locate command cannot find Better Strongholds in a fresh new world with default worldtype. As soon as Lost Cities is removed, the command is able to find a better stronghold in a fresh world. Even going to a world where the command couldn't find the stronghold before will suddenly work as well when lost cities is removed.

The command will go to the biome source's list of biomes, check for the structure in any of them, and then attempt to locate the structure. My guess it is failing at this point somehow like Lost Cities is doing something to the biome source in a way that it either loses the correct dynamic registry biomes with the stronghold in it or something. More testing will need to be done in a development environment with both mods on to see where exactly the conflict lies. This has me quite stumped rn thinking about it.

**Comment by TelepathicGrunt** [comment]
The reports that Better Stronghold is receiving about this: 
https://github.com/yungnickyoung/YUNGs-Better-Strongholds/issues/15

**Comment by McJty** [comment]
Does Better Stronghold properly register its configured feature? I think this can happen if that isn't done

**Comment by McJty** [comment]
Also in the future ALWAYS specify versions when submitting bugreports. Now I had to dig for it in logs which is annoying

**Comment by TelepathicGrunt** [comment]
Apologies. It is 1.16-4.0.9-beta Lost Cities and they do register their configuredstructure as Blame does not report anything in the logs with either of the mods on. Which leads me to think it isn't a simple registration issue but something more obscure

**Comment by TelepathicGrunt** [comment]
Just for the record, I do list mod version in most of my report. I simply just accidentally forgotten this one time.

Anyway, I got better strongholds and better cities in dev rn and trying to narrow down the issue and I seemed to had a found a clue. The chunkgenerator lost the Better Stronghold's structure spacing config when Lost Cities is on which is... strange.
![image](https://user-images.githubusercontent.com/40846040/118584506-106b9d00-b765-11eb-9bf2-d7a64bb89eeb.png)


I'll keep poking around and state updated here on any finding

**Comment by TelepathicGrunt** [comment]
Ok so Better Strongholds does get their structure spacing into the chunk generator just fine in WorldEvent.Load. But when I go to locate, the structure spacing map loses the stronghold spacing even though the chunk generator instance is the same instance. Now this is super puzzling

**Comment by McJty** [comment]
And you do register the ConfiguredFeature? (not only the feature but the configured feature has to be registered too)
Ah sorry. You do. Missed the reply. Strange

**Comment by TelepathicGrunt** [comment]
It's nick yung's mod. I'm just trying to help out lol

But I found the issue. When multiple dimensions uses the same noise setting, the DimensionStructuresSettings instance is the same instance for all of their chunk generators instead of new instances like I thought they would be. So while structure mods were modifying the structure spacing map in chunk generator's DimensionStructuresSettings, a whitelist of the overworld adds the structure spacing to the map but then removed it from that same DimensionStructuresSettings instance when it hit your dimension.

I'm gonna throw this whole issue at forge as this is something they should look into so that structure mods can do proper dimensional whitelist/blacklists as other non-mixin alternatives either causes the server to hang forever or give false positives with locate.
