### ISSUE TITLE
wrong block state on walls and some glass panes

### ISSUE THREAD

**Issue by Old-Man-D** [McJty/LostCities#384]
I started making a new mod pack, and it doesn't have many mods yet.  I made a few worlds using the lost cities presets and it seems that all the walls and some of the glass panes don't connect together like they should.  This is using LC version 1.16-4.0.9-beta and forge 36.1.23
![2021-05-18_23 40 55](https://user-images.githubusercontent.com/48969963/118769493-129d2c80-b835-11eb-886f-b2a5c84f103b.png)
![2021-05-18_23 42 56](https://user-images.githubusercontent.com/48969963/118769508-17fa7700-b835-11eb-9c71-b6e24f73d371.png)
![image](https://user-images.githubusercontent.com/48969963/118769851-74f62d00-b835-11eb-91f4-415e997e8a15.png)

**Comment by Old-Man-D** [comment]
[latest.log](https://github.com/McJtyMods/LostCities/files/6506522/latest.log)
maybe this will help too

**Comment by ghost** [comment]
I also have the issue whereby walls have the wrong blockstate

**Comment by ghost** [comment]
I'm seeing this as well -- MC 1.18.1, LC 5.0.3.

**Comment by strubium** [comment]
[https://github.com/MCTeamPotato/Lost-Cities-Potato-Edition](https://github.com/MCTeamPotato/Lost-Cities-Potato-Edition) Fixes this issue

**Comment by ghost** [comment]
> https://github.com/MCTeamPotato/Lost-Cities-Potato-Edition Fixes this issue

Oh, cool! Though, I do wish the panes could actually be fixed rather than swept under the rug by restricting buildings to only full-block glass.

**Comment by McJty** [comment]
This is already fixed in 1.18.2 and later

**Comment by strubium** [comment]
> > https://github.com/MCTeamPotato/Lost-Cities-Potato-Edition Fixes this issue
> 
> Oh, cool! Though, I do wish the panes could actually be fixed rather than swept under the rug by restricting buildings to only full-block glass.
 
Yeah, but if you want to use 1.16.4-beta this is all we got. Maybe switching to 1.16.5 will help but idk.
