### ISSUE TITLE
"easymobs" vs "hardmobs" - Clarification?

### ISSUE THREAD

**Issue by ghost** [McJty/LostCities#385]
The wiki skips over actually explaining what these conditions are. Do "hardmobs" entries only exist in the world as spawners when the difficulty is hard? Why is there no "normalmobs" section then? It is confusing.

**Comment by McJty** [comment]
No no. It's just that some spawners in buildings are classified as being tied to 'hardmobs' and other spawners are classified as being tied to 'easymobs'. It doesn't correspond to the game difficulty

**Comment by ghost** [comment]
Oh I see, and then I assume the hardmobs are spawned less frequently? Wouldn't it be better if mobs just had a weight parameter?

**Comment by McJty** [comment]
It has to do with specific spawners. Spawners that are in somewhat more hard to reach locations and locations with better loot are tagged as 'hardmobs'. While others are easymobs

**Comment by ghost** [comment]
Ah, interesting. I flew around a little while and didn't see anything but maybe I got unlucky?

**Comment by McJty** [comment]
Well they are normal spawners. Not sure how you expect to recognize them? They are just coupled to the hardmobs factor. You generally find them very deep underground

**Comment by ghost** [comment]
Recognising the mobs they were spawning, lol

Oh, another question, what scale does `factor` operate on? Is it a float, or an integer?

**Comment by McJty** [comment]
It doesn't really matter. It's relative to the total sum. So you can do it in any range

**Comment by ghost** [comment]
Ah, thanks. I should have really looked at the existing conditions.json to see that it could be both, and I could have asked a better question then lol

**Comment by ghost** [comment]
@McJty Forgive me if this is something on my end but... I've been no-clipping around under the ground for like 20 minutes now, and have not seen a single blaze or witch spawn.

Furthermore, forge cannot find any witches or blazes anywhere either:
![image](https://user-images.githubusercontent.com/24266948/118782361-5e9daf00-b8d1-11eb-97c2-890fa16afe3b.png)
![image](https://user-images.githubusercontent.com/24266948/118782387-652c2680-b8d1-11eb-9efc-ec239f1c8a74.png)

...Is this normal? I hate to be that guy, but it really looks like something isn't right with the mod. I am using a custom profile, is that it?

**Comment by McJty** [comment]
They are rare but they do work. I've seen them. Note, are you sure that spawners actually activate while you are in that mode? I know they don't in spectator mode

**Comment by ghost** [comment]
I'm using the noclip feature of NotEnoughCreativity - they are spawning!

Hmm, is there any way to adjust the hardmobs general rarity? This is too rare for what I'm going for, but I don't want them peppered literally at any floor level either.

**Comment by McJty** [comment]
Check the wiki: https://wiki.mcjty.eu/mods/index.php?title=Lost_Cities
You'll have to actually modify the building assets for that

**Comment by ghost** [comment]
Ah, okay. Thanks!

It would honestly be nice if there was some global factor that was exposed as a general config option, but I'm still glad it's possible.

**Comment by ghost** [comment]
Struggling to see any sort of legend on the wiki or in the JSON file that explains what each char represents in the building parts file.

**Comment by McJty** [comment]
They are defined in the palette.json (and some in library.json)

**Comment by ghost** [comment]
Ah, thank you. Seriously, your responsiveness and patience is outstanding, I really appreciate it.

**Comment by ghost** [comment]
Okay, I'm struggling to work with these files, because after making some changes to conditions.json and the loot tables, the profile that was working before is now no longer being used in the dimension.

**Comment by ghost** [comment]
Is there some log lostcities puts messages in relating to failing to parse the conditions file?

I'm also using KubeJS to add to and override existing instances of lostcities loot JSONs. Not sure if that is a problem.

**Comment by ghost** [comment]
Huh... that's really strange. The new mobs I added are spawning, but chest loot isn't working. Both are in the same conditions file...

EDIT: Somehow LC reset its own config to use the default profile for the dimension again. I did not change this back, I do not know why it has done this.

**Comment by ghost** [comment]
Gonna close this for now - thank you for clarifying so many things!
