### ISSUE TITLE
[1.12]Dimension does not use config 

### ISSUE THREAD

**Issue by Thedrummonger** [McJty/LostCities#39]
I changed the dimensionProfile config to S:dimensionProfile=chisel in order to use the chisel profile, however the dimension still uses the default profile when loaded in game. It also does not seem to generate a biomes o plenty world type (dimensionBoP is set to true). I have both chisel and biomes o plenty installed. 

Tested with only the following mods installed
Forge 14.21.1.2443
lostcities-0.0.19
BiomesOPlenty-1.12-7.0.0.2291
Chisel-0.0.13.14
CTM-0.2.1.5

Thanks!

**Comment by BrisingrAerowing** [comment]
This is possibly the same issue as #37.

**Comment by McJty** [comment]
Will be fixed next release
