### ISSUE TITLE
No vanilla structures

### ISSUE THREAD

**Issue by Imaninja32** [McJty/LostCities#40]
I don't know if this is intentional or accidental but with the LostCities preset I am unable to locate any vanilla structures in any dimension, even when using the /locate command.

**Comment by McJty** [comment]
Version? I have found several vanilla structures in my worlds

**Comment by McJty** [comment]
Version please?

**Comment by Imaninja32** [comment]
1.12, When I was testing in a single player world I was unable to find any ocean monuments when using the /locate command.

**Comment by McJty** [comment]
I fixed the locate command so it will work next version but the monuments do generate
