### ISSUE TITLE
id like to add this to my current world

### ISSUE THREAD

**Issue by kian2001** [McJty/LostCities#401]
is there some sort of way i can add this to my pre generated world, i want it to load in chunks that have not been loaded yet, I'm on 1.16.5

**Comment by Secq1n** [comment]
I got the same trouble on 1.16.5

**Comment by McJty** [comment]
No idea how to do this myself to be honest. Not sure it's even possible

**Comment by NixityNull** [comment]
i dont think you can do that, it's a world type so you have to select that world type for it to generate properly
