### ISSUE TITLE
dimension portal explodes

### ISSUE THREAD

**Issue by dekm** [McJty/LostCities#403]
I'm using 1.16.5 and when I create a portal with the bed and skulls it explodes on use. Any idea what would be causing this?

Also as I'm using BOP is there a dimension using that mod as well?

**Comment by McJty** [comment]
Show how you created the bed, skulls and diamond blocks.

Also in what dimension were you doing this?

**Comment by dekm** [comment]
![portal](https://user-images.githubusercontent.com/9221328/131703656-9b809720-0d7d-4402-af25-26ac5736a2a2.jpg)
![boom](https://user-images.githubusercontent.com/9221328/131703681-1e8cb6ae-4763-466c-afb1-2cee1acfae29.jpg)
This happens in both overworld and lostcities dimensions

**Comment by McJty** [comment]
So how did you get to the lost city dimension then?

**Comment by dekm** [comment]
it explodes after I take the portal 😄

**Comment by McJty** [comment]
Fixed in 4.0.10

**Comment by dekm** [comment]
> Fixed in 4.0.10

👍🏼 thanks man its a cool mod
