### ISSUE TITLE
[Asset System Question] Can I create a palette for something occupying more than one block?

### ISSUE THREAD

**Issue by PeterBennyFooda** [McJty/LostCities#414]
Hi, LostCities is awesome! I'm having fun creating custom structures in past few days.

However, I noticed that if a palette contains something bigger than one block (such as door and bed), only one block of it will be generated. Is there any attribute or option that I could use to generate this kind of blocks properly? I really want to make a bedroom with beds lol.

Version: lostcities-1.16-4.0.10-beta

**Comment by McJty** [comment]
You need to generate both parts. i.e. the lower and upper parts of the door are separate blocks and need to both put there

**Comment by PeterBennyFooda** [comment]
Thank you! I just realized that there are BlockStates specifying which part of them will be generated. 
Glad that LostCities supports BlockState format in the palette!
