### ISSUE TITLE
[Crash] String index out of range: 255

### ISSUE THREAD

**Issue by PeterBennyFooda** [McJty/LostCities#415]
Hi, I encountered this crash when walking in the city after I add some custom building parts. 
Could you please tell me what could possibly causes this issue so that I can try to fix it? 

[crash-2021-12-06_17.32.15-server.txt](https://github.com/McJtyMods/LostCities/files/7659700/crash-2021-12-06_17.32.15-server.txt)

Version: lostcities-1.16-4.0.10-beta

**Comment by McJty** [comment]
Looks like a slice where the string is too small. i.e. a 16x16 floor where less characters are given

**Comment by PeterBennyFooda** [comment]
Thank you! I found a missing character in a 16x16 slice.
