### ISSUE TITLE
[1.16.5] Unterminated Object at line 23

### ISSUE THREAD

**Issue by ChucklesMcFuckles** [McJty/LostCities#416]
I had previously run the game just fine, with no errors, however now I cannot boot to the main menu as it gives me a mod loading error and crashes.

The crash log is attached
[crash-2021-12-20_20.54.44-fml.txt](https://github.com/McJtyMods/LostCities/files/7749665/crash-2021-12-20_20.54.44-fml.txt)
.

**Comment by McJty** [comment]
That means there is an error in one of your custom profiles or assets

**Comment by ChucklesMcFuckles** [comment]
That fixed my issue, thanks
