### ISSUE TITLE
Edit "specialBedBlock" globally instead of per world save?

### ISSUE THREAD

**Issue by SuspiciousMango** [McJty/LostCities#419]
Hello! I'm currently working on a modpack and really want to use lost cities, but for progression reasons I want to change the special bed block to something other than a diamond block. Unfortunately, since that option is in the server.toml file, players have to go into the save folder of any new world generated and change that themselves. Is there a way to make it a global option, like it used to be in the 1.12 version, by putting the option in the global config files or using a datapack or something, so that every new world generated automatically has the progression I need it to? Thanks! And amazing work on the mod!

**Comment by McJty** [comment]
You can put default server configs in the defaultconfigs folder

**Comment by SuspiciousMango** [comment]
OH MY GOD THANK YOU!! After doing a little research I was pulling my hair out thinking my modpack was ruined because of the "new" forge config system (not just because of lost cities, but a bunch of other mods too). Its a shame no one anywhere has ANY documentation on the default configs folder. You are an absolute lifesaver <3
