### ISSUE TITLE
Bedrock generating at y=0 beneath cities

### ISSUE THREAD

**Issue by FynnWaelsing** [McJty/LostCities#421]
As it says on the tin, I'm getting a perfectly flat, one-block deep layer of bedrock at y=0 beneath cities (see screenshot). It does not appear to generate elsewhere. Tested this on a fresh world with just Lost Cities installed and got the same result.

Forge: 39.0.19
Lost Cities: 1.18-5.0.1

![2022-01-13_20 06 58](https://user-images.githubusercontent.com/45303748/149433957-2a7c3cc4-a110-4ebb-b60c-14ade4cf0995.png)

**Comment by McJty** [comment]
I will fix this

**Comment by McJty** [comment]
Will be fixed next release (about to be released in a moment after I fix another bug)
