### ISSUE TITLE
City Generator settings have no effect on city generation

### ISSUE THREAD

**Issue by Virgil6440** [McJty/LostCities#423]
I've been playing around with the city generator now for about 3 hours just generating new worlds with the same settings over and over again. It seems like a toss up, but I always get either a world-spanning city with no end, a few tiny cities dotted around the world with maybe 1 or 2 buildings, or cities that are decently sized but right next to each other. I've tried configuring the settings to make cities rarer and smaller, but no matter what I do the world generator always gives me one of those 3 outcomes. Am I doing something wrong or is the world generator just not listening to the values I put in?

**Comment by McJty** [comment]
It is listening but you have to exit Minecraft everytime when you want to make a new world. There is a bug there. I have already fixed it and I will release a fix probably tomorrow

**Comment by Virgil6440** [comment]
Wow, thanks for the fast reply! I am using the 1.16-4.0.10 beta version by the way.
