### ISSUE TITLE
Exception in server tick loop crash when starting singleplayer world

### ISSUE THREAD

**Issue by ghost** [McJty/LostCities#426]
Crash a few seconds after beginning a new singleplayer world

[crash-2022-02-05_00.56.31-server.txt](https://github.com/McJtyMods/LostCities/files/8007614/crash-2022-02-05_00.56.31-server.txt)

**Comment by McJty** [comment]
Did you do any changes to the profile? What profile are you using? Some more details please

**Comment by ghost** [comment]
> Did you do any changes to the profile? What profile are you using? Some more details please

I made my own profile but I think the changes are minor, I was going for a tallbuildings with a bit rarer city spawn rate
[tallrare.txt](https://github.com/McJtyMods/LostCities/files/8007627/tallrare.txt)

**Comment by McJty** [comment]
Minor changes or not. That's most likely the problem. Do you happen to know exactly what you changed? This profile is rather brittle. A minor change can cause issues if it's not the right change

**Comment by ghost** [comment]
Ok just using the rare cities profile without any changes seem to work. Sorry for bothering you and thanks for your help
