### ISSUE TITLE
1.18.1 - Lost Cities 5.0.4 - Crash when entering dimension [ ServerHangWatchdog detected that a single server tick took 60.00 seconds]

### ISSUE THREAD

**Issue by Marc-Harony** [McJty/LostCities#433]
Hi, I have a crash when I enter the lost cities Dimension.
[Here is the crash report of the server](https://pastebin.com/a8nLW8X1)
Oh, I'm using Oh The Biomes You'll Go as a Worldgen mod.

**Comment by McJty** [comment]
You are using Lost Cities 5.1.0 which is for 1.18.2. Go back to an older version for 1.18.1

**Comment by Marc-Harony** [comment]
OOPS, I didn't upload the right crash log.
[Here it is](https://pastebin.com/6499M5Sx)
Same problem here : Server crashes when entering the Lost Cities Dimension.
