### ISSUE TITLE
1.18.1 - Lost Cities 5.0.4 - Crash when entering dimension [ ServerHangWatchdog detected that a single server tick took 60.00 seconds]

### ISSUE THREAD

**Issue by Marc-Harony** [McJty/LostCities#434]
Hi, I already opened an issue for this problem, but I didn't upload the right crash log.
[Here it is](https://pastebin.com/6499M5Sx)
Same problem here : Server crashes when entering the Lost Cities Dimension.

**Comment by McJty** [comment]
Hmm weird. I cannot reproduce that. Maybe some other mod is breaking things?

**Comment by Marc-Harony** [comment]
i think it's beacause of the BYG mod. Can we configure Lost Cities to use the vanilla world generator ?

**Comment by McJty** [comment]
Lost cities can't do that. That's for byg

**Comment by Marc-Harony** [comment]
ok thanks, I'll ask to the modder.I'll keep you informed asap

**Comment by Marc-Harony** [comment]
No news from the modder. I still have this problem but the Lost Cities seems to generate normally in the overworld. So I will remove the possibility to join the dimension.
Sorry for the inconvenience and good luck with the development!
