### ISSUE TITLE
有一个大问题！Catserver安装mod后玩家进入维度后断开连接，第二次无法登录！

### ISSUE THREAD

**Issue by CeroxeAnivie** [McJty/LostCities#438]
怎么解决它
[latest.log](https://github.com/McJtyMods/LostCities/files/8597143/latest.log)

**Comment by CeroxeAnivie** [comment]
mc 服务端的版本是1.12.2

**Comment by McJty** [comment]
You just show a log but what exactly is wrong? I see no problem in the log?

**Comment by CeroxeAnivie** [comment]
https://www.aliyundrive.com/s/CVwLMMV9ZLu

**Comment by McJty** [comment]
I can't read anything on this site. I see a video but it doesn't play because I get a chinese popup on which I don't know what to do. Can you please describe the problem?

**Comment by CeroxeAnivie** [comment]
好的，事情是这样的
我按照说明搭好了传送门，然后进入了失落的城市那个维度。如果你在那个维度断开连接，下次登录时就一定会卡在“登录中”，无法登录游戏
