### ISSUE TITLE
Block ID issue 1.18.1

### ISSUE THREAD

**Issue by KhaleesiCat87** [McJty/LostCities#444]
Hi,  every time i go to the lost city dimension it times out and kicks me and the server has to be restarted. My server host said It seems there might be some block ID mismatches which might be causing me to crash client side.

**Comment by McJty** [comment]
I need logs. Also 1.18.1 is not supported anymore. Please update to 1.18.2

Op do 2 jun. 2022 21:45 schreef KhaleesiCat87 ***@***.***>:

**Comment by KhaleesiCat87** [comment]
oh ok thank you !
