### ISSUE TITLE
World gen crash (1.16.5)

### ISSUE THREAD

**Issue by NixityNull** [McJty/LostCities#445]
The game keeps crashing whenever I create or open a new world, regardless of whether I even set the world gen to cities

"The game crashed whilst starting integrated server
Error: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 15 column 6 path $.swapper.
Exit Code: -1"

Creating new world without cities: [crash-2022-06-13_20.24.31-client.txt](https://github.com/McJtyMods/LostCities/files/8895285/crash-2022-06-13_20.24.31-client.txt)
Opening old worlds: [crash-2022-06-13_20.20.26-client.txt](https://github.com/McJtyMods/LostCities/files/8895286/crash-2022-06-13_20.20.26-client.txt)
Creating new world with cities: [crash-2022-06-13_15.16.19-client.txt](https://github.com/McJtyMods/LostCities/files/8895287/crash-2022-06-13_15.16.19-client.txt)

**Comment by McJty** [comment]
This indicates an error in the json. Probably an asset that is configured wrong? What modifications were done to the assets?

**Comment by NixityNull** [comment]
absolutely no modifications to any of the assets or jsons of the mod

**Comment by NixityNull** [comment]
nevermind, apparently the json crash is coming from another mod
