### ISSUE TITLE
forge 1.18.2 tall cities stop the chunks from loading

### ISSUE THREAD

**Issue by amomentspeace** [McJty/LostCities#446]
everytime i make a new world with tall buildings chunks dont load.

**Comment by McJty** [comment]
Your own custom profile or the tall buildings incluced with Lost Cities?

**Comment by amomentspeace** [comment]
> Your own custom profile or the tall buildings incluced with Lost Cities?

both

**Comment by McJty** [comment]
I will check it out

Op di 21 jun. 2022 18:03 schreef Pluelagoon ***@***.***>:

**Comment by amomentspeace** [comment]
its fixed in the last update good work
