### ISSUE TITLE
Crash when starting the game

### ISSUE THREAD

**Issue by KasaneRuy** [McJty/LostCities#447]
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2022-06-16 20:36:58 CDT
Description: Initializing game

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from The Lost Cities (lostcities)
Caused by: java.lang.NoClassDefFoundError: mcjty/lostcities/gui/GuiLostCityConfiguration
      at mcjty.lostcities.dimensions.ModDimensions.init(ModDimensions.java:27)
      at mcjty.lostcities.setup.ModSetup.preInit(ModSetup.java:44)
      at mcjty.lostcities.LostCities.preInit(LostCities.java:41)
      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      at java.lang.reflect.Method.invoke(Method.java:497)
      at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
      at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      at java.lang.reflect.Method.invoke(Method.java:497)
      at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
      at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
      at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
      at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
      at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
      at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
      at com.google.common.eventbus.EventBus.post(EventBus.java:217)
      at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
      at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      at java.lang.reflect.Method.invoke(Method.java:497)
      at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
      at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
      at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
      at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
      at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
      at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
      at com.google.common.eventbus.EventBus.post(EventBus.java:217)
      at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
      at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
      at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
      at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
      at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:3927)
      at net.minecraft.client.main.Main.main(SourceFile:123)
      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      at java.lang.reflect.Method.invoke(Method.java:497)
      at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
      at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: mcjty.lostcities.gui.GuiLostCityConfiguration
      at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
      at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
      at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
      ... 43 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Initialization --

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 384537848 bytes (366 MB) / 805306368 bytes (768 MB) up to 3690987520 bytes (3520 MB)
  JVM Flags: 7 total; -Xmx3514M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2860 Optifine OptiFine_1.12.2_HD_U_G5 103 mods loaded, 103 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                              | Version                  | Source                                              | Signature                                |
       |:----- |:------------------------------- |:------------------------ |:--------------------------------------------------- |:---------------------------------------- |
       | LCH   | minecraft                       | 1.12.2                   | minecraft.jar                                       | None                                     |
       | LCH   | mcp                             | 9.42                     | minecraft.jar                                       | None                                     |
       | LCH   | FML                             | 8.0.99.99                | forge-1.12.2-14.23.5.2860.jar                       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCH   | forge                           | 14.23.5.2860             | forge-1.12.2-14.23.5.2860.jar                       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCH   | creativecoredummy               | 1.0.0                    | minecraft.jar                                       | None                                     |
       | LCH   | smoothfontcore                  | mc1.12.2-2.1.3           | minecraft.jar                                       | None                                     |
       | LCH   | smoothfont                      | mc1.12.2-2.1.3           | SmoothFont-mc1.12.2-2.1.3.jar                       | None                                     |
       | LCH   | uncrafted                       | 3.0.1                    | 272970268_666934927840042_5725936256084229342_n.jar | None                                     |
       | LCH   | securitycraft                   | v1.9.2                   | [1.12.2]+SecurityCraft+v1.9.2.jar                   | None                                     |
       | LCH   | vanillafix                      | 1.0.7+72                 | [[[AaAVanillaFix-1.0.7-72.jar                       | None                                     |
       | LCH   | deconstruction                  | 3.0.4                    | [MC1.12.2]DeconTable-3.0.4.jar                      | None                                     |
       | LCH   | ageingspawners                  | 1.0.0                    | AgeingSpawners-1.12.2-1.0.0.jar                     | None                                     |
       | LCH   | alcoholic                       | 1.0.0                    | alcoholic+v.1.1.1+1.12.2.jar                        | None                                     |
       | LCH   | creativecore                    | 1.10.0                   | CreativeCore_v1.10.70_mc1.12.2.jar                  | None                                     |
       | LCH   | ambientsounds                   | 3.0                      | AmbientSounds_v3.1.7_mc1.12.2.jar                   | None                                     |
       | LCH   | antiqueatlas                    | 4.6.3                    | antiqueatlas-1.12.2-4.6.3.jar                       | None                                     |
       | LCH   | antiqueatlasoverlay             | 1.2                      | antiqueatlas-1.12.2-4.6.3.jar                       | None                                     |
       | LCH   | wumpleutil                      | 2.12.9                   | wumpleutil-1.12.2-2.12.9.jar                        | None                                     |
       | LCH   | foodfunk                        | 4.9.6                    | foodfunk-1.12.2-4.9.6.jar                           | None                                     |
       | LCH   | applecore                       | 3.4.0                    | AppleCore-mc1.12.2-3.4.0.jar                        | None                                     |
       | LCH   | jei                             | 4.16.1.302               | jei_1.12.2-4.16.1.302.jar                           | None                                     |
       | LCH   | appleskin                       | 1.0.14                   | AppleSkin-mc1.12-1.0.14.jar                         | None                                     |
       | LCH   | carrots                         | 1.0.0b1                  | carrotslib-mc1.12.2-1.0.0b1.jar                     | None                                     |
       | LCH   | armorunder                      | 1.0.0                    | armorunder-mc1.12.2-1.0.0.jar                       | None                                     |
       | LCH   | badmobs                         | 1.1.40                   | BadMobs-1.12.2-1.1.40.jar                           | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCH   | betterbedrock                   | 5.1                      | BetterBedrock-1.12.2-5.1.11.jar                     | None                                     |
       | LCH   | betterhud                       | 1.4.4                    | betterhud-1.12.2-1.4.4.jar                          | None                                     |
       | LCH   | biomesoplenty                   | 7.0.1.2445               | BiomesOPlenty-1.12.2-7.0.1.2445-universal.jar       | None                                     |
       | LCH   | bloodmoon                       | 1.5.3                    | Bloodmoon-MC1.12.2-1.5.3.jar                        | d72e0dd57935b3e9476212aea0c0df352dd76291 |
       | LCH   | camera                          | 1.0.10                   | camera-1.0.10.jar                                   | None                                     |
       | LCH   | chameleon                       | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                            | None                                     |
       | LCH   | collective                      | 3.0                      | collective-1.12.2-3.0.jar                           | None                                     |
       | LCH   | toughasnails                    | 3.1.0.141                | ToughAsNails-1.12.2-3.1.0.141-universal.jar         | None                                     |
       | LCH   | comforts                        | 1.4.1.3                  | comforts-1.12.2-1.4.1.3.jar                         | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
       | LCH   | controlling                     | 3.0.10                   | Controlling-3.0.10.jar                              | None                                     |
       | LCH   | extendedrenderer                | v1.0                     | coroutil-1.12.1-1.2.37.jar                          | None                                     |
       | LCH   | coroutil                        | 1.12.1-1.2.37            | coroutil-1.12.1-1.2.37.jar                          | None                                     |
       | LCH   | configmod                       | v1.0                     | coroutil-1.12.1-1.2.37.jar                          | None                                     |
       | LCH   | cosmeticarmorreworked           | 1.12.2-v5a               | CosmeticArmorReworked-1.12.2-v5a.jar                | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
       | LCH   | craftableblazerodandblazepowder | 1.0.0                    | CraftableBlazerod_1.12.2+[0.0.1].jar                | None                                     |
       | LCH   | craftingtweaks                  | 8.1.9                    | CraftingTweaks_1.12.2-8.1.9.jar                     | None                                     |
       | LCH   | damagetilt                      | 0.1.0                    | DamageTilt-1.12.2-0.1.0.jar                         | None                                     |
       | LCH   | darknesslib                     | 1.1.2                    | DarknessLib-1.12.2-1.1.2.jar                        | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
       | LCH   | ding                            | 1.0.2                    | Ding-1.12.2-1.0.2.jar                               | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | LCH   | sereneseasons                   | 1.2.18                   | SereneSeasons-1.12.2-1.2.18-universal.jar           | None                                     |
       | LCH   | orelib                          | 3.6.0.1                  | OreLib-1.12.2-3.6.0.1.jar                           | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCH   | dsurround                       | 3.6.1.0                  | DynamicSurroundings-1.12.2-3.6.1.0.jar              | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCH   | dynamictrees                    | 1.12.2-0.9.29            | DynamicTrees-1.12.2-0.9.29.jar                      | None                                     |
       | LCH   | dynamictreesbop                 | 1.12.2-1.5.1             | DynamicTreesBOP-1.12.2-1.5.1.jar                    | None                                     |
       | LCH   | enhancedvisuals                 | 1.3.0                    | EnhancedVisuals_v1.4.4_mc1.12.2.jar                 | None                                     |
       | LCH   | eyesinthedarkness               | 0.1.0                    | EyesInTheDarkness-0.1.0.jar                         | None                                     |
       | LCH   | konkrete                        | 1.3.3                    | konkrete_forge_1.3.3_MC_1.12-1.12.2.jar             | None                                     |
       | LCH   | fancymenu                       | 2.7.2                    | fancymenu_forge_2.7.2_MC_1.12-1.12.2.jar            | None                                     |
       | LCH   | fencejumper                     | 1.0.5                    | fencejumper-1.12-1.0.5.jar                          | None                                     |
       | LCH   | cfm                             | 6.3.1                    | furniture-6.3.1-1.12.2.jar                          | None                                     |
       | LCH   | grue                            | 1.8.1                    | Grue-1.12.2-1.8.1.jar                               | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
       | LCH   | hardcoredarkness                | 2.0                      | HardcoreDarkness-MC1.12.2-2.0.jar                   | d72e0dd57935b3e9476212aea0c0df352dd76291 |
       | LCH   | healingitems                    | 0.4.8                    | healingitems-0.4.8.jar                              | None                                     |
       | LCH   | iblis_headshots                 | 1.2.6                    | iblis-headshots-1.2.6.jar                           | None                                     |
       | LCH   | ichunutil                       | 7.2.2                    | iChunUtil-1.12.2-7.2.2.jar                          | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | LCH   | mts                             | 21.2.0                   | Immersive+Vehicles-1.12.2-21.2.0.jar                | None                                     |
       | LCH   | incontrol                       | 3.9.18                   | incontrol-1.12-3.9.18.jar                           | None                                     |
       | LCH   | inventorytweaks                 | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                            | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
       | LCH   | jrftl                           | 1.1                      | JRFTL[1.12.2]-1.1.jar                               | None                                     |
       | LCE   | lostcities                      | 2.0.22                   | lostcities-1.12-2.0.22.jar                          | None                                     |
       | LC    | malisiscore                     | 1.12.2-6.5.1-SNAPSHOT    | malisiscore-1.12.2-6.5.1.jar                        | None                                     |
       | LC    | malisisdoors                    | 1.12.2-7.3.0             | malisisdoors-1.12.2-7.3.0.jar                       | None                                     |
       | LC    | mcwfences                       | 1.0.0                    | mcw-fences-1.0.0-mc1.12.2.jar                       | None                                     |
       | LC    | mcwtrpdoors                     | 1.0.2                    | mcw-trapdoors-1.0.3-mc1.12.2.jar                    | None                                     |
       | LC    | mcwwindows                      | 1.0                      | mcw-windows-1.0.0-mc1.12.2.jar                      | None                                     |
       | LC    | mobamputation                   | 7.0.0                    | MobAmputation-1.12.2-7.0.1.jar                      | None                                     |
       | LC    | mobdismemberment                | 7.0.0                    | MobDismemberment-1.12.2-7.0.0.jar                   | None                                     |
       | LC    | mobends                         | 1.2.1                    | MoBends_1.12.2-1.2.1-19.12.21.jar                   | None                                     |
       | LC    | mobsunscreen                    | 1.12.2-2.1.3             | mobsunscreen-1.12.2-2.1.3.jar                       | None                                     |
       | LC    | modnametooltip                  | 1.10.1                   | modnametooltip_1.12.2-1.10.1.jar                    | None                                     |
       | LC    | mousetweaks                     | 2.10.1                   | MouseTweaks-2.10.1-mc1.12.2.jar                     | None                                     |
       | LC    | mumblelink                      | 1.12.2-4.2.5             | mumblelink-1.12.2-4.2.5.jar                         | None                                     |
       | LC    | extendedpasupport               | 1.0.0                    | mumblelink-1.12.2-4.2.5.jar                         | None                                     |
       | LC    | mw                              | 0.4.4.6                  | mw_2.0-0.4.4.6_mc1.12.2.jar                         | None                                     |
       | LC    | norecipebook                    | 1.2.1                    | noRecipeBook_v1.2.2formc1.12.2.jar                  | None                                     |
       | LC    | northerncompass                 | 1.12.2-1.0.0             | NorthernCompass-1.12.2-1.0.0.jar                    | 565fa4dbf20e7c3c4423950ca8e0bdabf7568796 |
       | LC    | overworld-quartz                | 1.12-1.0.0.1             | overworldquartz-1.12-1.0.0.1.jar                    | None                                     |
       | LC    | realdrops                       | 1.2.14                   | RealisticItemDrops-1.2.14.jar                       | None                                     |
       | LC    | serenetweaks                    | 0.0.1                    | SereneTweaks-1.0.jar                                | None                                     |
       | LC    | shouldersurfing                 | 2.2.1                    | ShoulderSurfing-1.12.2-2.2.2.jar                    | d6261bb645f41db84c74f98e512c2bb43f188af2 |
       | LC    | flashlight                      | 2.0.0                    | simpleFlashlight-2.0.0.jar                          | None                                     |
       | LC    | craftable_slimeball             | 1.0.0                    | SlimeBottles.jar                                    | None                                     |
       | LC    | soundfilters                    | 0.12.1_for_1.12          | SoundFilters-0.12.1_for_1.12.jar                    | None                                     |
       | LC    | srparasites                     | 1.9.4                    | SRParasites-1.12.2v1.9.5.jar                        | None                                     |
       | LC    | scapeandrunvaccine              | 1.0.0                    | srpvaccine-1.0.0.jar                                | None                                     |
       | LC    | starterkit                      | 2.4                      | starterkit_1.12.2-2.4.jar                           | None                                     |
       | LC    | storagedrawers                  | 5.2.2                    | StorageDrawers-1.12.2-5.4.2.jar                     | None                                     |
       | LC    | mo                              | 1.0                      | sulfur-potassium-1.12-1.1.jar                       | None                                     |
       | LC    | tenshilib                       | 1.2.4                    | TenshiLib-1.12.2-1.2.4.jar                          | None                                     |
       | LC    | tawct                           | 1.0                      | time-and-wind-ct-1.3+1.12.2.jar                     | None                                     |
       | LC    | tlauncher_custom_cape_skin      | 1.4                      | tlskincape_1.12.2-1.4.jar                           | None                                     |
       | LC    | unbreakable                     | 1.0.0                    | Unbreakable+1.0.0.jar                               | None                                     |
       | LC    | unexperienced                   | 1.1.0                    | Unexperienced-1.12.2-1.1.1.jar                      | None                                     |
       | LC    | waterskin                       | 1.0.1                    | waterskin-1.0.1.jar                                 | None                                     |
       | LC    | weather2                        | 1.12.1-2.6.12            | weather2-1.12.1-2.6.12.jar                          | None                                     |
       | LC    | zombieawareness                 | 1.12.1-1.11.16           | zombieawareness-1.12.1-1.11.16.jar                  | None                                     |
       | LC    | nimble                          | 0.0.2                    | Nimble-0.0.2.jar                                    | None                                     |
       | LC    | hungeroverhaul                  | 1.12.2-1.3.3.jenkins148  | HungerOverhaul-1.12.2-1.3.3.jenkins148.jar          | None                                     |
  Loaded coremods (and transformers): TransformLoader (DynamicSurroundings-1.12.2-3.6.1.0.jar)
                                        
                                      RBLoadingPlugin (RealBench-1.12.2-1.3.3.jar)
                                        pw.prok.realbench.asm.RBTransformer
                                      SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
                                        sereneseasons.asm.transformer.EntityRendererTransformer
                                        sereneseasons.asm.transformer.WorldTransformer
                                      TenshiCore (TenshiLib-1.12.2-1.2.4.jar)
                                        com.flemmli97.tenshilib.asm.ASMTransformer
                                      KonkreteCore (konkrete_forge_1.3.3_MC_1.12-1.12.2.jar)
                                        
                                      CreativePatchingLoader (CreativeCore_v1.10.70_mc1.12.2.jar)
                                        
                                      AppleCore (AppleCore-mc1.12.2-3.4.0.jar)
                                        squeek.applecore.asm.TransformerModuleHandler
                                      F5FixLoadingPlugin (f5fix-1.2.jar)
                                        de.morrien.f5fix.F5FixTransformer
                                      SecurityCraftLoadingPlugin ([1.12.2]+SecurityCraft+v1.9.2.jar)
                                        
                                      FMCore (fancymenu_forge_2.7.2_MC_1.12-1.12.2.jar)
                                        
                                      LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
                                        lumien.bloodmoon.asm.ClassTransformer
                                      ShoulderPlugin (ShoulderSurfing-1.12.2-2.2.2.jar)
                                        com.teamderpy.shouldersurfing.asm.transformers.EntityPlayerRayTrace
                                        com.teamderpy.shouldersurfing.asm.transformers.EntityRendererGetMouseOver
                                        com.teamderpy.shouldersurfing.asm.transformers.EntityRendererGetMouseOver2
                                        com.teamderpy.shouldersurfing.asm.transformers.EntityRendererOrientCamera
                                        com.teamderpy.shouldersurfing.asm.transformers.EntityRendererRayTrace
                                        com.teamderpy.shouldersurfing.asm.transformers.GuiIngameRenderAttackIndicator
                                        com.teamderpy.shouldersurfing.asm.transformers.GuiCrosshairsBCRenderAttackIndicator
                                      VanillaFixLoadingPlugin ([[[AaAVanillaFix-1.0.7-72.jar)
                                        
                                      Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      CorePlugin (SmoothFont-mc1.12.2-2.1.3.jar)
                                        bre.smoothfont.asm.Transformer
                                      MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
                                        
                                      LoadingPlugin (HardcoreDarkness-MC1.12.2-2.0.jar)
                                        lumien.hardcoredarkness.asm.ClassTransformer
                                      weaponlib (mw_2.0-0.4.4.6_mc1.12.2.jar)
                                        com.vicmatskiv.weaponlib.core.WeaponlibClassTransformer
                                      TLSkinCapeHookLoader (tlskincape_1.12.2-1.4.jar)
                                        gloomyfolken.hooklib.minecraft.PrimaryClassTransformer
  GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 27.20.100.9664' Renderer: 'Intel(R) UHD Graphics 630'
  Suspected Mods: The Lost Cities (lostcities)
  Launched Version: Forge 1.12.2
  LWJGL: 2.9.4
  OpenGL: Intel(R) UHD Graphics 630 GL version 4.6.0 - Build 27.20.100.9664, Intel
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: [1.12.2] Jhon Smith Legacy, [1.12.2] TZP+2.1.zip, [1.16.5] Michipapu (incompatible)
  Current Language: English (US)
  Profiler Position: N/A (disabled)
  CPU: 6x Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz

**Comment by KasaneRuy** [comment]
This happened after I changed the config file for wasteland profile I thought deleting the file would fix it but it keep crashing, I also tried uninstalling it and installing it again but it neither worked

**Comment by McJty** [comment]
Seems something got corrupt. It is crashing in a place that isn't possible really. Also you're using a pretty old version of Java 8.

**Comment by KasaneRuy** [comment]
The error was fixed by restarting the launcher but thanks for your time anyway
