### ISSUE TITLE
how to disable spawning of cities in nether/end

### ISSUE THREAD

**Issue by GeminiMarshdevil** [McJty/LostCities#449]
howdy! love the mod on 1.18.2 its a core feature of my modpack. server community loves it too. 

the issue is the cities keep spawning in the nether and the end.  they take over the entire map of each dimension. nothing i do seems to matter in configs or profiles.  is there a way to simply disable their spawning on other dimensions?

**Comment by GeminiMarshdevil** [comment]
![image](https://user-images.githubusercontent.com/35816347/175840564-5049f14d-6322-4a43-ab83-01b7efc8e531.png)

**Comment by McJty** [comment]
um that's weird. They shouldn't spawn there at all? What version? Any other mods?

**Comment by McJty** [comment]
Closing due to no response
