### ISSUE TITLE
[1.18.2] lostcities-1.18-5.2.5 breaks single player world creation due to datapacks.

### ISSUE THREAD

**Issue by ProsperCraft** [McJty/LostCities#451]
When updating to lostcities-1.18-5.2.5 I am not longer able to load in due to a datapack issue, downgrading to 5.2.4 fixes it.

Debug log-
https://gist.githubusercontent.com/ProsperCraft/7a48374ebe0eabb9363f332ce78ebe9e/raw/1c978798d88874c2fbbe10b35ed567484b735dd4/gistfile1.txt

**Comment by ProsperCraft** [comment]
Here is the debug log showing it loading properly after downgrading to 5.2.4
https://gist.githubusercontent.com/ProsperCraft/d8ccb0e94880c02b010e8c7c63dd60e3/raw/99479e92b0e0bc0a74cf621fad4a3d84556ea082/gistfile1.txt

**Comment by McJty** [comment]
Fixed in 5.2.6
