### ISSUE TITLE
my game keeps crashing trying to load a world

### ISSUE THREAD

**Issue by Nobody48213** [McJty/LostCities#457]
the crash report is ---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 7/10/22, 9:41 PM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: 'void net.minecraft.server.level.DistanceManager.addRegionTicket(net.minecraft.server.level.TicketType, net.minecraft.world.level.ChunkPos, int, java.lang.Object, boolean)'
	at net.minecraft.server.level.ServerChunkCache.addRegionTicket(ServerChunkCache.java:429) ~[client-1.18.2-20220404.173914-srg.jar%2381!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerChunkCache.m_8387_(ServerChunkCache.java:425) ~[client-1.18.2-20220404.173914-srg.jar%2381!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_129940_(MinecraftServer.java:471) ~[client-1.18.2-20220404.173914-srg.jar%2381!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:318) ~[client-1.18.2-20220404.173914-srg.jar%2381!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.server.IntegratedServer.m_7038_(IntegratedServer.java:84) ~[client-1.18.2-20220404.173914-srg.jar%2381!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.18.2-20220404.173914-srg.jar%2381!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%2381!/:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 4102817792 bytes (3912 MiB) / 6186598400 bytes (5900 MiB) up to 8388608000 bytes (8000 MiB)
	CPUs: 4
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Athlon 3000G with Radeon Vega Graphics     
	Identifier: AuthenticAMD Family 23 Model 24 Stepping 1
	Microarchitecture: Zen / Zen+
	Frequency (GHz): 3.49
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: AMD Radeon(TM) Vega 3 Graphics
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 2048.00
	Graphics card #0 deviceId: 0x15d8
	Graphics card #0 versionInfo: DriverVersion=30.0.13023.4001
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 19407.50
	Virtual memory used (MB): 14611.23
	Swap memory total (MB): 5137.62
	Swap memory used (MB): 0.00
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8000m -Xms256m
	Server Running: true
	Player Count: 0 / 8; []
	Data Packs: vanilla, mod:tenshilib, mod:mcwbridges, mod:mousetweaks (incompatible), mod:creativecore (incompatible), mod:jei (incompatible), mod:incontrol (incompatible), mod:sound_physics_remastered (incompatible), mod:neat (incompatible), mod:mobsunscreen (incompatible), mod:journeymap, mod:fastbench (incompatible), mod:enhancedvisuals (incompatible), mod:controlling (incompatible), mod:placebo (incompatible), mod:comforts (incompatible), mod:yungsapi, mod:backpacked (incompatible), mod:cgm, mod:lostcities (incompatible), mod:badmobs, mod:farsightedmobs (incompatible), mod:cfm, mod:framework (incompatible), mod:firstaid (incompatible), mod:forge, mod:appleskin (incompatible), mod:improvedmobs, mod:bettermineshafts
	World Generation: Experimental
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	OptiFine Version: OptiFine_1.18.2_HD_U_H6_pre1
	OptiFine Build: 20220303-215048
	Render Distance Chunks: 5
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.2.14761 Core Profile Forward-Compatible Context 21.30.23.04 30.0.13023.4001
	OpenGlRenderer: AMD Radeon(TM) Vega 3 Graphics
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4
	ModLauncher: 9.1.3+9.1.3+main.9b69c82a
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 slf4jfixer PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 OptiFine TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.18.2-20220404.173914-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		tenshilib-1.18.2-1.6.8-forge.jar                  |TenshiLib                     |tenshilib                     |1.18.2-1.6.8        |DONE      |Manifest: NOSIGNATURE
		mcw-bridges-2.0.3-mc1.18.2.jar                    |Macaw's Bridges               |mcwbridges                    |2.0.3               |DONE      |Manifest: NOSIGNATURE
		MouseTweaks-forge-mc1.18-2.21.jar                 |Mouse Tweaks                  |mousetweaks                   |2.21                |DONE      |Manifest: NOSIGNATURE
		CreativeCore_FORGE_v2.6.12_mc1.18.2.jar           |CreativeCore                  |creativecore                  |2.6.12              |DONE      |Manifest: NOSIGNATURE
		jei-1.18.2-9.7.0.209.jar                          |Just Enough Items             |jei                           |9.7.0.209           |DONE      |Manifest: NOSIGNATURE
		incontrol-1.18-6.0.12.jar                         |InControl                     |incontrol                     |1.18-6.0.12         |DONE      |Manifest: NOSIGNATURE
		soundphysics-forge-1.18.2-1.0.6.jar               |Sound Physics Remastered      |sound_physics_remastered      |1.18.2-1.0.6        |DONE      |Manifest: NOSIGNATURE
		Neat-1.8-31.jar                                   |Neat                          |neat                          |1.8-31              |DONE      |Manifest: NOSIGNATURE
		mobsunscreen-1.18.1-3.0.4.jar                     |Mob Sunscreen                 |mobsunscreen                  |1.18.1-3.0.4        |DONE      |Manifest: NOSIGNATURE
		journeymap-1.18.2-5.8.5-forge.jar                 |Journeymap                    |journeymap                    |5.8.5               |DONE      |Manifest: NOSIGNATURE
		FastWorkbench-1.18.2-6.0.2.jar                    |Fast Workbench                |fastbench                     |6.0.2               |DONE      |Manifest: NOSIGNATURE
		EnhancedVisuals_FORGE_v1.5.5_mc1.18.2.jar         |EnhancedVisuals               |enhancedvisuals               |1.5.5               |DONE      |Manifest: NOSIGNATURE
		Controlling-forge-1.18.2-9.0+21.jar               |Controlling                   |controlling                   |9.0+21              |DONE      |Manifest: NOSIGNATURE
		Placebo-1.18.2-6.4.1.jar                          |Placebo                       |placebo                       |6.4.1               |DONE      |Manifest: NOSIGNATURE
		comforts-forge-1.18.2-5.0.0.4.jar                 |Comforts                      |comforts                      |1.18.2-5.0.0.4      |DONE      |Manifest: NOSIGNATURE
		YungsApi-1.18.2-Forge-2.0.8.jar                   |YUNG's API                    |yungsapi                      |1.18.2-Forge-2.0.8  |DONE      |Manifest: NOSIGNATURE
		backpacked-2.1.8-1.18.2.jar                       |Backpacked                    |backpacked                    |2.1.8               |DONE      |Manifest: NOSIGNATURE
		cgm-1.2.6-1.18.2.jar                              |MrCrayfish's Gun Mod          |cgm                           |1.2.6               |DONE      |Manifest: NOSIGNATURE
		lostcities-1.18-5.3.2.jar                         |LostCities                    |lostcities                    |1.18-5.3.2          |DONE      |Manifest: NOSIGNATURE
		BadMobs-1.18.2-13.01.jar                          |BadMobs                       |badmobs                       |13.01               |DONE      |Manifest: NOSIGNATURE
		farsightedmobs-forge-1.1-1.18.jar                 |Farsighted Mobs               |farsightedmobs                |1.1                 |DONE      |Manifest: NOSIGNATURE
		cfm-7.0.0-pre29-1.18.2.jar                        |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre29         |DONE      |Manifest: NOSIGNATURE
		framework-0.2.3-1.18.2.jar                        |Framework                     |framework                     |0.2.3               |DONE      |Manifest: NOSIGNATURE
		firstaid-1.11.1.jar                               |First Aid                     |firstaid                      |1.11.1              |DONE      |Manifest: NOSIGNATURE
		forge-1.18.2-40.1.60-universal.jar                |Forge                         |forge                         |40.1.60             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		appleskin-forge-mc1.18-2.4.0.jar                  |AppleSkin                     |appleskin                     |2.4.0+mc1.18        |DONE      |Manifest: NOSIGNATURE
		improvedmobs-1.18.2-1.10.14-forge.jar             |Improved Mobs Mod             |improvedmobs                  |1.18.2-1.10.14      |DONE      |Manifest: NOSIGNATURE
		YungsBetterMineshafts-1.18.2-Forge-2.2.jar        |YUNG's Better Mineshafts      |bettermineshafts              |1.18.2-Forge-2.2    |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 93e5054e-0cc1-4d84-a74f-ba2ef471d661
	FML: 40.1
	Forge: net.minecraftforge:40.1.60

**Comment by McJty** [comment]
What has this to do with Lost Cities?

**Comment by De0lsjx** [comment]
I had to join Github because of this issue too. I kept getting the same beginning line of text "java.lang.NoSuchMethodError: 'void net.minecraft.server.level.DistanceManager.addRegionTicket(net.Minecraft.server.level.TicketType, net.minecraft.world.level.ChunkPos, int, java.lang.Object, boolean)" no matter how many times I try to take out so many mods.
I had over 217 mods (yes I know it's a lot), made a new profile to find where the issue was, and thought it was balm turned out it wasn't causing it. It would then tell me it's a different mod the next time in the exact same place. I am trying to make my own mod pack with it included and centralize the pack around it. I am still looking into it but I am eliminating too many mods to narrow it down to this mod and/or some other mod.

**Comment by McJty** [comment]
Again, what has this to do with Lost Cities?

**Comment by McJty** [comment]
Closing because not related to Lost Cities

**Comment by De0lsjx** [comment]
Where is the error coming from then? I can't pinpoint it. or it is about the compatibility?

**Comment by McJty** [comment]
Hard to say. I doubt it has to do with Lost Cities but you could try removing mods until you can find the problematic one
