### ISSUE TITLE
No Spawners when using a custom Library.json (1.12.2)

### ISSUE THREAD

**Issue by knoxhack** [McJty/LostCities#458]
When I tried to load a custom Library JSON with ($lostcities/library.json) it does not generates spawners.
But it does generates them when I use the internal one (/assets/lostcities/citydata/library.json)

Version: lostcities-1.12-2.0.22

**Comment by McJty** [comment]
Show me your custom library. Also show me you lostcities-common.toml

**Comment by knoxhack** [comment]
general.cfg file: [https://raw.githubusercontent.com/NFINIT-Development/Astroblock-3/main/general.cfg](https://raw.githubusercontent.com/NFINIT-Development/Astroblock-3/main/general.cfg)

profile_chisel.cfg file: [https://raw.githubusercontent.com/NFINIT-Development/Astroblock-3/main/profile_chisel.cfg](https://raw.githubusercontent.com/NFINIT-Development/Astroblock-3/main/profile_chisel.cfg)

library.json: [https://raw.githubusercontent.com/NFINIT-Development/Astroblock-3/main/library.json](https://raw.githubusercontent.com/NFINIT-Development/Astroblock-3/main/library.json)

conditions.json file: [https://raw.githubusercontent.com/NFINIT-Development/Astroblock-3/main/conditions.json](https://raw.githubusercontent.com/NFINIT-Development/Astroblock-3/main/conditions.json)

palette_chisel.json file: [https://raw.githubusercontent.com/NFINIT-Development/Astroblock-3/main/palette_chisel.json](https://raw.githubusercontent.com/NFINIT-Development/Astroblock-3/main/palette_chisel.json)

**Comment by knoxhack** [comment]
even if I try to use an unmodified version of Library.json found at [here](https://raw.githubusercontent.com/McJtyMods/LostCities/1.16/src/main/resources/assets/lostcities/citydata/library.json) it doesnt generate them

**Comment by McJty** [comment]
Why did you change minecraft:mob_spawner to minecraft:spawner in your library.json?
That's your problem. Change it back.
Also that unmodified version of library.json is not correct either. It must be mob_spawner and not spawner

**Comment by knoxhack** [comment]
That fixes it, thank you so much!

I did not change minecraft:mob_spawner to minecraft:spawner tho, it came like that from the example internal file fround [here](https://raw.githubusercontent.com/McJtyMods/LostCities/1.16/src/main/resources/assets/lostcities/citydata/library.json)

**Comment by McJty** [comment]
Well here is what Lost Cities itself uses internally. Clearly says mob_spawner. Not sure where you got your data from:

https://github.com/McJtyMods/LostCities/blob/1.12/src/main/resources/assets/lostcities/citydata/library.json#L62

**Comment by knoxhack** [comment]
ahh I see, I was using the 1.16 files not the 1.12.2 files

"https://raw.githubusercontent.com/McJtyMods/LostCities/1.16/src/main/resources/assets/lostcities/citydata/library.json"

**Comment by McJty** [comment]
Yes, I just was thinking the same :-)

**Comment by knoxhack** [comment]
Yeah, thanks so much! Now I can fully customize my cities :)
