### ISSUE TITLE
Start failed

### ISSUE THREAD

**Issue by bBhdshuaib** [McJty/LostCities#464]
[crash-2022-07-26_17.38.44-fml.txt](https://github.com/McJtyMods/LostCities/files/9188650/crash-2022-07-26_17.38.44-fml.txt)
Cannot start after adding this mod,Is there anyone who can help me?thanks:)

**Comment by McJty** [comment]
Update Forge. Your forge is extremely old

**Comment by bBhdshuaib** [comment]
> Update Forge. Your forge is extremely old

Oh, my God, thanks, brother
