### ISSUE TITLE
blocks are perceived by the world incorrectly

### ISSUE THREAD

**Issue by SupremeLOLKA** [McJty/LostCities#466]
1. it's raining right through the blocks
2. on the map, the blocks are also not visible
however, the blocks break adequately and can be walked on.
I use a lot of mods, including Quark, Vallhelsia and Biomes o Plenty...
![image](https://user-images.githubusercontent.com/110157337/181444806-8bd3c2fe-d53a-49a0-8c05-39c8d34efd72.png)
![image](https://user-images.githubusercontent.com/110157337/181445239-1c8d2ee0-3f1a-47f9-9bb7-ffb373c2d7ea.png)
full list of mods:
![image](https://user-images.githubusercontent.com/110157337/181446942-3305edad-2ea0-48a6-8728-0e07e96261ec.png)
![image](https://user-images.githubusercontent.com/110157337/181447023-39467314-2b3d-4296-9d19-b40b3fc3c75a.png)

**Comment by McJty** [comment]
I *literally* fixed this bug yesterday. Please update and in the future check for updates first

**Comment by SupremeLOLKA** [comment]
Promptly. Just yesterday and installed this mod. Thanks!
