### ISSUE TITLE
Crashes when creating a new world with The Lost Cities generation enabled (1.18.2)

### ISSUE THREAD

**Issue by Nevrai** [McJty/LostCities#469]
When I create a new world using The Lost Cities generation, my game crashes. I had it set to rare cities and had only modified the chance of a city (to 0.006).

Additionally, albeit a much more minor issue, the game also crashes every time I click the rightmost button a few times in The Lost Cities’ configuration menu when creating a new world, which I believe was labelled “Standard.” There was no crash report made in that case, but that’s not as big of an issue as the game crashing on world creation.

**Crash report:** https://pastebin.com/raw/mcJwjyxC

### Versions
* **Minecraft:** 1.18.2
* **Forge:** 40.1.68 (latest for 1.18.2)
* **The Lost Cities:** 5.3.7 (latest for 1.18.2)

**Comment by McJty** [comment]
Is this with custom assets?

**Comment by McJty** [comment]
The customization screen crash has been fixed

**Comment by Nevrai** [comment]
Thanks for the fix! Can confirm that everything works as it should now.
