### ISSUE TITLE
"lostcities_bop" generator type mountainous?

### ISSUE THREAD

**Issue by BlayzerQ** [McJty/LostCities#47]
lostcities-1.1x-1.0.1
I used the BIOMESOP generation type and the world was nice and good, but when I set the value of lostcities_bop, the whole world turns into a very mountainous one. Why is that?

**Comment by McJty** [comment]
Screenshot? Might be you just got unlucky. Did you try to fly around?

**Comment by BlayzerQ** [comment]
I flying, regenerated the world - everywhere so.
lostcities_bop (Coordinates are different) Cities are generated:
https://image.prntscr.com/image/sg1QTGzdSIeJO6lwaqanIw.png
https://image.prntscr.com/image/tQ8imuFtTJKtHbiOORiEag.png
https://image.prntscr.com/image/BSIoeiA3RTem_MfujPMGYQ.png
https://image.prntscr.com/image/EwQXdM-DR0GjgRGwGXKrCw.png
BIOMESOP - Cities are not generated:
https://image.prntscr.com/image/oKNdexbqT1uToLCz6OAFPA.png
https://image.prntscr.com/image/pR3sg6EzRgqcQa6a60aFeA.png

**Comment by McJty** [comment]
What profile did you select? Did you modify any configs?

**Comment by BlayzerQ** [comment]
profile - rarecities, with default too so. Profiles did not change.
general config: https://pastebin.com/9rQ9bXsc

**Comment by BlayzerQ** [comment]
Is it possible to generate cities for a BIOMESOP world type?

**Comment by Alaberti** [comment]
What other mods do you have? I think I saw something like this with the Ecology mod.

**Comment by BlayzerQ** [comment]
Mod list: https://pastebin.com/1q9qxrNR
MineTweaker? I make them a Wasteland map.

**Comment by BlayzerQ** [comment]
Yes, its a BiomeTweaker. I change biome height in my script, but with world type BIOMESOP its work fine. I remove the height changing and all fine.
BiomeTweaker likley issues. Thanks for the tip!

**Comment by BlayzerQ** [comment]
There are still problems with mountainousness. Excessive mountaininess even without changing altitude.

**Comment by McJty** [comment]
I doubt this has anything to do with lost cities though. I use exactly the same setting myself for my LP (Lost cities + BOP) and it works perfectly fine. In fact I have a big lack of mountains near my base :-)

**Comment by esotericist** [comment]
This is actually due to some peculiarities in the BOP biomes; they rely on some specific things that their worldtype does with regards to elevation in order to handle transitions between biomes. This is why they no longer have an option in their config to enable BOP biomes in vanilla worldtypes.

It's basically not fixable without either importing a lot of BOP's logic into lost cities (obviously a bad plan), or having BOP itself add support for lost cities via the provided api (the 'correct' solution).

It's a common enough problem for my servers that I'm honestly considering either not using the bop worldtype, or cutting out many of the 'mountainous' bop biomes. 😞

**Comment by McJty** [comment]
Is this problem only on servers then because I never noticed this problem in my single player instances

**Comment by BlayzerQ** [comment]
I fix this by changing biome height by BiomeTweaker script.
zero = forBiomes(46, 63, 73, 76, 85, 88, 89, 92, 53, 71)
zero.set("height", 0)
zero.set("heightVariation", 0)

**Comment by esotericist** [comment]
I'm doing my testing on single player, and experiencing that with several of the biomes o plenty biomes.

Basically, the truly mountainous bop biomes can generate super weird when they generate next to non-transitional biomes outside of the biomesop worldtype (whether SSP or SMP). It won't always happen, but it's going to sometimes happen.

there's ways of hacking around it, but it's super clunky. The BOP devs have no intention of making the biomes in question work correctly in other worldtypes.

@BlayzerQ those IDs are going to be installation-specific; the ID numbers are auto generated.
