### ISSUE TITLE
Error Loading Mod in 1.18.2

### ISSUE THREAD

**Issue by Plebiful** [McJty/LostCities#471]
The lost cities mod for 1.18.2 appears to be broken for me, as whenever I load it up in 1.18.2, it has the text of "Lost Cities has encountered an error during the common_setup event phase". 

This version was run on both a profile with custom assets and run without any custom assets. Both result the same.

I reinstalled minecraft/curseforge and made sure it was the most recent version, which it is.

I am currently running the 1.18-5.3.7 version. I also tried putting it two versions back (still in 1.18.2) and it still didn't work

Here is an error log of what happened on the most recent version: https://pastebin.com/raw/fD7zDGfE

If there are more parts of the file that you need to see, or you need more clarification, please reply to this post and I'll respond and update accordingly.

Thank you.

**Comment by McJty** [comment]
Update forge. It's ancient
