### ISSUE TITLE
Lost Cities is not generating

### ISSUE THREAD

**Issue by rashie12** [McJty/LostCities#483]
I followed the instructions in the curseforge description and even set the rarity to 0.1. And it still will not generate the cities.

**Comment by McJty** [comment]
Be more specific. Tell me EXACTLY what you did. Also what version?

**Comment by rashie12** [comment]
Version I'm using is 1.16.5.

-Created single player world
-Click More World Options and enabled Lost Cities as instructed in the Curseforge description.

**Comment by rashie12** [comment]
> Be more specific. Tell me EXACTLY what you did. Also what version?

Version I'm using is 1.16.5

-Create New World (Single player)

-Click World Options and enabled Lost Cities that's at the top right.

-Then generated the world.

**Comment by McJty** [comment]
Ok, did you select the profile? After clicking the Lost Cities button on the top right you STILL need to do something there. By default the top-left button is set to 'disabled'.

**Comment by rashie12** [comment]
Already selected the profile and changed it to 'onlycities'

**Comment by McJty** [comment]
And you get no cities in the world after that? I assume this is single player right?

**Comment by McJty** [comment]
Also I forgot but 1.16.5 still has a bug where you HAVE to close Minecraft after changing settings.
i.e. to get a fresh world. Exit minecraft, then create the world with Lost Cities enabled

**Comment by rashie12** [comment]
No cities in the world. And yes, this is single player

**Comment by McJty** [comment]
Try exiting Minecraft and creating a world then

**Comment by rashie12** [comment]
> Also I forgot but 1.16.5 still has a bug where you HAVE to close Minecraft after changing settings. i.e. to get a fresh world. Exit minecraft, then create the world with Lost Cities enabled

Ohhh, let me see if it works

**Comment by rashie12** [comment]
So I have to create the world, exit the world, close mimecraft and log back in again?

**Comment by McJty** [comment]
No no
1. Exit Minecraft
2. Start Minecraft again
3. Create a new world configured for Lost Cities
4. Play it

**Comment by rashie12** [comment]
Ahh, you'll have to give me details on step 3. I'm not sure about that.

**Comment by McJty** [comment]
You said you did that before? i.e. just create world, hit the 'lost cities' button top right, then select a profile with the button 'top left'. The important thing is that you have a cleanly started Minecraft

**Comment by rashie12** [comment]
It works! Thanks you!
