### ISSUE TITLE
Suggestion: as Dimension

### ISSUE THREAD

**Issue by Chromayx** [McJty/LostCities#489]
can we have the Lost Cities as Dimension for 1.12.2?
Portal frame made out of Iron Bloacks 4x5 - 21x21, trigger item is one piece Redstone

**Comment by McJty** [comment]
Lost Cities already IS a dimension on 1.12.2. You can go to it using a bed that's surrounded by six skulls and is put on top of two diamond blocks

**Comment by Chromayx** [comment]
but how to return?

**Comment by McJty** [comment]
Either with the help of another mod or else you bring two diamond blocks, a bed and 6 skulls with you

**Comment by Chromayx** [comment]
ok got it ty
