### ISSUE TITLE
1.19.2 Strange constant crash during world generation.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [McJty/LostCities#491]
[crash-2022-10-07_08.51.52-server.txt](https://github.com/McJtyMods/LostCities/files/9734487/crash-2022-10-07_08.51.52-server.txt)

I do not have the one probe by the way.

[latest.log](https://github.com/McJtyMods/LostCities/files/9734492/latest.log)

Version it crashes on.

lostcities-1.19-6.0.6.jar

it does not have this issue with this version

lostcities-1.19-6.0.5.jar

**Comment by McJty** [comment]
I will fix this in a moment

**Comment by McJty** [comment]
Fixed
