### ISSUE TITLE
Not compatible with Journeymap mod

### ISSUE THREAD

**Issue by ghost** [McJty/LostCities#492]
When I try loading a world with [Journeymap](https://www.curseforge.com/minecraft/mc-mods/journeymap) loaded, the following error appears:
![image](https://user-images.githubusercontent.com/8857825/194705881-635389c0-6c71-4272-a021-b4507d92395f.png)
### Mods:
![image](https://user-images.githubusercontent.com/8857825/194705933-b304fe5b-df4f-4438-805f-3867c97e8fe5.png)
### Minecraft version is 1.19.2

**Comment by ghost** [comment]
Logs: [latest.log](https://github.com/McJtyMods/LostCities/files/9739142/latest.log)

**Comment by McJty** [comment]
Did you also report to them? Also there is no crash in that log

**Comment by ghost** [comment]
> Did you also report to them? 

No. I will try to report to them either.
> Also there is no crash in that log

Hm. I will try to gather as many logs as I can then. Btw, feel free to ask me about any data or evidence of this problem. In particular, I could record a video of a crash.

**Comment by ghost** [comment]
More logs:
[debug.log](https://github.com/McJtyMods/LostCities/files/9739566/debug.log)
[latest.log](https://github.com/McJtyMods/LostCities/files/9739567/latest.log)

**Comment by McJty** [comment]
What was the solution?
