### ISSUE TITLE
[1.18-5.3.11] Floating ferns/grass and vines issue with Terralith/Biome mods

### ISSUE THREAD

**Issue by BadIsMyUsername** [McJty/LostCities#493]
Forge Modloader Version: 40.1.80
Terralith Version: 1.18.2 - 2.2.2
Biome's O Plenty Version: 1.18.2-16.0.0.109

Lost Cities Version: 1.18-5.3.11
Profile settings: largecities

To reproduce:
Download Lost Cities, find a generated city that lies within the bounds of a new biome, observe oddly behaving grass and vines.

![2022-10-12_14 58 50](https://user-images.githubusercontent.com/62829927/195275470-1dd107d0-3541-428a-8f12-830bf6700ce0.png)
Terralith

![2022-10-12_15 26 58](https://user-images.githubusercontent.com/62829927/195277816-8e82f4e9-08c9-4b08-a4a6-ad1b24196e33.png)
Biomes O' Plenty

**Comment by McJty** [comment]
Will be fixed next release
