### ISSUE TITLE
Server Crashes on Start; Failure message: LostCities (lostcities) encountered an error during the common_setup event phase java.lang.IllegalStateException: Not a JSON Object: true

### ISSUE THREAD

**Issue by unluckyClone** [McJty/LostCities#495]
I dont know of anything that changed and might have caused this error.
tested a few things: reinstalled, repaired, tried older modpack-versions. 
And since I dont really know what I´m even doing I´ll just attatch all the files I got.

[crash-2022-10-24_19.15.55-fml.txt](https://github.com/McJtyMods/LostCities/files/9854229/crash-2022-10-24_19.15.55-fml.txt)
[crash-2022-10-24_18.57.56-server.txt](https://github.com/McJtyMods/LostCities/files/9854251/crash-2022-10-24_18.57.56-server.txt)
[latest.log](https://github.com/McJtyMods/LostCities/files/9854253/latest.log)
 
 I hope this is the right place for this problem and I´m sorry if thats not the case.

**Comment by McJty** [comment]
yes, this is caused by changing some type of config somewhere. Hard to say though if you don't know what you changed. Try to revert to defaults perhaps?

**Comment by unluckyClone** [comment]
i changed some values in other mods, but cant remember even touching lost cities.
And I just got back from the gym and everythings running like nothing ever happend, I just hope it´ll stay like this ^^
Thank you for the fast answer.
