### ISSUE TITLE
Server Crashes when Generating rarecities profile

### ISSUE THREAD

**Issue by TheStarlessBandit** [McJty/LostCities#496]
Hey,
My Server crashes when i try to generate Cities with the profile of "rarecities" and i couldn't figure out why.
Am i doing something wrong?

Mod version: 1.12.2
Generator Settings: {"profile":"rarecities"}
Level type: lostcities_bop
Crash log: https://pastebin.com/KSg2CGeN

Note: it works when i leave the Generator Settings blank, but i want cities to be rare.

**Comment by McJty** [comment]
That appears to be caused by some modifications to the rarecities profile. What did you change there?

**Comment by TheStarlessBandit** [comment]
i don't think i have touched it at all.
here is the config: https://pastebin.com/Tn4p4HPi
