### ISSUE TITLE
 in 1.16.5 theres a bug with the cobblestone wall that looks disgusting 

### ISSUE THREAD

**Issue by demifried** [McJty/LostCities#506]
cobblestone wall generates horrobly and it looks really disgusting and really stressful to watch

and  every cobblestone wall generated like this by lost citys 

if you can fix it please tell me the way of fixing it by my self

![i hate this bug](https://user-images.githubusercontent.com/100454103/203631266-e5fb0feb-7416-4d4e-a627-0d819e1836ca.png)

**Comment by strubium** [comment]
WTF

I don't even know what is happening here, but if I recall correctly, in 1.16 Mojang changed walls to merge perfectly (see [this](https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.reddit.com%2Fr%2FMinecraft%2Fcomments%2Fezdkm6%2F116_vs_115%2F&psig=AOvVaw1LgLA5sPPK-oWVSI2Xp5hJ&ust=1680101131712000&source=images&cd=vfe&ved=2ahUKEwjirLTK7v79AhU6Et4AHU5IDxEQr4kDegQIARBu)) Maybe the lost cities doesn't know how to place them and is attempting to place them using the 1.15 way. 

It feels far fetched, but possible

**Comment by McJty** [comment]
It is a bug in Lost Cities. But it will not get fixed because I no longer work on 1.16.5

**Comment by strubium** [comment]
> It is a bug in Lost Cities. But it will not get fixed because I no longer work on 1.16.5

What is causing the bug?

**Comment by McJty** [comment]
Just using a wrong way to place the wall blocks. i.e. I'm just setting the wall there but not triggering a block update to cause it be correct

**Comment by strubium** [comment]
Yoo! I was actually right for once! Thank you! 

Should I attempt to fix this bug?

**Comment by McJty** [comment]
The bug is actually fixed in 1.18 and later. However I will not release new versions for 1.16.5 as I no longer have a dev environment ready for it
