### ISSUE TITLE
Singleplayer world crashes while loading chunks

### ISSUE THREAD

**Issue by nomnivore1** [McJty/LostCities#507]
Singleplayer worlds sometimes crash while generating terrain. usually happens after the world is loaded while new terrain is being generated. Experimented with a few different LostCities configurations, and the crashes seemed to happen specifically when using the perlin noise option for city rarity with custom settings for building height, but sample size is too small to say for sure. other mods present, listed in crash report. Tried with the other mods removed, continued to get crashes. 

crash report here: https://pastebin.com/PkWAqAaN

edit: another crash report: https://pastebin.com/S59vGiaZ

**Comment by McJty** [comment]
What version and what profile are you using? Did you do custom modifications?

**Comment by nomnivore1** [comment]
Lost Cities 1.18-5.3.12, crashes occurred using multiple city generation profiles with custom changes, I think Large Cities and Rare Cities. I did try adding [this mod](https://www.curseforge.com/minecraft/mc-mods/feature-nbt-deadlock-be-gone) which fixes crashes caused when world generation tries to place a structure over a block entity, and the world I generated using that didn't crash, but the crashes were sporadic enough that this could have just been a fluke. 

It seems like something in the world generation is causing the crashes, because they either happened while generating new chunks or while generating a new world. I think they are sporadic because you have to generate a chunk that will crash the world, so you may be able to start a world and explore for a while without a crash. But I don't know enough about how Minecraft works to be sure.

**Comment by McJty** [comment]
The changes are most likely caused by the changes you did to your profile. Can you tell me exactly what you changed?

**Comment by nomnivore1** [comment]
Nothing crazy. adjustments to the perlin noise scale, city size and frequency, and building height.

**Comment by McJty** [comment]
Yep, that would do it. Building height is the main factor. If that's too high you can get overflow which causes exactly this problem

**Comment by nomnivore1** [comment]
how high is too high? I think the highest I set it was 12 stories. is that really high enough to crash the game?

**Comment by McJty** [comment]
Show me what you changed. It can be a combination of things

**Comment by nomnivore1** [comment]
I don't have a record of all the things I changed in the world generation menu, sorry. I do have one of the world files that was crashing, but I can't find the city generation profile in it.

**Comment by McJty** [comment]
It should be in server-config inside your world

**Comment by nomnivore1** [comment]
the only LostCities file there is lostcities-server.toml and it contains the following text:


>#General settings
>[profiles]
>	#Block to put underneath a bed so that it qualifies as a teleporter bed
>	specialBedBlock = "minecraft:diamond_block"
>	selectedProfile = "customized"
>	selectedCustomJson = ""

**Comment by McJty** [comment]
hmm hard to say then. Not sure how to help you with this. I know it is caused by wrong settings because this has happened in the past with other people but without knowing what you changed there is not much I can do I'm afraid

**Comment by nomnivore1** [comment]
okay, thanks for your time anyway. I'll look for some settings that are stable with the pack I'm putting together, and I'll keep that "deadlock-be-gone" mod around just in case.

**Comment by McJty** [comment]
I just released a new version of Lost Cities where this crash should no longer happen and the maximum number of floors and cellars has been raised considerably. If a building goes beyond build limits it will now automatically adjust
