### ISSUE TITLE
1.18 freeze due to Invalid name given to minecraft:root getOrThrow

### ISSUE THREAD

**Issue by reenigne1** [McJty/LostCities#509]
playing with all the mods 7 
MC version: 1.18.2
Forge: 40.1.86
I create a new world and play for a random amount of time, I explore LostCities cities that were generated on world creation no problem, but at some point, during exploration and generating new chunks the game freezes indefinitely. I play with rare cities
[crash-2022-12-11_21.26.36-server.txt](https://github.com/McJtyMods/LostCities/files/10204144/crash-2022-12-11_21.26.36-server.txt)

**Comment by McJty** [comment]
Is this with a custom profile? How did you configure Lost Cities?

**Comment by reenigne1** [comment]
it's a custom profile based off of the rarecities profile. I shrink the cities so they are between 32 and 48 blocks radius, decrease both fountains and parks to 0.001, I generally set buildings to 0.7 but I use up to 0.9, and buildings 2X2 I set somewhere from 0.3 to 0.5, floors I boost from between 12 to 30 floors above ground and between 3 to 7 cellars below ground, chance of small and large explosions I add an additional 0, so explosions are 0.0002, and min/exp are 0.003, I don't recall changing anything in the transport section on this map, but I've set distance mask to 63 in other maps (it doesn't seem to change anything), all other settings remain original to their rarecities settings.
converted the config file to .txt, see attached:
[lostcities-server.txt](https://github.com/McJtyMods/LostCities/files/10204607/lostcities-server.txt)

also, forgot to mention, this is all in the overworld.

**Comment by McJty** [comment]
yes this problem only happens with custom profiles. Your floors are waaay too high. That's what is causing an overflow and that causes this problem

**Comment by reenigne1** [comment]
Ah, drat. What should the max floors be to prevent this?
if I try and make 50 floors it automatically corrects to 30, so I though 30 was the max.

**Comment by McJty** [comment]
It's a bit complicated. The max floors that are possible depends also on the variation of the terrain. I need to add in a better safety check for this because this is a very common problem

**Comment by reenigne1** [comment]
Ah, ok, I'll try for 20 floors and hopefully that'll work. Thanks for your help!

**Comment by McJty** [comment]
I'm going to try to implement a better solution for this

**Comment by McJty** [comment]
I just released a new version of Lost Cities where this crash should no longer happen and the maximum number of floors and cellars has been raised considerably. If a building goes beyond build limits it will now automatically adjust

**Comment by reenigne1** [comment]
hahahaha, these cities are even more glorious! Great update!
