### ISSUE TITLE
ATM3 Server World Type: lostcities_bop - client cannot connect to server.

### ISSUE THREAD

**Issue by Sonicx32** [McJty/LostCities#51]
I am trying to set up a ATM3 Server on my PC. It's got an i7-6700k 32gb DDR4 RAM, GTX980 TI, so it's more than powerful enough for this sort of thing. I've opened plenty of FTB servers in the past on it. My problem though seems to be with attempting to open an ATM3 server with a lostcities_bop world type. The world generates and the server seems to open. (At the very least it's not crashing) But when I try to connect via localhost for testing I either get the "Logging In..." message which hangs indefinitely until I force close the client or after 3-5 min of loading it just fails to connect and gives me the typical Connection Timed Out message. Now, I have been able to open a normal lost cities world type and connect to the server with no problems. But as soon as I change the world to a lostcities_bop world type I can no longer connect.
I should note that I am using the exact same configuration files for Lost cities on my client with the exact same seed in a single player world and it works fine. As soon as these same settings / config files are used to create an identical world with the same seed on the server, my client can no longer connect. I am at a loss for what could be causing this or how to fix it. Let me know if you need anything  else other than the files I have pasted below.

Here are all the lost cities and ATM3 server configuration files and setting files I have changed from the default.

[profile_server.txt](https://github.com/McJty/LostCities/files/1403525/profile_server.txt)
[server.txt](https://github.com/McJty/LostCities/files/1403528/server.txt)
[settings.txt](https://github.com/McJty/LostCities/files/1403530/settings.txt)

And here are some server logs which might help for troubleshooting.

[fml-junk-earlystartup.log](https://github.com/McJty/LostCities/files/1403536/fml-junk-earlystartup.log)
[fml-server-latest.log](https://github.com/McJty/LostCities/files/1403539/fml-server-latest.log)

**Comment by McJty** [comment]
Sorry for the late reply but I haven't had a chance to look at this yet.

**Comment by McJty** [comment]
Hmm, did you try increasing the -Xms2G?

JAVA_ARGS=-server -d64 -Xms2G -XX:+ExplicitGCInvokesConcurrent -XX:+ExplicitGCInvokesConcurrentAndUnloadsClasses -XX:+UseConcMarkSweepGC -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=50 -XX:UseSSE=3;

**Comment by Sonicx32** [comment]
Wow. After days of troubleshooting in the configuration files, it was that simple. raised the max to 12G and the min to 4G in the settings.cfg file. Connected with no problems after that. Thank you!
