### ISSUE TITLE
I get error code -1 when trying to join a world

### ISSUE THREAD

**Issue by MostLikelyHuman** [McJty/LostCities#511]
when i try to open or create a world my game crashes gives error code -1 and says:

The game crashed whilst exception in server tick loop
Error: java.lang.NoClassDefFoundError: mcjty/theoneprobe/config/Config

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 12/21/22, 11:51 AM
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: mcjty/theoneprobe/config/Config
	at mcjty.lostcities.setup.ForgeEventHandlers.onPlayerLoggedIn(ForgeEventHandlers.java:89) ~[lostcities-1.18-5.3.10.jar%2378!/:1.18-5.3.10] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_359_ForgeEventHandlers_onPlayerLoggedIn_PlayerLoggedInEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.firePlayerLoggedIn(ForgeEventFactory.java:819) ~[forge-1.18.2-40.1.51-universal.jar%23101!/:?] {re:classloading}
	at net.minecraft.server.players.PlayerList.m_11261_(PlayerList.java:238) ~[client-1.18.2-20220404.173914-srg.jar%2396!/:?] {re:classloading}
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_143699_(ServerLoginPacketListenerImpl.java:138) ~[client-1.18.2-20220404.173914-srg.jar%2396!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10055_(ServerLoginPacketListenerImpl.java:125) ~[client-1.18.2-20220404.173914-srg.jar%2396!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10050_(ServerLoginPacketListenerImpl.java:69) ~[client-1.18.2-20220404.173914-srg.jar%2396!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.network.Connection.m_129483_(Connection.java:241) ~[client-1.18.2-20220404.173914-srg.jar%2396!/:?] {re:classloading}
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142) ~[client-1.18.2-20220404.173914-srg.jar%2396!/:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:916) ~[client-1.18.2-20220404.173914-srg.jar%2396!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[client-1.18.2-20220404.173914-srg.jar%2396!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:118) ~[client-1.18.2-20220404.173914-srg.jar%2396!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[client-1.18.2-20220404.173914-srg.jar%2396!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%2396!/:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}
Caused by: java.lang.ClassNotFoundException: mcjty.theoneprobe.config.Config
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:134) ~[securejarhandler-1.0.3.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:134) ~[securejarhandler-1.0.3.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	... 18 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 677467120 bytes (646 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 9 6900HS with Radeon Graphics        
	Identifier: AuthenticAMD Family 25 Model 68 Stepping 1
	Microarchitecture: Zen 3
	Frequency (GHz): 3.29
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: AMD Radeon RX 6700S
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x73ef
	Graphics card #0 versionInfo: DriverVersion=31.0.12024.2005
	Graphics card #1 name: AMD Radeon(TM) Graphics
	Graphics card #1 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #1 VRAM (MB): 512.00
	Graphics card #1 deviceId: 0x1681
	Graphics card #1 versionInfo: DriverVersion=31.0.12024.2005
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 4.80
	Memory slot #0 type: Unknown
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 4.80
	Memory slot #1 type: Unknown
	Virtual memory max (MB): 34028.45
	Virtual memory used (MB): 27314.66
	Swap memory total (MB): 18432.00
	Swap memory used (MB): 1530.52
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['Doomasaurus_Rex'/458, l='ServerLevel[MOOOOD 4]', x=5.50, y=72.00, z=1.50]]
	Data Packs: vanilla, mod:tenshilib, mod:grapplemod (incompatible), mod:horsecombatcontrols (incompatible), mod:voicechat (incompatible), mod:bedbenefits (incompatible), mod:terrablender (incompatible), mod:swingthroughgrass (incompatible), mod:physicsmod (incompatible), mod:toolbelt, mod:torchslabmod (incompatible), mod:cgm, mod:biomesoplenty (incompatible), mod:connectiblechains, mod:shouldersurfing (incompatible), mod:simple_weapons, mod:playeranimator, mod:incontrol (incompatible), mod:callablehorses (incompatible), mod:fallingleaves (incompatible), mod:collective, mod:mobsunscreen (incompatible), mod:parcool (incompatible), mod:sereneseasons (incompatible), mod:configured (incompatible), mod:toughasnails (incompatible), mod:doubleslabs (incompatible), mod:lostcities (incompatible), mod:botanypots (incompatible), mod:bookshelf, mod:badmobs, mod:farsightedmobs (incompatible), mod:starterkit, mod:architectury (incompatible), mod:immersivemc (incompatible), mod:framework (incompatible), mod:firstaid (incompatible), mod:cloth_config (incompatible), mod:bettercombat, mod:forge, mod:realistictorches, mod:dummmmmmy (incompatible), mod:improvedmobs
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	OptiFine Version: OptiFine_1.18.2_HD_U_H7
	OptiFine Build: 20220410-185216
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: DrDestens+MinecraftShaders+v1.5.7.zip
	OpenGlVersion: 3.2.0 Core Profile Context 22.20.24.02.220906
	OpenGlRenderer: AMD Radeon(TM) Graphics
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 16
	ModLauncher: 9.1.3+9.1.3+main.9b69c82a
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 slf4jfixer PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 OptiFine TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.18.2-20220404.173914-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		tenshilib-1.18.2-1.6.14-forge.jar                 |TenshiLib                     |tenshilib                     |1.18.2-1.6.14       |DONE      |Manifest: NOSIGNATURE
		grappling_hook_mod-1.18.2-v13.jar                 |Grappling Hook Mod            |grapplemod                    |1.18.2-v13          |DONE      |Manifest: NOSIGNATURE
		horsecombatcontrols-1.18.2-1.0.1.jar              |Horse Combat Controls         |horsecombatcontrols           |1.18.2-1.0.1        |DONE      |Manifest: NOSIGNATURE
		voicechat-forge-1.18.2-2.3.23.jar                 |Simple Voice Chat             |voicechat                     |1.18.2-2.3.23       |DONE      |Manifest: NOSIGNATURE
		BedBenefits-Forge-1.18.2-6.0.2.jar                |BedBenefits                   |bedbenefits                   |6.0.2               |DONE      |Manifest: NOSIGNATURE
		TerraBlender-forge-1.18.2-1.2.0.126.jar           |TerraBlender                  |terrablender                  |1.2.0.126           |DONE      |Manifest: NOSIGNATURE
		swingthroughgrass-1.18.2-1.9.1.jar                |SwingThroughGrass             |swingthroughgrass             |1.18.2-1.9.1        |DONE      |Manifest: NOSIGNATURE
		physics-mod-2.9.4-mc-1.18.2-forge.jar             |Physics Mod                   |physicsmod                    |2.9.4               |DONE      |Manifest: NOSIGNATURE
		ToolBelt-1.18.2-1.18.9.jar                        |Tool Belt                     |toolbelt                      |1.18.9              |DONE      |Manifest: NOSIGNATURE
		torchslabmod-1.18.1_v1.7.5.jar                    |Torch Slab Mod                |torchslabmod                  |1.7.5               |DONE      |Manifest: NOSIGNATURE
		cgm-1.2.7-1.18.2.jar                              |MrCrayfish's Gun Mod          |cgm                           |1.2.7               |DONE      |Manifest: NOSIGNATURE
		BiomesOPlenty-1.18.2-16.0.0.109-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.18.2-16.0.0.109   |DONE      |Manifest: NOSIGNATURE
		Connectible+Chains-forge-1.18.2-2.1.1.jar         |Connectible Chains            |connectiblechains             |2.1.1               |DONE      |Manifest: NOSIGNATURE
		ShoulderSurfing-Forge-1.18.2-2.2.16.jar           |Shoulder Surfing              |shouldersurfing               |1.18.2-2.2.16       |DONE      |Manifest: NOSIGNATURE
		Simple+Weapons+1.1.4+-+1.18.2.jar                 |Simple Weapons                |simple_weapons                |1.1.4               |DONE      |Manifest: NOSIGNATURE
		player-animation-lib-forge-0.4.0+1.18.jar         |Player Animator               |playeranimator                |0.4.0+1.18          |DONE      |Manifest: NOSIGNATURE
		incontrol-1.18-6.1.1.jar                          |InControl                     |incontrol                     |1.18-6.1.1          |DONE      |Manifest: NOSIGNATURE
		callablehorses-1.18.2-1.2.2.5.jar                 |Callable Horses               |callablehorses                |1.2.2.5             |DONE      |Manifest: 8c:03:ac:7d:21:62:65:e2:83:91:f3:22:57:99:ed:75:78:1e:db:de:03:99:ef:53:3b:59:95:18:01:bc:84:a9
		Fallingleaves-1.18.2-1.3.2.jar                    |Falling Leaves                |fallingleaves                 |1.3.2               |DONE      |Manifest: NOSIGNATURE
		collective-1.18.2-5.45.jar                        |Collective                    |collective                    |5.45                |DONE      |Manifest: NOSIGNATURE
		mobsunscreen-1.18.1-3.0.4.jar                     |Mob Sunscreen                 |mobsunscreen                  |1.18.1-3.0.4        |DONE      |Manifest: NOSIGNATURE
		ParCool-1.18.2-2.0.0.3-R.jar                      |ParCool!                      |parcool                       |1.18.2-2.0.0.3-R    |DONE      |Manifest: NOSIGNATURE
		Serene+Seasons-1.18.2-7.0.0.13.jar                |Serene Seasons                |sereneseasons                 |1.18.2-7.0.0.13     |DONE      |Manifest: NOSIGNATURE
		configured-2.0.0-1.18.2.jar                       |Configured                    |configured                    |2.0.0               |DONE      |Manifest: NOSIGNATURE
		Tough+As+Nails-1.18.2-7.0.0.69.jar                |Tough As Nails                |toughasnails                  |1.18.2-7.0.0.69     |DONE      |Manifest: NOSIGNATURE
		DoubleSlabs-1.18-5.0.0.jar                        |Double Slabs                  |doubleslabs                   |5.0.0               |DONE      |Manifest: NOSIGNATURE
		lostcities-1.18-5.3.10.jar                        |LostCities                    |lostcities                    |1.18-5.3.10         |DONE      |Manifest: NOSIGNATURE
		BotanyPots-Forge-1.18.2-8.0.23.jar                |BotanyPots                    |botanypots                    |8.0.23              |DONE      |Manifest: NOSIGNATURE
		Bookshelf-Forge-1.18.2-13.2.50.jar                |Bookshelf                     |bookshelf                     |13.2.50             |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		BadMobs-1.18.2-13.01.jar                          |BadMobs                       |badmobs                       |13.01               |DONE      |Manifest: NOSIGNATURE
		farsightedmobs-forge-1.1-1.18.jar                 |Farsighted Mobs               |farsightedmobs                |1.1                 |DONE      |Manifest: NOSIGNATURE
		starterkit_1.18.2-4.1.jar                         |Starter Kit                   |starterkit                    |4.1                 |DONE      |Manifest: NOSIGNATURE
		architectury-4.9.84-forge.jar                     |Architectury                  |architectury                  |4.9.84              |DONE      |Manifest: NOSIGNATURE
		immersivemc-1.1.3-1.18.2-forge.jar                |ImmersiveMC                   |immersivemc                   |1.1.2               |DONE      |Manifest: NOSIGNATURE
		framework-0.2.4-1.18.2.jar                        |Framework                     |framework                     |0.2.4               |DONE      |Manifest: NOSIGNATURE
		firstaid-1.11.1.jar                               |First Aid                     |firstaid                      |1.11.1              |DONE      |Manifest: NOSIGNATURE
		cloth-config-6.4.90-forge.jar                     |Cloth Config v4 API           |cloth_config                  |6.4.90              |DONE      |Manifest: NOSIGNATURE
		bettercombat-forge-1.5.3+1.18.2.jar               |Better Combat                 |bettercombat                  |1.5.3+1.18.2        |DONE      |Manifest: NOSIGNATURE
		forge-1.18.2-40.1.51-universal.jar                |Forge                         |forge                         |40.1.51             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		RealisticTorches-1.18.2-3.1.5.jar                 |Realistic Torches             |realistictorches              |1.18.2-3.1.5        |DONE      |Manifest: NOSIGNATURE
		MmmMmmMmmMmm-1.18.2-1.5.2.jar                     |MmmMmmMmmMmm                  |dummmmmmy                     |1.18-1.5.2          |DONE      |Manifest: NOSIGNATURE
		improvedmobs-1.18.2-1.10.15-forge.jar             |Improved Mobs Mod             |improvedmobs                  |1.18.2-1.10.15      |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 254e5ac7-5211-4434-94fd-396ac334ae13
	FML: 40.1
	Forge: net.minecraftforge:40.1.51

**Comment by McJty** [comment]
I'll fix. You can temporarily fix this by adding TheOneProbe mod

**Comment by MostLikelyHuman** [comment]
if it this: https://www.curseforge.com/minecraft/mc-mods/the-one-probe, then that just looks like a waila-ish thing but ill try it when i have time

**Comment by McJty** [comment]
yes, it's a bit like waila, It's also one of my mods

**Comment by MostLikelyHuman** [comment]
OH THANKS SO MUCH IT WORKED! i am making a modpack-ish thing and lost cities was one i really wanted

**Comment by McJty** [comment]
Oh. Also why are you using an old version of Lost Cities? Update. That bug was fixed some time ago

**Comment by MostLikelyHuman** [comment]
a few of my mods need 1.18.2

**Comment by McJty** [comment]
yes, but you are using an old version of Lost Cities for 1.18.2. There is a more recent version for 1.18.2

**Comment by MostLikelyHuman** [comment]
oh... okay i did not notice
