### ISSUE TITLE
[Asset System Question] Can I use commands such as CreateBuilding or CreatePart to generate custom assets?

### ISSUE THREAD

**Issue by PeterBennyFooda** [McJty/LostCities#529]
Hi, I really like the new Asset DataPack System so far.

However, it seems that only buildings or parts in the standard asstets can be generated by commands. 
Currently, I need to override the standard citystyle with custom buildings and try to find them in the world.

It would be more convenient if I can use the commands to generate custom asstes immediately.

Version: lostcities-1.18-5.3.14

**Comment by McJty** [comment]
Hmm you can generate any part you want? Why do you think that isn't working?

**Comment by PeterBennyFooda** [comment]
For example, I have a custom asstes folder and the modid is "mycities" and there is a custom building "data\mycities\lostcities\buildings\mybuilding1.json".

If I type the command like "/lostcities createbuilding mybuilding1 1 8", I'll get the error message "Error trying to get resource lostcities:mybuilding1!".

if I change the command to "/lostcities createbuilding mycities:mybuilding1 1 8", I'll get the error message "expected whitespace to end one argument but found trailing data" right after I type the colon.

**Comment by McJty** [comment]
You need "  around mycities:mybuilding

**Comment by PeterBennyFooda** [comment]
Unfortunately it's still not working.
![image](https://user-images.githubusercontent.com/6175456/215990537-c49d6718-4a03-4025-aa77-989b356e19cb.png)

![image](https://user-images.githubusercontent.com/6175456/215990708-dc066aec-36a0-4ed1-bc6a-7cc1a22fd877.png)

**Comment by McJty** [comment]
Hmm weird. I'll have to check it out

**Comment by PeterBennyFooda** [comment]
Okay, thanks for your help!
I'll just override the standard citystyle to check my custom buildings for now.

**Comment by McJty** [comment]
I implemented proper command support now. Including tab completion like vanilla commands
