### ISSUE TITLE
[1.12.2] Random values don't work correctly in palettes and spawning of buildings

### ISSUE THREAD

**Issue by spaseksplorer** [McJty/LostCities#539]
In the profile config, setting the park or fountain spawn chance to 0.0 does not prevent parks or fountains from spawning. 
In palettes, the random values seem to have a underlying max sum they are trying to fill.  Setting the random weights for blocks too low (so the sum of the weights is less than 100) makes the structure spawn with empty spaces where blocks should be.  Setting the random weights for blocks to high (>100 each) prevents later items in the list from generating in the parts.

**Comment by McJty** [comment]
No idea about the fountains

yes indeed. That's how it is implemented for the random blocks

**Comment by spaseksplorer** [comment]
Why is the random weights for blocks implemented that way? Why is there an invisible, arbitrary limit to the value of weights I put in?

**Comment by McJty** [comment]
The limit is actually 128. So a weight of 32 means 1/4 chance.
This is done for efficiency reasons

**Comment by spaseksplorer** [comment]
Then how do the palettes that ship with the mod work? They have values of 8, 9, and 1000.

**Comment by McJty** [comment]
The 1000 basically means: all the rest. Because the mod automatically caps the maximum to 128. So it's an easy way of saying: 'if it's not one of the above then take this'

**Comment by spaseksplorer** [comment]
How does setting a limit improve efficiency? Is it possible to remove this limit?

**Comment by McJty** [comment]
It uses a lookup table internally with 128 values. So no, not possible to remove this limit

**Comment by McJty** [comment]
Also why would you want to remove this limit?

**Comment by spaseksplorer** [comment]
To have finer control over the random weights. So it can actually function like a true weighted list.

**Comment by McJty** [comment]
ok, but it's not possible. Also you asked for 1.12.2 and I no longer work on 1.12.2 (or 1.16.5)

**Comment by spaseksplorer** [comment]
Why is it not possible? Could you add a comment to the docs describing this limit then?

**Comment by McJty** [comment]
It's not possible because it would require more memory

**Comment by spaseksplorer** [comment]
https://github.com/McJtyMods/LostCities/blob/e89000238a8095cba8a739fc3b9e595d854a1346/src/main/java/mcjty/lostcities/dimensions/world/lost/BuildingInfo.java#L738
Line 738 might need to go where line 729 is to fix the parks still spawning issue.
