### ISSUE TITLE
[1.12.2] LostCities Chosing Wasteland still has pools of water and streams

### ISSUE THREAD

**Issue by Morpheus1101** [McJty/LostCities#54]
When chosing the LostCities Wasteland configuration, fountains of water as well as various pools still generate.  Dropping this here as per our conversation on Discord.

**Comment by Morpheus1101** [comment]
Updated an re-configured using newly generated config files for this and while fountains an the likes are gone, im still getting pools of water.
![2017-11-07_15 52 12](https://user-images.githubusercontent.com/10524952/32479092-ec7f0e0a-c3d3-11e7-9e39-52c5cf9a053e.png)

Here is a copy of my wasteland config as it stands:


[profile_wasteland.txt](https://github.com/McJty/LostCities/files/1448850/profile_wasteland.txt)

**Comment by McJty** [comment]
That doesn't look like water?

**Comment by Morpheus1101** [comment]
Its a green color is thats what it appears as when shown in wasteland biome

**Comment by Morpheus1101** [comment]
https://puu.sh/ygE1y/4cd403d62b.mp4 is a small vid showing it done

**Comment by McJty** [comment]
I think these pools might be generated by Biomes O Plenty (biome decoration). That means I actually don't have control over this. Maybe this is something that can be configured at BoP's side?

**Comment by Morpheus1101** [comment]
i'll poke around an see what i can find

**Comment by Morpheus1101** [comment]
BOP side an its resolved, thanks for the assistance with this :)
