### ISSUE TITLE
[Question] Utilizing Custom Loot Tables from Datapacks in Lost Cities & An Additional Query

### ISSUE THREAD

**Issue by Untrustedlife** [McJty/LostCities#543]
Hey there! It's been ages since I last logged into my GitHub account (Im more of gitlab and bitbucket guy), but I could really use some help with chest loot tables in Lost Cities for version 1.19.2. I'm putting together a custom modpack and I'm wondering if there's a way to set up the loot tables so Lost Cities can use them whether it be configurable somewhere i'm not seeing in lost cities or what loot tables to overwrite.

Also, if you have any tips on how to get cities to generate in the Nether and the End, that would be super helpful, as it's a key part of my modpack. 

I've looked through the GitHub issues here and couldn't find any instances where someone asked this question or similar  and received a useful response or if they did get a useful response it looks like thats no longer how its done and **none** of the configs even resemble what we have now. Can anyone help me out here?

Thanks a bunch!

**Comment by McJty** [comment]
Check this tutorial:

https://www.youtube.com/watch?v=Ck9_yknPx4c&ab_channel=JorritTyberghein

And this example datapack:

https://github.com/McJty/LostCityAssets

**Comment by Untrustedlife** [comment]
Thanks! I plan to use datapack functionality to the greatest extent I can to create something like urbex.. I wan't to add things like apartment complexes and such, so that should be perfect.

**Comment by Untrustedlife** [comment]
Does that also cover the second question?

**Comment by McJty** [comment]
Ah sorry, missed the second question. It's not currently possible to generate cities in the nether and the end
