### ISSUE TITLE
[Feature Request] Prevent cities from generating with other mods structure

### ISSUE THREAD

**Issue by Kasualix** [McJty/LostCities#545]
[This](https://github.com/McJtyMods/LostCities/blob/d77249cc30599beaa4119db8ce71fb1e4ae6e0dd/src/main/java/mcjty/lostcities/worldgen/LostCityTerrainFeature.java#L280) only prevent cities from generating with village, but many other modded structures (maybe like idas) still get broken with them.

**Comment by McJty** [comment]
Unfortunately there is not much that I can do about that as far as I know

**Comment by Kasualix** [comment]
alright, thank you.
