### ISSUE TITLE
[1.18.2] Loot condition ignored when in a random palette/style

### ISSUE THREAD

**Issue by CaiganMythFang** [McJty/LostCities#548]
[Mod Version 5.3.1.7]

Working on a heavily customized Lost City setup, and have run into a few interesting issues.

The main issue I've run into is if I have a chest or other inventory block with a "loot" condition, in a palette that is randomized with other blocks, the inventory block will never generate loot.

I've tested this a bit, using the following in a buildnig Part file : 
[Edited section of building](https://i.imgur.com/V21TvM1.png)

`"palette": {
    "palette": [
      {
      "char": "2",
      "block": "cfm:birch_desk_cabinet[facing=north,waterlogged=false]",
      "loot": "minekov_desk_loot"
      },
      {
        "char": "F",
        "blocks": [
        {
          "random": 100,
          "block": "minecraft:chest[facing=south]",
            "loot": "minekov_desk_loot"
        },
        {
          "random": 1000,
          "block": "minecraft:stone"
        }
      ]
    }
  ]
  },`

The building looks like this, set up for testing this issue : 
![image](https://user-images.githubusercontent.com/16909199/231937331-6891c5e1-127d-45d9-ae65-844d2a2f67ff.png)

The cabinets are the only thing that will generate on 2, while F can either be a chest or stone. The chest and cabinet both have the same loot condition, the loot table inside the condition is confirmed valid using the /loot command

Generated multiple worlds and checked multiple instances of the building part : 

As expected, the Birch Cabinets in the top row had loot in them from the condition loot table.

The chests never had loot in them.

**Comment by McJty** [comment]
It might work (didn't test it) if you put the loot condition at the top level. I think Lost Cities will not try to generate loot for blocks that don't support it. If that doesn't work then I'm afraid it's not supported

**Comment by CaiganMythFang** [comment]
Do you mean top level as in, say, palette/common.json ? Tried that as well to the same effect unfortunately.

Is there a chance of this getting supported? Can understand if not, just means I have to rethink the system a bit before I get deeper into customizing the city generation =)

**Comment by McJty** [comment]
No, I mean like this:

```
"palette":{
   "palette":[
      {
         "char":"2",
         "block":"cfm:birch_desk_cabinet[facing=north,waterlogged=false]",
         "loot":"minekov_desk_loot"
      },
      {
         "char":"F",
         "loot":"minekov_desk_loot"
         "blocks":[
            {
               "random":100,
               "block":"minecraft:chest[facing=south]"
            },
            {
               "random":1000,
               "block":"minecraft:stone"
            }
         ]
      }
   ]
},

```

**Comment by CaiganMythFang** [comment]
Aha, did some testing and that works properly! Thank you!
