### ISSUE TITLE
Cities unable to generate (1.18, 1.19)

### ISSUE THREAD

**Issue by MaxineMaxie** [McJty/LostCities#564]
When I go to the LostCities customization screen everything is blanked out and when I try to load into the world it doesn't generate cities.
In 1.19 if I try to list parts it just says that the dimension is not supported.
![image](https://github.com/McJtyMods/LostCities/assets/94768673/5cec6031-70c6-4526-8a58-ab88146615c1)
![image](https://github.com/McJtyMods/LostCities/assets/94768673/bdd21cad-a889-4865-bdfe-25e569e93a71)
in 1.18 it can't get past world generation, so I guess this is an improvement.

**Comment by McJty** [comment]
Did you try clicking the button that says 'Disabled'?

**Comment by MaxineMaxie** [comment]
Oh, thanks for pointing that out. I don't know how I missed that.
