### ISSUE TITLE
Forge version incompatibility (1.19.2)

### ISSUE THREAD

**Issue by MaxineMaxie** [McJty/LostCities#565]
The mod requires forge 43.1.30 but the most recent version I can find on the forge website for 1.19.2 is 43.1.25
How does one play on 1.19.2?

**Comment by McJty** [comment]
I don't know where you get that from. The most recent Forge for 1.19.2 is 43.2.13

**Comment by McJty** [comment]
For reference:

https://files.minecraftforge.net/net/minecraftforge/forge/index_1.19.2.html
