### ISSUE TITLE
Directional block place support needed for highway [1.18.2]

### ISSUE THREAD

**Issue by woldioo** [McJty/LostCities#578]
![2023-09-16_14 02 09](https://github.com/McJtyMods/LostCities/assets/97209446/1f380fc7-0479-4f29-8c0a-ddc559daef48)

you can see the track are place correctly only bottom one
there wasn't a seperate setting for x axis and z axis highways unlike subway

**Comment by McJty** [comment]
Already implemented by adding the rotatable blocks to the lostcities:rotatable tag
