### ISSUE TITLE
(1.12.2) Can't find config file. Im trying to make a rare lost cities world thats amplified.

### ISSUE THREAD

**Issue by Honeydews** [McJty/LostCities#583]
I want to make an amplified world with rare lost cities in it, im ON 1.12.2 and not only can i not find the lostcities.cfg file as mentioned while creating the world, but I also cant find a way to make it amplified and rare cities, if there is any way to do this i NEED IT ive been looking fdor the past few weeks before resorting to submitting a request. pleeeease help. P.S im hosting the server through 1.12.2 essential mod. not through like the normal hosting thing people do. but with essential you literally can just host a singleplayer world so i dont think it efffects it.

**Comment by McJty** [comment]
Check the Lost Cities curseforge page. Instructions are there

**Comment by Honeydews** [comment]
i might be looking in the wrong place but i cant find the config file in the curseforge either, this is what im looking at: Documentation for 1.12
 

To use it server side you have to use 'lostcities' as the level-type (in server.properties).

 

Note that there is also a dimension (default ID 111) that you can travel too. This dimension can be disabled (useful if you want this for vanilla clients). But using this dimension you can keep the overworld normal and have The Lost Cities in a dimension. To go there (and back) the current way is to place a bed on top of two diamond blocks and surround it with 6 skulls. Then try to sleep in it.

 

If Biomes O Plenty is present there is also a Lost Cities (BoP) variant (or 'lostcities_bop' for servers) which will use Biomes O Plenty biomes.

 

To use a specific 'profile' (configuration profile) on a server you have to add this to your server-properties file:

 

generator-settings={"profile":"nodamage"}

 ----------------


This isnt a server thing, i just need to make a world amplified and also have lost cities, which hopefully is in the config file. the world can be singleplayer because essential juist lets you host any singleplayer world. sorry for me being annyoing me and my friends have been trying to crack this lol

**Comment by strubium** [comment]
> i might be looking in the wrong place but i cant find the config file in the curseforge either, this is what im looking at: Documentation for 1.12
> 
> To use it server side you have to use 'lostcities' as the level-type (in server.properties).
> 
> Note that there is also a dimension (default ID 111) that you can travel too. This dimension can be disabled (useful if you want this for vanilla clients). But using this dimension you can keep the overworld normal and have The Lost Cities in a dimension. To go there (and back) the current way is to place a bed on top of two diamond blocks and surround it with 6 skulls. Then try to sleep in it.
> 
> If Biomes O Plenty is present there is also a Lost Cities (BoP) variant (or 'lostcities_bop' for servers) which will use Biomes O Plenty biomes.
> 
> To use a specific 'profile' (configuration profile) on a server you have to add this to your server-properties file:
> 
> generator-settings={"profile":"nodamage"}
> 
> This isnt a server thing, i just need to make a world amplified and also have lost cities, which hopefully is in the config file. the world can be singleplayer because essential juist lets you host any singleplayer world. sorry for me being annyoing me and my friends have been trying to crack this lol

On CurseForge, you can press the three dots icon and click "Open Folder", then in File Explorer, click the folder labeled "config".

Config files are labeled with a .cfg file extension. But don't worry, you can edit them using notepad without any issues.

**Comment by McJty** [comment]
You need to do this with server.properties. That's how you can define what profile you  use
