### ISSUE TITLE
Reduce chance to find cities?

### ISSUE THREAD

**Issue by RipMe2Point0** [McJty/LostCities#584]
How in the world do I make these lostcities spawn less? I hate having so many in the entire world I just want to see them sometimes.

**Comment by McJty** [comment]
Use the rarecities profile

**Comment by RipMe2Point0** [comment]
What do I change? I see a bunch of low values that look nothing like what I see in game, in game it looks like cities are at 100% for spawn chance or generate chance.

**Comment by RipMe2Point0** [comment]
SOLVED: How to do it for servers is, edit the leveltype and generator settings.
Step 1. Go into serverproperties
Step 2. level-type=lostcities
Step 3. generator-settings={"profile":"rarecities"}
Step 4. Edit rarecities.cfg in config-lostcities-rarecities
Final step. Change CityChance to anything under or below 5 zeros, if you want plots of cities at least 5 zeros so like 0.000002. More zeros means less chance.
![image](https://github.com/McJtyMods/LostCities/assets/119878263/010b4a57-2d4c-49ba-ba8f-a15d398f1962)

![image](https://github.com/McJtyMods/LostCities/assets/119878263/5d883ab0-ffeb-40c2-a950-716dc3744604)

**Comment by pandalistics** [comment]
if i already have a world can i add it in for future chunks loaded?

**Comment by McJty** [comment]
No, you can't make changes like that
