### ISSUE TITLE
Wasteland and all presets are just default generations[1.19.2]

### ISSUE THREAD

**Issue by Skorpiorl** [McJty/LostCities#590]
Is no Wastelands, just default world. No Caverns and others specific generations. I am playing with BOP. 
It is a shame, because Wasteland at 1.12.2 was my favourite preset. It is very atmospheric and cool for post-apocalypse survival. But at 1.19.2 it just isn`t work. 

Tried to use Wastify mod, but can`t find config.

**Comment by McJty** [comment]
Wastify mod doesn't have a config. It just works

**Comment by Skorpiorl** [comment]
I still have water, ice and other... But why Lost Cities presets presets may not work for me? It isn`t mod conflicts, because i tested it at clear no mods version of game. And still no wastelands, no biospheres generation. It`s just like default.

**Comment by McJty** [comment]
Wasteland preset works in combation with wastify now

**Comment by McJty** [comment]
Biospheres should work if you enable them

**Comment by Skorpiorl** [comment]
![2023-11-09_12 32 51](https://github.com/McJtyMods/LostCities/assets/150322893/dc093902-d9c2-47b1-ab82-34013884995f)

This is screenshot of Lost Cities + Wastify with Wasteland preset. Water and snow still exist. Maybe i am stupid, man, but i don`t understand what is a problem.

**Comment by McJty** [comment]
yes, wastify doesn't remove that. It's really hard to do these things in modern minecraft

**Comment by Skorpiorl** [comment]
Oh... this is shame. But is still compatible with BOP biomes?

**Comment by McJty** [comment]
It should be. You will have to configure wastify for it though

**Comment by Skorpiorl** [comment]
How can i do it?
Thank you for your answers. Your mods is one of the best modern mods since golden classic.

**Comment by McJty** [comment]
See the wastify curseforge page. You basically need to make a datapack where you modify the json that is included in the base mod:

https://github.com/McJtyMods/Wastify/blob/1.19/src/main/resources/data/minecraft/dimension/overworld.json

**Comment by Skorpiorl** [comment]
Thank you again :3
