### ISSUE TITLE
Association of not involved world with the LostCities mod

### ISSUE THREAD

**Issue by kokurosa** [McJty/LostCities#594]
I will explain whole situation by steps
The issue is about that - one of my worlds that was generated before I installed LostCities(LC) for forge minecraft 1.18.2 (that new mod version from november 12) can't load without LC mod, and I really don't know why
The whole time when I had LC mod, I used TerraFirmaCraft(TFC:TNG) mod, that is a big mod that includes option to create type specific world for playing with that mod. Through all of lags and lack of RAM I did the thing, the world type of TFC with cities from LC was generated. And I played some time in it, got some resources, and wanted to take loot in the older world that was created ONLY with TFC:TNG mod, so I grab my items with structure blocks and copied that "generated" folder from TFC:TNG with LC world to TFC:TNG-only world, all was cool and my items was all in older world, I even forgot to pull of the LC mod from mod folder.
So, after all, I was about to get rid of LC mod, but every time without LC the game said to me that I need to restore some of configurations or load with "safe mode" which can not load
So here is the issue, I even deleted all the LostCities files from world folder, but that didn't worked, and I will load world with LC installed just to play with it unused

**Comment by McJty** [comment]
Sorry but this is confusing. Can you explain step by step what the problem is? I'm not getting it

**Comment by kokurosa** [comment]
> Sorry but this is confusing. Can you explain step by step what the problem is? I'm not getting it

no
if you can't get it, so it will be
not very important issue, but you can read it one more time
