### ISSUE TITLE
server issue

### ISSUE THREAD

**Issue by furrydemon1** [McJty/LostCities#596]
the server wont start keeps sayin missing registries

**Comment by McJty** [comment]
I need a LOT more information. What version? What's the exact error? How did you configure it? Logs?

**Comment by furrydemon1** [comment]
its 1 .18 . 2 i run a server it just said error missing registries i followed the curseforge instructions

30.11 04:27:33 [Server] WARN Missing Registries:
30.11 04:27:33 [Server] INFO lostcities:buildings
30.11 04:27:33 [Server] INFO lostcities:citystyles
30.11 04:27:33 [Server] INFO lostcities:conditions
30.11 04:27:33 [Server] INFO lostcities:multibuildings
30.11 04:27:33 [Server] INFO lostcities:palettes
30.11 04:27:33 [Server] INFO lostcities:parts
30.11 04:27:33 [Server] INFO lostcities:predefinedcites
30.11 04:27:33 [Server] INFO lostcities:predefinedspheres
30.11 04:27:33 [Server] INFO lostcities:scattered
30.11 04:27:33 [Server] INFO lostcities:styles
30.11 04:27:33 [Server] INFO lostcities:variants
30.11 04:27:33 [Server] INFO lostcities:worldstyles

**Comment by McJty** [comment]
Can you give me the full server log?

**Comment by furrydemon1** [comment]
[latest.log](https://github.com/McJtyMods/LostCities/files/13508401/latest.log)

**Comment by McJty** [comment]
I see this:

[30Nov2023 04:40:49.157] [main/WARN] [net.minecraft.server.MinecraftServer/]: Missing data pack mod:lostcities

There appears to be a problem with the Lost Cities mod or a datapack related to Lost Cities. Can you describe your setup a bit better? Do you have custom lost city datapacks?

**Comment by furrydemon1** [comment]
the datapack folder is empty

**Comment by McJty** [comment]
What about the mods folder? What is there?

**Comment by furrydemon1** [comment]
![image](https://github.com/McJtyMods/LostCities/assets/33299492/9b851d07-da86-44ca-a47c-c34e07007a4c)

**Comment by McJty** [comment]
I don't see lost cities in there?

**Comment by McJty** [comment]
Without Lost Cities itself this mod can obviously not work.
Also it sounds as if you copied the world. You should not do that. Follow the instructions
