### ISSUE TITLE
The mod crashes when I launch the game

### ISSUE THREAD

**Issue by MrFantastico1** [McJty/LostCities#604]
![screenshot](https://github.com/McJtyMods/LostCities/assets/157731991/b7b9c316-f8e0-4baf-b035-a8aeb28cd6dd)

I use forge 36.2.41 for minecraft 1.16.5

**Comment by McJty** [comment]
Remove the lost cities config files. Known problem

**Comment by MrFantastico1** [comment]
where i can delete the config files from

**Comment by McJty** [comment]
From the usual config folder in your minecraft instance
