### ISSUE TITLE
1.20.7.1.0 + 1.20.7.1.1 cause crashes with Noisium run through Sinytra Connector - "NoiseChunkGeneratorMixin from mod noisium cannot reduce visibiliy of PUBLIC target method"

### ISSUE THREAD

**Issue by StardustPassingBy** [McJty/LostCities#605]
Was experiencing crashes trying to add Noisium to my modpack, narrowed it down to just the Lost Cities, which I had recently updated. 1.20.7.0.4 works fine with Noisium, both alone and alongside my modpack, causing no crashes, but the two newer versions cause a crash at startup. Here is a log with only Sinytra Connector + Connector Extras, The Lost Cities, and Noisium enabled:

[latest.log](https://github.com/McJtyMods/LostCities/files/14219753/latest.log)

**Comment by McJty** [comment]
Yes, their bug. They shouldn't reduce visibility. Report to them
