### ISSUE TITLE
[1.20.1] Sphere World Void Chunk Structures

### ISSUE THREAD

**Issue by deepslater** [McJty/LostCities#607]
Environment: Windows 10, Forge version 47
Lost Worlds 0.0.1, Lost Cities 7.1.1

When using Lost Cities with Lost Worlds, structures in Frozen Oceans generate - including Shipwrecks and Icebergs. Other biomes unchecked.

Ruined portals also generate.

World file attached, screenshot attached.
[Void Test 1.zip](https://github.com/McJtyMods/LostCities/files/14331967/Void.Test.1.zip)
![image](https://github.com/McJtyMods/LostCities/assets/13291901/5df85693-d152-4dee-b653-41b44ece0ff8)

**Comment by ProudNitro** [comment]
Sorry, meant to submit to Lost Worlds, not cities.

**Comment by deepslater** [comment]
Please permanently delete.

Meant to submit as issue to Lost Worlds.
