### ISSUE TITLE
Lost Cities causing server crashes during new world generation (Forge 1.18.2, v40.2.4)

### ISSUE THREAD

**Issue by FleshNMetal** [McJty/LostCities#615]
https://pastebin.com/D0C5A86f

Password (if prompted): 12345

Basically, this is a new forge server I am attempting to play the mod pack DeceasedCraft (version 5.3.3) on a new 1.18.2 Forge Server. The server is fine until it runs into the world generation, where apparently it has trouble finding a certain resource for the mod, and then it spirals downward from there. Any help would be appreciated.

I have already tried posting this to the Forge community and attempted both of their solutions, hose being to remove the Open Parties and Claims mod and to try and use older version of the mod, both of which result in the same crash report.

**Comment by TqLxQuanZ** [comment]
You didn't install the modpack properly, how did you install the modpack? Did you use any launcher to install? You're missing a lot of other folder files to run the modpack.

**Comment by TqLxQuanZ** [comment]
If it's for the server, did you EXACTLY make sure every folder from the Server Pack is inside your server?

**Comment by FleshNMetal** [comment]
Apologies for wasting your time, all I had to do was transfer the kubejs folder into the server, as I falsely assumed it would be created upon world generation. Thank you.
