### ISSUE TITLE
Mod is literally unplayable.

### ISSUE THREAD

**Issue by AngelOfCreation** [McJty/LostCities#616]
I have no idea why but any time I try to play with this mod it just cripples my game. As soon as I start up a new world, I get intense server lag. It takes me like 30 seconds to switch my gamemode. Can't drop items. Can't interact with blocks. It's awful. I can't generate new chunks either after the initial generation. I just stand there waiting for the chunk adjacent to me to generate but it doesn't work.[](url)
[2024-04-16-6.log](https://github.com/McJtyMods/LostCities/files/15004245/2024-04-16-6.log)

Mods installed:
https://gyazo.com/a1e9cbb3edd2a8609677d199f4d4d7d7
https://gyazo.com/b42fdd836ae3983b9c917bbc5cb8d36c
https://gyazo.com/a12d08c04505e034a4e3eccc74c9bf11

Specs:
Intel i7 9700K
32 GB RAM
RTX 3080Ti
Windows 10 Enterprise

**Comment by McJty** [comment]
Could be a mod conflict. Is Lost Cities also slow on your computer without any of those other mods?

**Comment by AngelOfCreation** [comment]
It's much better by itself, still a slight delay tho. But its like a second or two rather than 30.

**Comment by McJty** [comment]
Yes, that points to some kind of mod conflict. If you feel up to it you could try to find out which mod is causing it

**Comment by AngelOfCreation** [comment]
That's what I'm doing atm, I'll keep you updated.

**Comment by AngelOfCreation** [comment]
Ok, I've figured it out. The problem is BetterChunkLoading ironically.

https://www.curseforge.com/minecraft/mc-mods/better-chunk-loading-forge-fabric

When playing with this mod, it makes chunks impossible to load with any speed. It also prevents the player from closing the game without force quitting via task manager, as the game freezes when saving to the main menu,

**Comment by McJty** [comment]
Glad that you found it!
