### ISSUE TITLE
1.16.5-36.2.42 JSON crash.

### ISSUE THREAD

**Issue by DetectivWolf** [McJty/LostCities#618]
So, I got an issue when I open the game, in Forge 1.16.5-36.2.42.
It says: LostCities (lostcities) encountered an error during the commom_setup event phase
            java.lang.IllegalStateException: Not a JSON Object: true

Can you help me?

**Comment by McJty** [comment]
Known bug and already reported a million times. Solution: remove the lost cities config files

**Comment by DetectivWolf** [comment]
> Known bug and already reported a million times. Solution: remove the lost cities config files

Thanks.
