### ISSUE TITLE
Mod prevents ocean monuments from generating

### ISSUE THREAD

**Issue by Ihatemakingpasswords** [McJty/LostCities#623]
the issue is as simple as the title when using lost cities ive traveled over 10k blocks in each direction and no ocean monuments

**Comment by McJty** [comment]
What version please? Also I have seen underwater monuments in lost cities worlds

**Comment by Ihatemakingpasswords** [comment]
its the most recent version not sure what it is exactly but alright if you have ima take your word for it and keep looking just been 3 days of straight flying with night vision unable to see them anywhere

**Comment by McJty** [comment]
I mean what Minecraft version. Also always specify exact numbers

**Comment by Ihatemakingpasswords** [comment]
its version 2.25.4-1.10.2 that's what the launcher says in the bottom left hand corner

**Comment by McJty** [comment]
That's the version of the launcher I think. What version of Minecraft?

**Comment by Ihatemakingpasswords** [comment]
> That's the version of the launcher I think. What version of Minecraft?

oh yes your right my bad 1.20.1 in the main menu bottom left:)

**Comment by Ihatemakingpasswords** [comment]
ehhhhhhh i found one boys!
