### ISSUE TITLE
[1.19.2] The Lost Cities Crash when creating new world

### ISSUE THREAD

**Issue by Periam** [McJty/LostCities#624]
Latest lost cities version crashed the game when creating new world
Minecraft 1.19.2
Forge 43.4.0
lostcities-1.19-6.0.28.jar

[crash-2024-06-13_09.57.34-server.txt](https://github.com/user-attachments/files/15820820/crash-2024-06-13_09.57.34-server.txt)

**Comment by McJty** [comment]
I'll check it out. Thanks for reporting

**Comment by RearMisser** [comment]
> I'll check it out. Thanks for reporting

Also happens to me when opening an existing server and world after updating to 6.0.28. Error seems to be identical to theirs. Reinstalled .27 and it works fine.

[crash-2024-06-13_11.24.38-server.txt](https://github.com/user-attachments/files/15823300/crash-2024-06-13_11.24.38-server.txt)

**Comment by McJty** [comment]
Should be fixed with 6.0.29
