### ISSUE TITLE
Worlds that I load with the Lost Cities Worldtype take too long to Load

### ISSUE THREAD

**Issue by Ancient-Tome** [McJty/LostCities#63]
When I try to load a Minecraft world with the lost cities world type it just freezes on the loading world building terrain screen and I have to restart my computer in order to get Minecraft to work again. Is there any way for me to fix this? Thanks-NinjaAdvisor

**Comment by McJty** [comment]
Do you give enough memory to minecraft?

**Comment by Ancient-Tome** [comment]
How much do I need, to run your mod correctly? Please respond as soon as possible

**Comment by NinjaAdvisor** [comment]
*For your mod to run correctly.

**Comment by Morpheus1101** [comment]
I've come across the same thing, but only with the rarecities world type, it claims its generating world i can load into the game, but nothing in the way of land generates and ive alotted 8GB of mem, ive also changed a few config settings in the rarecities & general part for LC

**Comment by axieum** [comment]
Ah, I wondered why my worlds weren't loading properly but yet the "Biomes O' Plenty" type would. It loaded fine when I had the `cityChance` set to 0.01. However, finding the cities still very common, I set it to 0.002 which is the default for the `rarecities` preset; this stops my world from loading properly.

**Comment by McJty** [comment]
I'll check out if making cities rare produces some overhead somewhere

**Comment by McJty** [comment]
Hmm. I cannot reproduce this in my test env (which gives 3.5 GB to Minecraft in my case). I used rarecities profile but modified cityChange to 0.001. I'll try to go even lower but maybe some other setting is causing the issue here?

Also is this with or without BOP?

**Comment by McJty** [comment]
Just used cityChance 
    S:cityChance=0.0001

and it works perfectly and fast. I even spawned on a highway so presumably I should be able to find a city at one end :-)

**Comment by McJty** [comment]
Also tried with same chance and BOP and still fine

**Comment by axieum** [comment]
It is due to the city base level being lower than the sea level offset.

**Comment by McJty** [comment]
That was fixed in the 2.0.0 releases (i.e. the sea level offset bug)
