### ISSUE TITLE
How to forbid ALL structures to spawn inside Lost Cities?

### ISSUE THREAD

**Issue by KrokusAstra** [McJty/LostCities#630]
Hi! Cool mod, i like it alot! Good job, keep it up!

Where i could add avoidance for other structures to LC? I installed Lost Cities, and a couple other generation mods, and i nonstop see like a village spawns inside LC, wiping out half of LC (it happened with Integrated Village), or above it like floating village on screen, since generator sees flat surface and tries to slap additional structures on top of it. Can't minecraft see that the chunks already contain structures?
Where i could fix that? Configs in minecraft folder? Jar file itself? Save file's config (why it even exists, wouldn't it be easier for users to make a folder in basic configs, so they won't need to copy save's configs in every single new world)?
I tried to fix it in Integrated village's config, and it kinda worked. But there is a ton of other gen mods. So it's easier and faster to just edit LC config 1 time, not 100500 configs of other mods.

![изображение_2024-07-04_232736913](https://github.com/McJtyMods/LostCities/assets/172990355/7ce79bcb-c59a-4177-8328-5cd03b05b13e)

**Comment by McJty** [comment]
The latest version of Lost Cities (1.19.2, 1.20.1 and 1.21) now supports a way for cities to avoid structures. By default mansions, temples, igloos and swamp huts are avoided but you can add more in the server config

**Comment by UH-1D101** [comment]
> The latest version of Lost Cities (1.19.2, 1.20.1 and 1.21) now supports a way for cities to avoid structures. By default mansions, temples, igloos and swamp huts are avoided but you can add more in the server config

Not only did I enable the "prevent spawning in and around villages" option in the server config within the save file, but I also manually added the village structure to the blacklist. However, villages and structures from The Lost Cities still generate overlappingly. Are there more solutions?

**Comment by McJty** [comment]
Yes it's buggy right now. This is a tough problem to crack. No solution unfortunatelly
