### ISSUE TITLE
Forge and 1.21 Support?

### ISSUE THREAD

**Issue by thetechhimself** [McJty/LostCities#631]
Good evening,

I noted this mod hasn't been updated for Forge since 1.19.x; question is there any plan to port this to Forge for 1.21 or is NeoForge the loader of choice going forward for this mod?

Thanks in a advance

**Comment by McJty** [comment]
What do you mean? This mod exists for:
1.20.1 Forge
1.21: Neoforge

Not sure why you say it hasn't been updated?

**Comment by McJty** [comment]
![image](https://github.com/McJtyMods/LostCities/assets/8188472/db6950cb-1b8d-410f-8f4a-97e8f378523a)

**Comment by thetechhimself** [comment]
<img width="401" alt="Screenshot 2024-07-06 at 8 22 41 AM" src="https://github.com/McJtyMods/LostCities/assets/111404831/0f48a860-a538-4e5f-aedb-e2199d81dae7">
According to CurseForge, 1.21 is only NeoForge...
Now if you're telling me it works just fine with Forge? I'm happy with that typo on CurseForge... https://www.curseforge.com/minecraft/mc-mods/the-lost-cities

**Comment by McJty** [comment]
As I said. Lost cities works on 1.20 with forge and on 1.21 with neoforge

**Comment by thetechhimself** [comment]
I’ll give 1.21 on forge a shot. Worst case? I revert. Just curious with how new 1.21 is if there was a known issue. Thanks again.

**Comment by McJty** [comment]
It will not work on forge. Why but switch to neoforge? Most big mods are going to support that

**Comment by thetechhimself** [comment]
So I'm relatively new to Minecraft mods, I was under the impression Forge had the larger codebase, however if you're telling me that NeoForge is in fact "better" in terms of long term viability, I can redo my mod loader. Somewhat "fun" as I've got Minecraft running on much older OSes, but if that's the better move, than it is.

Also I'm "cloning" my online systems for "dark site" use, which Forge supports as I have some OSes that are truly old that I don't want internet facing, but are great for gaming for the kiddos (and safe as they're offline). I presume Neoforge permits offline cached usage, but that's been my achilles heel, haven't tried it, but probably works.

**Comment by McJty** [comment]
Personally I think NeoForge is the future
