### ISSUE TITLE
Error loading

### ISSUE THREAD

**Issue by Fraddyzzz** [McJty/LostCities#633]
Version 1.16.5
Mod: Lost Cities
Mod version: 1.16-4.0.12-beta
Forge version: 36.2.42

![2024-07-11_15 44 47](https://github.com/user-attachments/assets/b515c84e-500f-4f24-8c59-324dc74ce0ab)

**Comment by Fraddyzzz** [comment]
Version 1.16.5

**Comment by McJty** [comment]
Known error. Delete the config files
