### ISSUE TITLE
Combining RTG and LC

### ISSUE THREAD

**Issue by NathanBruhnte** [McJty/LostCities#635]
Here's the thing: I have an LC and RTG mod in the assembly at the same time and I would like my world to have realistic generation and cities at the same time, please tell me how this can be done? 
I apologize in advance for possible mistakes - English is not my native language

**Comment by McJty** [comment]
Version? ALWAYS specify the version

**Comment by NathanBruhnte** [comment]
1.12.2

пн, 29 июл. 2024 г., 12:47 McJty ***@***.***>:

**Comment by McJty** [comment]
On 1.12.2 it's not possible unfortunatelly. That version is too old for that
