### ISSUE TITLE
version 7.1.8 crash

### ISSUE THREAD

**Issue by mike1000195** [McJty/LostCities#637]
Hey! just letting you know, after hours of pulling my hair out after updating all my mods on my 1.20.1 server trying to stop getting it to crash, i narrowed it down to this mod, and only version 7.1.8. I cant say *exactly* for sure as to what the specific issue is, since i have a lot of other mods too. But when upgrading to 7.1.8, i get a "Caused by: java.util.zip.ZipException: invalid stored block lengths" error, and it crashes it. It produces this error and crashes when loading the previous world, or when generating a new one. 7.1.8 is the only mod in the mods folder when generating a new world. Forge version 47.3.5. Also crashes when going as far back as 47.2.0 (previous stable version that i used on 7.1.2 before updating). Im not sure whats going on here with 7.1.8, but i think something is messed up with server compatibility on 7.1.8. I'll paste the log file in a pastebin link for you so you can take a look. I will revert back to 7.1.7 on forge 47.3.5 (latest 1.20.1 build) for now.

https://pastebin.com/Rh5Ads3A

**Comment by McJty** [comment]
Looks like a corrupt zip. In any case, nothing that I can help with. Try downloading the mod again
