### ISSUE TITLE
[1.19.2] Cannot export part, instead receives error message

### ISSUE THREAD

**Issue by CDRAGONN44** [McJty/LostCities#639]
Hello, I am playing Lost Cities (Version 6.0.29) on Forge (Version 43.4.0), and I was editing this part inside of a city (I made sure to use the command /lostcities editpart), yet when I attempt to export it I receive an error message instead. The message reads, "An unexpected error occurred trying to execute that command". It was working fine when I exported a previous part I had worked on. Any help is appreciated. Thanks! (Also I know for a fact it's not a worldedit incompatability because I was using worldedit on the other part.
![2024-07-31_11 47 47](https://github.com/user-attachments/assets/05d4a42a-d03a-41e2-9c78-40a3de475573)

**Comment by CDRAGONN44** [comment]
Commenting from the day after, this still has not been resolved even when in a new world. I'm not sure if a specific block/block entity from a mod is incompatible with LC, however my suspicions are glass item frame from quark and armor stands (if someone else made a part containing either one of these and it worked please let me know). I already tried using /lostcities debug but it seemed as though nothing happened. I'm not sure if something is corrupted, but I know it lets me edit parts before doing it says this. Any help is appreciated!

Photo from new world:
![2024-08-01_12 33 47](https://github.com/user-attachments/assets/d75834f2-8799-444f-9034-587503d55066)

I still can't figure this out and I may end up needing to look at the output log to find any errors. Forgot to mention I also disabled railways, cellars, and rubble as well as making every building only floor 0 to make editing each individual part easier for myself.

**Comment by McJty** [comment]
Check the logs. I need to see the crash.

Also /incontrol debug dumps info in the log

**Comment by CDRAGONN44** [comment]
> Check the logs. I need to see the crash.

I believe this is the log from when I experienced this:
[2024-08-01-2.log](https://github.com/user-attachments/files/16473904/2024-08-01-2.log)

**Comment by McJty** [comment]
You probably have to many different states in your part which overflows the palette. That's a current limitation in the editor

**Comment by CDRAGONN44** [comment]
Okay, thank you so much for the help! I'll try to use less blocks and will let you know if the error still occurs.

**Comment by McJty** [comment]
Fixed in the new release of Lost Cities where I significantly raised the limit
