### ISSUE TITLE
Unable to load Lost Cities in Minecraft 1.12.2

### ISSUE THREAD

**Issue by phillipinman** [McJty/LostCities#64]
G'day,

First love the mod, thank you for your time :)

Second, got an odd issue where forge refuses to load Lost Cities for MC 1.12.2, it gives the below error:

![image](https://user-images.githubusercontent.com/11908363/33792619-14393b44-dcf9-11e7-8377-2448a7a893b2.png)

I assume this is because the version string it reads is specifically 1.12 and not 1.12.2?

Kind Regards,

**Comment by phillipinman** [comment]
Lost Cities Version: lostcities-1.12-1.0.2

**Comment by McJty** [comment]
That's very weird. Lost Cities is used in many 1.12 packs (like Direwolf 20) with no issues. Double check that you have the right mod in your mods folder

**Comment by phillipinman** [comment]
Apologies, I was careful to check it before submitting this ticket but evidently the error was with me, just redownloaded it and all is well.

Thank you for your time :)
