### ISSUE TITLE
[1.21] Most chests don't use loot tables, so they're just empty

### ISSUE THREAD

**Issue by aaronhowser1** [McJty/LostCities#645]
![image](https://github.com/user-attachments/assets/9ed6c85c-131a-4e0e-9f53-151fd24e361f)

There's chests here but they weren't visible until i placed blocks nearby
![image](https://github.com/user-attachments/assets/1252584d-29d9-4efe-a3d4-2bb4e7bb5997)
![image](https://github.com/user-attachments/assets/2e108ae2-1cbd-402a-9f85-6a052e51e18e)

![image](https://github.com/user-attachments/assets/306b31b5-8b73-4486-8139-f53edeb9448c)

All of those had no loot in them

It's not ALL chests that have no loot, though, like the one below
![image](https://github.com/user-attachments/assets/81db72c0-4e94-4be2-a86e-5b438179e9ff)

This is using `lostcities-1.21-8.0.0`

**Comment by aaronhowser1** [comment]
![image](https://github.com/user-attachments/assets/84df612e-7812-47bb-a48d-828e88ec3a93)

Looks like most of them don't even use loot tables

**Comment by WithersChat** [comment]
There's an option somewhere in the profile files that determines the percentage of chests that have no loot. Are you sure it's at 0?

**Comment by aaronhowser1** [comment]
I'm using totally default, using the bed portal dimension. This could just be intended behavior and you're supposed to configure it?

**Comment by McJty** [comment]
Yes, there is a chance that chests are empty. This can be modified in the profile
