### ISSUE TITLE
Create Railways support for subway generation

### ISSUE THREAD

**Issue by 00p513-dev** [McJty/LostCities#647]
Would be interesting to have subway generate as [Create mod railways](https://modrinth.com/mod/create), allowing more complex networks with nicer trains

Tunnels would have to be wider with actual curves on the junctions

**Comment by McJty** [comment]
That's not something that can be part of Lost Cities as it uses vanilla only. However Lost Cities supports datapack so you can add create support yourselves. Look at the Deceased Craft modpack. It adds create tracks to the railways instead of the vanilla tracks
