### ISSUE TITLE
Unlock Chest 1.20.1

### ISSUE THREAD

**Issue by Fells2** [McJty/LostCities#648]
Hi, where can I find information about how to open a locked chest? I didn't see any information in the page

**Comment by McJty** [comment]
What do you mean? Lost Cities doesn't lock chests? Why is it locked?

**Comment by Fells2** [comment]
> What do you mean? Lost Cities doesn't lock chests? Why is it locked?

I mean, there chests that are locked, I dont know why or how to unlock them. And I think that is about the mod of The Lost Cities

**Comment by McJty** [comment]
Lost Cities doesn't lock chests. Must be another mod. What message do you get when you try to open them?

**Comment by Fells2** [comment]
> Lost Cities doesn't lock chests. Must be another mod. What message do you get when you try to open them?

It says ¨Chest is locked¨
Is a chest generated in Lost Cities map, is weird, maybe is part of the mod Keerdm's Zombie Apocalypse Essentials
that is like an extension of Lost Cities

**Comment by McJty** [comment]
Then best check there

**Comment by Fells2** [comment]
Yep, so the problem is not in the mod of Lost Cities, thanks for helping :D
