### ISSUE TITLE
Errror loading in minecraft 1.21

### ISSUE THREAD

**Issue by Ital1anJ** [McJty/LostCities#656]
error not specified by client. Crash report:

TRANSFORMER/forge@51.0.33/net.minecraftforge.logging.CrashReportExtender.lambda$dumpModLoadingCrashReport$7(CrashReportExtender.java:52) ~[forge-1.21-51.0.33-universal.jar!/:?] {re:classloading}
-- NO MOD INFO AVAILABLE --
Details:
	Mod File: NO FILE INFO
	Failure message: Invalid mod file found C:\Users\jtweh\curseforge\minecraft\Instances\Totality\mods\lostcities-1.21-8.2.1.jar
	Mod Version: NO MOD INFO AVAILABLE
	Mod Issue URL: NOT PROVIDED
	Exception message: MISSING EXCEPTION MESSAGE

**Comment by McJty** [comment]
Lost Cities needs NeoForge for 1.21. It doesn't work with Forge
