### ISSUE TITLE
Cant open Vanilla Chests

### ISSUE THREAD

**Issue by ghost** [McJty/LostCities#66]
since the last LostSouls update I cant open any vanilla chests

"Building not safe", in a normal Overworld, not a Lost City world/Dimension

Lost Souls 1.12.1.1.0

**Comment by McJty** [comment]
That's one of the new features of this release  (see changelog). You can disable this in the config

**Comment by ghost** [comment]
shouldnt it only happen in a LostCities dimension? and only inside buildings?

**Comment by McJty** [comment]
Oh misread. I'll check it out then

**Comment by McJty** [comment]
Fixed next release
