### ISSUE TITLE
[1.20.1] Lost Cities Not Generating With TerraFirmaCraft World Type

### ISSUE THREAD

**Issue by dudebehinddude** [McJty/LostCities#666]
When TerraFirmaCraft is installed, and a world is made with the TerraFirmaCraft world type, and the lost cities profile is set to default, lost cities will not generate in the world. I have tried to `/lostcities locate` different city parts, which does return finding multiple pieces, but when teleporting to them, but they do not appear in the world.

![image](https://github.com/user-attachments/assets/23a8686d-61cf-4e48-8e5e-385b3a39159a)

**Steps to reproduce:**
1. Install TFC and Lost Cities
2. Create a world and enable lost cities generation
3. No lost cities structures generate

Note that when the default (vanilla) world type is selected, structures generate without issue.

**Mod list:**
Patchouli (v1.20.1-84-forge)
TerraFirmaCraft (v3.2.12)
The Lost Cities (v1.20-7.3.5)

**Comment by McJty** [comment]
That's not a bug in Lost Cities. It's up to TFC to call the correct pieces so that features can work

**Comment by dudebehinddude** [comment]
Do you mean features as in Minecraft features? [I believe TFC uses biome tags](https://terrafirmacraft.github.io/Documentation/1.20.x/worldgen/tags/#biome-tags) to place them as opposed to how they are added in vanilla. I don't know if it's outside of the scope of this mod to add compatibility for that with this mod though.

**Comment by McJty** [comment]
Well then it's up to a datapack to add the Lost Cities feature

**Comment by dudebehinddude** [comment]
It's only [these two](https://github.com/McJtyMods/LostCities/tree/1.20/src/main/resources/data/lostcities/forge/biome_modifier) features that this mod uses to generate the cities I am assuming? And should this issue be closed then?

**Comment by McJty** [comment]
yep
