### ISSUE TITLE
Crash with Sponge (Exception ticking world)

### ISSUE THREAD

**Issue by Kira076** [McJty/LostCities#67]
### Version
Latest - 1.1x-1.0.2

### The Problem
I can load up a world my server just fine the first time, generating a new world, and it will run perfectly. But if I stop the server and run it again, once a player connects the server crashes (either immediately or very shortly after).

### The crash log
[crash-2018-01-01_12.41.52-server.txt](https://github.com/McJty/LostCities/files/1595568/crash-2018-01-01_12.41.52-server.txt)

### Additional info
It seems to only happen when re-opening a world, and it seems to happen only when Sponge is installed.

### Update
The issue appears to be outlined [Here](https://github.com/SpongePowered/SpongeForge/issues/1815)

**Comment by McJty** [comment]
As far as I can see this is not a bug in Lost Cities
