### ISSUE TITLE
Monorail intersections handled poorly

### ISSUE THREAD

**Issue by josephcsible** [McJty/LostCities#77]
![2018-01-27_17 57 35](https://user-images.githubusercontent.com/16061266/35477257-515daf90-038d-11e8-82bf-a234014af3c0.png)
Two of the directions of 4-way intersections are totally blocked. "Space" preset.

**Comment by McJty** [comment]
yes that's a bit intentaional as you cannot really do a rail crossing in minecraft. Or do you have any suggestions on this?

**Comment by josephcsible** [comment]
Some ideas:
1. A somewhat complex redstone-based auto-switcher ![2018-01-28_00 23 08](https://user-images.githubusercontent.com/16061266/35479279-859fd8c6-03c1-11e8-94db-33524c8b92c9.png) All it needs is 5 torches, 4 detector rails, and some redstone dust: ![2018-01-14_17 20 23](https://user-images.githubusercontent.com/16061266/35479284-8ddb5902-03c1-11e8-8400-cfab2f7504bf.png)
2. Offset all of the north-south tracks to always be higher than the east-west tracks. The tunnels are big enough that you can stack 2 and have them fit. IMO, this would look best if you made the lower set of tracks 1 block below the current height, and the upper set of tracks 2 blocks above the current height. ![2018-01-28_00 27 22](https://user-images.githubusercontent.com/16061266/35479309-101b22e4-03c2-11e8-905b-2800df5f22a2.png)
3. Have the tracks temporarily cross over and under each other ![2018-01-28_00 02 04](https://user-images.githubusercontent.com/16061266/35479173-d09cb7fc-03be-11e8-9771-215075bcbb66.png)
4. Have the tracks turn instead of going straight ![2018-01-28_00 19 34](https://user-images.githubusercontent.com/16061266/35479259-f74b5d2a-03c0-11e8-9b45-0dbd263aa6df.png)

**Comment by McJty** [comment]
Hmm some nice idea. I'll see what is possible

**Comment by josephcsible** [comment]
Fixed with a variant of idea 3 by 2497caf
