### ISSUE TITLE
Tall Cities - adjust explosion presets

### ISSUE THREAD

**Issue by Seth0067** [McJty/LostCities#8]
Loos like the explosion presets are tuned for regular world gen/height only, so if you generate a "Tall Cities" variant, you end up with a lot of smaller looking holes always low to the ground.  

The result are building that look like they shouldnt be standing or buildings with holes in them a la the 1990s Godzilla movie.
[Godzilla walked through this!](http://imgur.com/a/8gUJc)

Probably on your list of to dos, but thought I would mention it.

**Comment by Seth0067** [comment]
I'm tweaking values in the configs and will share some adjustements in case you want to use a different set.  Might be useful to have command that reloads configs without restart.

**Comment by Seth0067** [comment]
As I mentioned, here's some values I seem reasonably happy with.  
[explosions in the sky](https://pastebin.com/205fVnVa)

**Comment by McJty** [comment]
Thanks. I'll include them for next version
