### ISSUE TITLE
Awkward space under monorail

### ISSUE THREAD

**Issue by josephcsible** [McJty/LostCities#80]
![2018-01-27_18 25 29](https://user-images.githubusercontent.com/16061266/35477394-84752bd6-038f-11e8-80c2-bdaf51a97993.png)

There's a 2-block-high 4-block-wide space under monorails, which is plenty big enough for players and mobs to exist in, but it's impossible to get in or out of it without breaking a block somewhere.

**Comment by McJty** [comment]
I think mobs don't spawn on glass normally?

**Comment by josephcsible** [comment]
I note that solution 2 to issue #77 will resolve this, as the gap under there would then only be 1 block high.

**Comment by josephcsible** [comment]
Fixed by 73004ad
