### ISSUE TITLE
Unwanted fossil generation

### ISSUE THREAD

**Issue by josephcsible** [McJty/LostCities#83]
Fossils currently generate floating in space, which is rather odd. You should listen for [DecorateBiomeEvent.Decorate](https://github.com/MinecraftForge/MinecraftForge/blob/9a2ebd45d720f229b1fbf6d3368a4603732307e4/src/main/java/net/minecraftforge/event/terraingen/DecorateBiomeEvent.java#L103) on the TERRAIN_GEN_BUS (not on the EVENT_BUS!) to cancel these.

**Comment by McJty** [comment]
I actually already handle that event for other features. I will add a config option to disable this (you don't want them disabled for all profiles)

**Comment by McJty** [comment]
Fixed in next release
