### ISSUE TITLE
Lost Cities loot tables are unregistered

### ISSUE THREAD

**Issue by Daomephsta** [McJty/LostCities#87]
The loot tables you add aren't registered. This is done by calling `LootTableList.register()` with the loot table's resloc as the argument. While unregistered loot tables are visible to the `LootTableManager`, they don't exist in the master list of all loot tables that exist. 

Note: If you register the loot tables in the initializer of a static field, as vanilla does, please add a dummy method that you call in preinit to force the JVM to initialize the class. Otherwise they won't be registered when mods like LootTweaker check the master list to make sure a table with a particular name exists.

**Comment by tachometer74** [comment]
Second this request. 

I am far from an expert but I have yet to find a way to modify 'lostcitychest' or 'raildungeonchest'.

Ideally LootTweaker and/or Recurrent Complex would be able to modify them (vs. <world>/data/loot_tables/lost_cities/lostcitychest.json...which is challenging for modpack creation).

**Comment by McJty** [comment]
Solved next release
