### ISSUE TITLE
[1.12.2] Client Crash Dim 111 

### ISSUE THREAD

**Issue by chezpaul** [McJty/LostCities#88]
Minecraft 1.12.2, Forge 2507, Lost Cities 2.0.0

Once every 3 launches or so, I get this client crash:

[Log](https://pastebin.com/rUKUMCq0)

**Comment by McJty** [comment]
When you do what exactly?

**Comment by chezpaul** [comment]
Client just never boots. It crashes towards the end of launching

**Comment by josephcsible** [comment]
I suspect it's a conflict with another one of your mods. Can you try to narrow down which one it could be?

**Comment by chezpaul** [comment]
With the newest Lost Cities 2.0.1 update, now my client will ALWAYS crash. Something changed.
https://pastebin.com/Mf2qa0QX

**Comment by McJty** [comment]
Well besides a mod conflict I have no clue what can cause this

**Comment by McJty** [comment]
My guess is some other mod is trying to use that dimension id. Either change the id for Lost Cities or try to find the other mod that uses that dimension and change that

**Comment by chezpaul** [comment]
Damn, I thought you being the mod guru could read between the lines. ;-)

**Comment by chezpaul** [comment]
I'll try changing ID's. Thanks

**Comment by chezpaul** [comment]
Changing to 24 did the trick.
198 made it crash.
Maybe some mod is not allowing higher numbered dims?

**Comment by McJty** [comment]
Or some mod is allocating a whole lot of dimensions in that range. Anyway it is ok now
