### ISSUE TITLE
[1.12.2] Sponge-server crash

### ISSUE THREAD

**Issue by Vitali8** [McJty/LostCities#89]
During the first server startup after installing the mod, everything was fine, but during the second run server crashed. Before that, I changed the parameter `S: dimensionProfile = biosphere` in the config file.

SpongeAPI: 7.1.0-SNAPSHOT-b163786
SpongeForge: 1.12.2-2586-7.1.0-BETA-2868
Minecraft Forge: 14.23.1.2607
Here crash-log: https://pastebin.com/9guj23Dz

**Comment by McJty** [comment]
I can't really solve this as I have no other solution for this as far as I node. Atm Lost Cities and Sponge are not compatible

**Comment by josephcsible** [comment]
I may know how to fix this; I'll take a look tonight.

**Comment by josephcsible** [comment]
Never mind; I don't. @Vitali8 Can you report this to Sponge's issue tracker?

**Comment by Vitali8** [comment]
https://github.com/SpongePowered/SpongeForge/issues/1815
