### ISSUE TITLE
[1.12] .8beta Crash on world generation 

### ISSUE THREAD

**Issue by Seth0067** [McJty/LostCities#9]
[crash report](https://pastebin.com/Z6JHWkH8)

This was the latest.log from a standard/default Lost Cities (BoP) world type.  Also tried with Tall Cities and non BoP type world with same result.

**Comment by McJty** [comment]
I will check it out

**Comment by McJty** [comment]
Fixed in 0.0.8beta2 (I hope) which should be approved soon
