### ISSUE TITLE
Invalid maximum heap size

### ISSUE THREAD

**Issue by Carmana0** [McJty/LostCities#91]
Hello. I was following the guide to start a cities server, but I get this message everytime I try to launch. Please help when you can, Thank you for your time.

![cities_error](https://user-images.githubusercontent.com/36222003/35903061-8ffd6936-0bab-11e8-9939-d350edf1b690.png)

**Comment by McJty** [comment]
That's not really a Lost City bug. It looks as if you're using a 32-bit java
