### ISSUE TITLE
[Suggestion] Add Sky Isle Cities World Gen Option

### ISSUE THREAD

**Issue by MokahTGS** [McJty/LostCities#94]
I was wondering if you might be able to add a new type of Lost Cities world gen that mixes the Lost Cities with the Sky Isle type of world gen.  I think it would be a fun world to play in with globs of ruined cities floating off in the sky.

**Comment by McJty** [comment]
That's already there (the 'floating' profile). Just select that when creating a world

**Comment by MokahTGS** [comment]
SWEET!  I didn't know that was an option, Thanks!
