### ISSUE TITLE
Above bedrock in caverns setting: Villages and lake generation

### ISSUE THREAD

**Issue by kragnoth** [McJty/LostCities#98]
This is on 1.12.2 at least (2615 latest test branch)
Lost cities version: 1.12-2.0.2

Lakes and villages (and forestry hives) spawn above bedrock level.  Passive mobs also spawn above bedrock (most likely because it counts as seeing the sky and having light, even though its 0 light)

Not a huge bug, but fixing this could help squeeze a few extra TPS from that world gen type.

**Comment by McJty** [comment]
I just saw that lakes are actually already disabled for cavern but you probably did not remove your lost city configs when upgrading

**Comment by McJty** [comment]
Anyway, villages are now also disabled next version
